"""
Sliding-window object detection inference

This module provides tiled inference for detection models on native-resolution images.
It generates overlapping windows, maps tile detections back to full-image coordinates,
and merges duplicate detections across tile boundaries.

Generated by gpt-5.5 xhigh.
"""

from typing import Any
from typing import Literal
from typing import Optional

import torch
from torch.nn import functional as F
from torchvision.ops import boxes as box_ops

from birder.data.collators.detection import batch_images
from birder.inference.wbf import fuse_detections_wbf_single

Detection = dict[str, torch.Tensor]
Window = tuple[int, int, int, int]
MergeMode = Literal["wbf", "nms", "nmm", "greedy_nmm", "none"]


def _generate_windows(
    image_size: tuple[int, int], tile_size: tuple[int, int], overlap: tuple[int, int]
) -> list[Window]:
    """
    Generate sliding-window boxes for an image

    Inputs use (height, width). Returned windows use xyxy order.
    """

    image_h, image_w = image_size
    tile_h, tile_w = tile_size
    overlap_h, overlap_w = overlap
    if overlap_h >= tile_h or overlap_w >= tile_w:
        raise ValueError("overlap must be smaller than tile_size")

    if image_h <= tile_h:
        y_starts = [0]
    else:
        y_stride = tile_h - overlap_h
        y_last_start = image_h - tile_h
        y_starts = list(range(0, y_last_start, y_stride))
        if y_starts[-1] != y_last_start:
            y_starts.append(y_last_start)

    if image_w <= tile_w:
        x_starts = [0]
    else:
        x_stride = tile_w - overlap_w
        x_last_start = image_w - tile_w
        x_starts = list(range(0, x_last_start, x_stride))
        if x_starts[-1] != x_last_start:
            x_starts.append(x_last_start)

    windows: list[Window] = []
    for y1 in y_starts:
        y2 = min(y1 + tile_h, image_h)
        for x1 in x_starts:
            x2 = min(x1 + tile_w, image_w)
            windows.append((x1, y1, x2, y2))

    return windows


def _clip_detections_to_image(detection: Detection, image_size: tuple[int, int]) -> Detection:
    image_h, image_w = image_size
    boxes = detection["boxes"].clone()
    boxes[:, 0::2] = boxes[:, 0::2].clamp(min=0, max=image_w)
    boxes[:, 1::2] = boxes[:, 1::2].clamp(min=0, max=image_h)

    clipped = dict(detection)
    clipped["boxes"] = boxes

    return clipped


def _filter_valid_detections(detection: Detection) -> Detection:
    boxes = detection["boxes"]
    keep = torch.logical_and(boxes[:, 2] > boxes[:, 0], boxes[:, 3] > boxes[:, 1])

    return {
        "boxes": boxes[keep],
        "labels": detection["labels"][keep],
        "scores": detection["scores"][keep],
    }


def _empty_detection(device: torch.device) -> Detection:
    return {
        "boxes": torch.zeros((0, 4), device=device),
        "labels": torch.zeros((0,), dtype=torch.int64, device=device),
        "scores": torch.zeros((0,), device=device),
    }


def _concat_detections(detections: list[Detection]) -> Detection:
    if len(detections) == 0:
        return _empty_detection(torch.device("cpu"))

    device = detections[0]["boxes"].device
    non_empty = [detection for detection in detections if detection["boxes"].numel() > 0]
    if len(non_empty) == 0:
        return _empty_detection(device)

    return {
        "boxes": torch.concat([detection["boxes"] for detection in non_empty], dim=0),
        "labels": torch.concat([detection["labels"] for detection in non_empty], dim=0),
        "scores": torch.concat([detection["scores"] for detection in non_empty], dim=0),
    }


def _box_ios(boxes1: torch.Tensor, boxes2: torch.Tensor) -> torch.Tensor:
    boxes1 = boxes1.to(dtype=torch.float32)
    boxes2 = boxes2.to(dtype=torch.float32)
    lt = torch.maximum(boxes1[:, None, :2], boxes2[None, :, :2])
    rb = torch.minimum(boxes1[:, None, 2:], boxes2[None, :, 2:])
    wh = (rb - lt).clamp(min=0)
    inter = wh[:, :, 0] * wh[:, :, 1]

    area1 = (boxes1[:, 2] - boxes1[:, 0]) * (boxes1[:, 3] - boxes1[:, 1])
    area2 = (boxes2[:, 2] - boxes2[:, 0]) * (boxes2[:, 3] - boxes2[:, 1])
    smaller_area = torch.minimum(area1[:, None], area2[None, :])

    return torch.where(smaller_area > 0, inter / smaller_area, torch.zeros_like(inter))


def _merge_detection_group(detection: Detection, indexes: torch.Tensor) -> Detection:
    keep = indexes[0]
    box = detection["boxes"][keep]
    score = detection["scores"][keep]
    label = detection["labels"][keep]
    for merge_idx in indexes[1:]:
        merge_box = detection["boxes"][merge_idx]
        box = torch.concat((torch.minimum(box[:2], merge_box[:2]), torch.maximum(box[2:], merge_box[2:])), dim=0)
        if detection["scores"][merge_idx] > score:
            score = detection["scores"][merge_idx]
            label = detection["labels"][merge_idx]

    return {
        "boxes": box.unsqueeze(0),
        "labels": label.reshape(1),
        "scores": score.reshape(1),
    }


def _sort_detections(detection: Detection) -> Detection:
    order = torch.argsort(detection["scores"], descending=True)

    return {
        "boxes": detection["boxes"][order],
        "labels": detection["labels"][order],
        "scores": detection["scores"][order],
    }


def _score_tiebreak_order(detection: Detection, indexes: torch.Tensor) -> torch.Tensor:
    order = indexes
    boxes = detection["boxes"]
    scores = detection["scores"]
    for key in (boxes[:, 3], boxes[:, 2], boxes[:, 1], boxes[:, 0], -scores):
        order = order[torch.argsort(key[order], stable=True)]

    return order


def _merge_greedy_nmm_ios(detection: Detection, match_threshold: float) -> Detection:
    """
    Greedy non-maximum merging
    """

    merged_groups: list[Detection] = []
    consumed = torch.zeros((detection["boxes"].size(0),), dtype=torch.bool, device=detection["boxes"].device)

    for label in torch.unique(detection["labels"]):
        label_indexes = torch.where(detection["labels"] == label)[0]
        order = _score_tiebreak_order(detection, label_indexes)
        for pos, keep in enumerate(order):
            if consumed[keep].item() is True:
                continue

            candidates = order[pos + 1 :]
            candidates = candidates[consumed[candidates] == 0]
            if candidates.numel() > 0:
                matches = _box_ios(detection["boxes"][keep].unsqueeze(0), detection["boxes"][candidates]).squeeze(0)
                merge_indexes = candidates[matches >= match_threshold]
                consumed[merge_indexes] = True
                group = torch.concat((keep.reshape(1), merge_indexes), dim=0)
            else:
                group = keep.reshape(1)

            consumed[keep] = True
            merged_groups.append(_merge_detection_group(detection, group))

    return _sort_detections(_concat_detections(merged_groups))


def _nmm_label_groups_ios(detection: Detection, indexes: torch.Tensor, match_threshold: float) -> list[torch.Tensor]:
    size = indexes.size(0)
    if size == 0:
        return []

    local_detection = {
        "boxes": detection["boxes"][indexes],
        "labels": detection["labels"][indexes],
        "scores": detection["scores"][indexes],
    }
    local_indexes = torch.arange(size, device=indexes.device)
    order = _score_tiebreak_order(local_detection, local_indexes)

    boxes = local_detection["boxes"]
    rank = torch.empty((size,), dtype=torch.long, device=indexes.device)
    rank[order] = torch.arange(size, device=indexes.device)
    dominates = rank[:, None] < rank[None, :]
    candidates_of = dominates & (_box_ios(boxes, boxes) >= match_threshold)

    keep_to_merge: dict[int, list[int]] = {}
    merge_to_keep = torch.full((size,), -1, dtype=torch.long, device=indexes.device)
    for current in order.tolist():
        matched = torch.where(candidates_of[current])[0].tolist()
        keep_idx = int(merge_to_keep[current].item())
        if keep_idx < 0:
            keep_to_merge[current] = []
            keep_idx = current

        merge_list = keep_to_merge[keep_idx]
        for match_idx in matched:
            if merge_to_keep[match_idx].item() < 0 and match_idx not in merge_list:
                merge_list.append(match_idx)
                merge_to_keep[match_idx] = keep_idx

    return [
        indexes[torch.tensor([keep_idx, *merge_indexes], dtype=torch.long, device=indexes.device)]
        for keep_idx, merge_indexes in keep_to_merge.items()
    ]


def _merge_nmm_ios(detection: Detection, match_threshold: float) -> Detection:
    """
    Non-maximum merging
    """

    merged_groups: list[Detection] = []
    for label in torch.unique(detection["labels"]):
        label_indexes = torch.where(detection["labels"] == label)[0]
        for group in _nmm_label_groups_ios(detection, label_indexes, match_threshold):
            merged_groups.append(_merge_detection_group(detection, group))

    return _sort_detections(_concat_detections(merged_groups))


def _merge_sliding_window_detections(
    detections: list[Detection], mode: MergeMode, merge_threshold: float, filter_threshold: Optional[float] = None
) -> Detection:
    if mode == "wbf":
        skip_box_thr = 0.0 if filter_threshold is None else filter_threshold
        return fuse_detections_wbf_single(
            detections, iou_thr=merge_threshold, skip_box_thr=skip_box_thr, conf_type="avg"
        )

    merged = _concat_detections(detections)
    if filter_threshold is not None:
        keep = merged["scores"] >= filter_threshold
        merged = {
            "boxes": merged["boxes"][keep],
            "labels": merged["labels"][keep],
            "scores": merged["scores"][keep],
        }

    if mode == "none" or merged["boxes"].numel() == 0:
        return merged

    if mode == "nms":
        keep = box_ops.batched_nms(merged["boxes"], merged["scores"], merged["labels"], merge_threshold)
        return {
            "boxes": merged["boxes"][keep],
            "labels": merged["labels"][keep],
            "scores": merged["scores"][keep],
        }

    if mode == "greedy_nmm":
        return _merge_greedy_nmm_ios(merged, merge_threshold)

    if mode == "nmm":
        return _merge_nmm_ios(merged, merge_threshold)

    raise ValueError(f"Unsupported merge mode: {mode}")


def _map_window_detection(detection: Detection, window: Window, image_size: tuple[int, int]) -> Detection:
    x1, y1, _, _ = window
    mapped = dict(detection)
    mapped["boxes"] = detection["boxes"] + detection["boxes"].new_tensor([x1, y1, x1, y1])
    mapped = _clip_detections_to_image(mapped, image_size)
    mapped = _filter_valid_detections(mapped)

    return mapped


def _infer_global_image(
    net: torch.nn.Module | torch.ScriptModule,
    image: torch.Tensor,
    global_size: tuple[int, int],
    channels_last: bool,
    size_divisible: int,
    **kwargs: Any,
) -> Detection:
    image_size = (image.shape[-2], image.shape[-1])
    global_image = F.interpolate(image.unsqueeze(0), size=global_size, mode="bilinear", align_corners=False).squeeze(0)
    inputs, masks, global_image_sizes = batch_images([global_image], size_divisible)
    if channels_last is True:
        inputs = inputs.to(memory_format=torch.channels_last)

    detections, _ = net(inputs, masks=masks, image_sizes=global_image_sizes, **kwargs)
    detection = detections[0]
    if detection["boxes"].numel() > 0 and global_image_sizes[0] != image_size:
        scale_w = image_size[1] / global_image_sizes[0][1]
        scale_h = image_size[0] / global_image_sizes[0][0]
        scaled = dict(detection)
        scaled["boxes"] = detection["boxes"] * detection["boxes"].new_tensor([scale_w, scale_h, scale_w, scale_h])
        detection = scaled

    detection = _clip_detections_to_image(detection, image_size)

    return _filter_valid_detections(detection)


def infer_sliding_window(
    net: torch.nn.Module | torch.ScriptModule,
    image: torch.Tensor,
    global_size: Optional[tuple[int, int]],
    tile_size: tuple[int, int],
    overlap: tuple[int, int],
    tile_batch_size: int,
    merge_mode: MergeMode,
    merge_threshold: float,
    filter_threshold: Optional[float] = None,
    channels_last: bool = False,
    size_divisible: int = 32,
    **kwargs: Any,
) -> Detection:
    image_size = (image.shape[-2], image.shape[-1])
    windows = _generate_windows(image_size, tile_size, overlap)
    detections: list[Detection] = []

    for start in range(0, len(windows), tile_batch_size):
        tile_windows = windows[start : start + tile_batch_size]
        tile_images = [image[:, y1:y2, x1:x2] for x1, y1, x2, y2 in tile_windows]
        inputs, masks, tile_image_sizes = batch_images(tile_images, size_divisible)
        if channels_last is True:
            inputs = inputs.to(memory_format=torch.channels_last)

        tile_detections, _ = net(inputs, masks=masks, image_sizes=tile_image_sizes, **kwargs)
        for detection, window in zip(tile_detections, tile_windows):
            detection = _map_window_detection(detection, window, image_size)
            detections.append(detection)

    if global_size is not None:
        detections.append(
            _infer_global_image(
                net, image, global_size, channels_last=channels_last, size_divisible=size_divisible, **kwargs
            )
        )

    return _merge_sliding_window_detections(
        detections, mode=merge_mode, merge_threshold=merge_threshold, filter_threshold=filter_threshold
    )
