stages:
  - test
  - build
  - deploy

all-test-job:
  stage: test
  image: python:3.10
  only:
    - tags
  variables:
    NETWORK_TESTS: 1
  script:
    - pip install -r requirements/requirements-pytorch-cpu.txt
    - pip install -r requirements/requirements-dev.txt
    - inv ci

build-job:
  stage: build
  image: python:3.10
  only:
    - tags
  script:
    - pip install --upgrade pip wheel build twine
    - python -m build
    - twine check dist/*
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: deploy
  image: python:3.10
  only:
    - tags
  script:
    - pip install -r requirements/requirements-dev.txt
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  environment: production
