[bumpver]
current_version = "v0.0.2-alpha"
version_pattern = "vMAJOR.MINOR.PATCH[-TAG]"
commit_message = "Bump version: {old_version} -> {new_version}"
tag_message = "{new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"birder/__init__.py" = ['^__version__ = "{version}"$']
