version: "3.8"

services:
  api_http:
    build:
      context: .
      dockerfile: docker/api-http.Dockerfile
    image: "birder-api-http:0.1.0"
    expose:
      - "80/tcp"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    image: "birder-app:0.1.0"
    ports:
      - "80:80/tcp"
    depends_on:
      - api_http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
