"""
Generated by gpt-5.6-sol max.
"""

import multiprocessing as mp
from collections.abc import Callable
from collections.abc import Iterable
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Any

import torch
from torch.nn import functional as F
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data.dataloader import default_collate

EPOCH_SEED_STRIDE = 1_000_003


class NaFlexCollator:
    """
    Patchify and collate variable-size images into padded patch sequences

    Images must be tensors of shape (C, H, W) whose height and width are divisible by the
    configured patch size. Patch values are flattened in the same order as a
    Conv2d patch projection with a square, non-overlapping kernel.

    The collated inputs contain the padded patch sequences, their two-dimensional
    grid sizes, and a mask whose True values identify valid patches.

    Parameters
    ----------
    input_offset
        Position of the image in each sample.
    patch_size
        Height and width of each square image patch.
    """

    def __init__(self, input_offset: int, patch_size: int) -> None:
        if patch_size <= 0:
            raise ValueError(f"Patch size must be positive, got {patch_size}")

        self.patch_size = patch_size
        self.input_offset = input_offset

    def _patchify(self, image: torch.Tensor) -> tuple[torch.Tensor, tuple[int, int]]:
        C, H, W = image.size()
        grid_h = H // self.patch_size
        grid_w = W // self.patch_size
        patches = image.reshape(C, grid_h, self.patch_size, grid_w, self.patch_size)
        patches = patches.permute(1, 3, 0, 2, 4).reshape(grid_h * grid_w, -1)

        return (patches, (grid_h, grid_w))

    def _patchify_images(self, images: tuple[torch.Tensor, ...]) -> tuple[list[torch.Tensor], list[tuple[int, int]]]:
        patch_sequences: list[torch.Tensor] = []
        grid_sizes: list[tuple[int, int]] = []
        for image in images:
            patches, grid_size = self._patchify(image)
            patch_sequences.append(patches)
            grid_sizes.append(grid_size)

        return (patch_sequences, grid_sizes)

    def _collate_inputs(
        self, patch_sequences: list[torch.Tensor], grid_sizes: list[tuple[int, int]]
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        padded_patches = pad_sequence(patch_sequences, batch_first=True)
        valid_mask = pad_sequence(
            [patches.new_ones(patches.size(0), dtype=torch.bool) for patches in patch_sequences],
            batch_first=True,
        )

        grid_sizes_tensor = torch.tensor(grid_sizes, dtype=torch.int64, device=padded_patches.device)
        return (padded_patches, grid_sizes_tensor, valid_mask)

    def __call__(self, batch: list[tuple[Any, ...]]) -> tuple[Any, ...]:
        batch_fields = list(zip(*batch))
        images = batch_fields[self.input_offset]
        patch_sequences, grid_sizes = self._patchify_images(images)
        collated_inputs = self._collate_inputs(patch_sequences, grid_sizes)
        collated_batch = [
            collated_inputs if idx == self.input_offset else default_collate(list(field))
            for idx, field in enumerate(batch_fields)
        ]

        return tuple(collated_batch)


class NaFlexTrainingCollator(NaFlexCollator):
    """NaFlex collator for training samples of the form (image, target)"""

    def __init__(self, patch_size: int) -> None:
        super().__init__(0, patch_size)


class NaFlexMixupTrainingCollator(NaFlexTrainingCollator):
    """
    Apply regional MixUp to variable-size patch grids before padding

    Each sample is paired with the preceding sample in the batch. The largest patch
    rectangle shared by the two grids is blended at independently sampled source and
    destination positions. The recipient grid remains unchanged and the soft-target
    weights account for the fraction of its patches that were mixed.

    The variable-size regional MixUp strategy is adapted from timm's NaFlex MixUp:
    https://github.com/huggingface/pytorch-image-models/blob/main/timm/data/naflex_mixup.py

    Parameters
    ----------
    patch_size
        Height and width of each square image patch.
    num_classes
        Number of classes used for one-hot encoding.
    alpha
        Hyperparameter of the Beta distribution used for MixUp.
    p
        Probability of applying MixUp to a batch.
    """

    def __init__(self, patch_size: int, num_classes: int, alpha: float, p: float = 0.5) -> None:
        super().__init__(patch_size)
        if num_classes < 1:
            raise ValueError(f"Number of classes must be positive, got {num_classes}")
        if alpha <= 0:
            raise ValueError(f"Alpha must be positive, got {alpha}")
        if p < 0.0 or p > 1.0:
            raise ValueError(f"Probability must be in range [0, 1], got {p}")

        self.num_classes = num_classes
        self.p = p
        self._lambda_dist = torch.distributions.Beta(alpha, alpha)

    @staticmethod
    def _random_offset(grid_size: int, overlap_size: int) -> int:
        max_offset = grid_size - overlap_size
        if max_offset == 0:
            return 0

        return int(torch.randint(max_offset + 1, ()).item())

    def _mixup(
        self,
        patch_sequences: list[torch.Tensor],
        grid_sizes: list[tuple[int, int]],
        targets: torch.Tensor,
    ) -> tuple[list[torch.Tensor], torch.Tensor]:
        lambda_param = float(self._lambda_dist.sample().item())
        mixed_sequences: list[torch.Tensor] = []
        effective_lambdas: list[float] = []

        for idx, (patches, (grid_h, grid_w)) in enumerate(zip(patch_sequences, grid_sizes)):
            donor_idx = (idx - 1) % len(patch_sequences)
            donor_patches = patch_sequences[donor_idx]
            donor_grid_h, donor_grid_w = grid_sizes[donor_idx]

            overlap_h = min(grid_h, donor_grid_h)
            overlap_w = min(grid_w, donor_grid_w)
            destination_top = self._random_offset(grid_h, overlap_h)
            destination_left = self._random_offset(grid_w, overlap_w)
            source_top = self._random_offset(donor_grid_h, overlap_h)
            source_left = self._random_offset(donor_grid_w, overlap_w)

            patch_grid = patches.reshape(grid_h, grid_w, -1).clone()
            donor_grid = donor_patches.reshape(donor_grid_h, donor_grid_w, -1)
            destination_region = patch_grid[
                destination_top : destination_top + overlap_h,
                destination_left : destination_left + overlap_w,
            ]
            source_region = donor_grid[
                source_top : source_top + overlap_h,
                source_left : source_left + overlap_w,
            ]
            destination_region.mul_(lambda_param).add_(source_region, alpha=1.0 - lambda_param)
            mixed_sequences.append(patch_grid.flatten(0, 1))

            overlap_fraction = (overlap_h * overlap_w) / (grid_h * grid_w)
            effective_lambdas.append(1.0 - ((1.0 - lambda_param) * overlap_fraction))

        targets = F.one_hot(targets, num_classes=self.num_classes).to(  # pylint: disable=not-callable
            dtype=patch_sequences[0].dtype
        )
        donor_targets = targets.roll(1, dims=0)
        lambda_tensor = targets.new_tensor(effective_lambdas).unsqueeze(1)
        targets.mul_(lambda_tensor).add_(donor_targets * (1.0 - lambda_tensor))

        return (mixed_sequences, targets)

    def __call__(self, batch: list[tuple[Any, ...]]) -> tuple[Any, ...]:
        batch_fields = list(zip(*batch))
        images = batch_fields[self.input_offset]
        targets = default_collate(list(batch_fields[1]))
        patch_sequences, grid_sizes = self._patchify_images(images)

        if len(patch_sequences) > 1 and (self.p == 1.0 or torch.rand(()).item() < self.p):
            patch_sequences, targets = self._mixup(patch_sequences, grid_sizes, targets)

        return (self._collate_inputs(patch_sequences, grid_sizes), targets)


class NaFlexPathCollator(NaFlexCollator):
    """NaFlex collator for samples of the form (path, image, target)"""

    def __init__(self, patch_size: int) -> None:
        super().__init__(1, patch_size)


@dataclass(frozen=True)
class NaFlexSequenceLengthSchedule:
    """Deterministically select a maximum sequence length for a global batch"""

    max_seq_lens: tuple[int, ...]
    seed: int

    def __post_init__(self) -> None:
        if len(self.max_seq_lens) == 0:
            raise ValueError("At least one maximum sequence length is required")
        if any(max_seq_len <= 0 for max_seq_len in self.max_seq_lens):
            raise ValueError(f"Maximum sequence lengths must be positive, got {self.max_seq_lens}")

    def select(self, epoch: int, global_batch_idx: int) -> int:
        generator = torch.Generator()
        generator.manual_seed(self.seed + epoch * EPOCH_SEED_STRIDE + global_batch_idx)
        schedule_idx = int(torch.randint(len(self.max_seq_lens), (), generator=generator).item())

        return self.max_seq_lens[schedule_idx]


class NaFlexBatchProcessor:
    """
    Select one maximum sequence length and transform all images in a batch with it

    The image batch size remains constant.
    Sequence-length selection is deterministic for an epoch and DataLoader batch index,
    and therefore stays aligned across distributed ranks that use the same worker count.

    Parameters
    ----------
    base_collator
        NaFlex collator applied after the images have been transformed.
    transforms
        Mapping from maximum sequence lengths to their corresponding image transforms.
    seed
        Seed used for sequence-length selection.
    """

    def __init__(
        self, base_collator: NaFlexCollator, transforms: dict[int, Callable[..., torch.Tensor]], seed: int
    ) -> None:
        self.base_collator = base_collator
        self.transforms = transforms
        self.schedule = NaFlexSequenceLengthSchedule(tuple(transforms), seed)
        self._epoch = mp.Value("q", 0)
        self._worker_epoch = -1
        self._worker_batch_idx = 0

    def set_epoch(self, epoch: int) -> None:
        self._epoch.value = epoch

    def _get_max_seq_len(self, epoch: int, worker_batch_idx: int) -> int:
        worker_info = torch.utils.data.get_worker_info()
        if worker_info is None:
            worker_id = 0
            num_workers = 1
        else:
            worker_id = worker_info.id
            num_workers = worker_info.num_workers

        # The WDS loader ensures that every configured worker is active on every distributed rank
        global_batch_idx = worker_batch_idx * num_workers + worker_id

        return self.schedule.select(epoch, global_batch_idx)

    def _next_max_seq_len(self) -> int:
        epoch = self._epoch.value
        if epoch != self._worker_epoch:
            self._worker_epoch = epoch
            self._worker_batch_idx = 0

        max_seq_len = self._get_max_seq_len(epoch, self._worker_batch_idx)
        self._worker_batch_idx += 1

        return max_seq_len

    def _transform_sample(self, sample: tuple[Any, ...], transform: Callable[..., torch.Tensor]) -> tuple[Any, ...]:
        fields = list(sample)
        fields[self.base_collator.input_offset] = transform(fields[self.base_collator.input_offset])
        return tuple(fields)

    def transform_batch(self, batch: Iterable[tuple[Any, ...]]) -> list[tuple[Any, ...]]:
        max_seq_len = self._next_max_seq_len()
        transform = self.transforms[max_seq_len]
        return [self._transform_sample(sample, transform) for sample in batch]

    def __call__(self, batch: list[tuple[Any, ...]]) -> tuple[Any, ...]:
        return self.base_collator(self.transform_batch(batch))

    def iter_batches(
        self, source: Iterable[tuple[Any, ...]], batch_size: int, drop_last: bool
    ) -> Iterator[tuple[Any, ...]]:
        """Batch a sample stream while transforming each decoded image immediately"""

        # Snapshot the epoch for this iterator so stale WDS prefetch from an old iterator cannot observe a new epoch
        epoch = self._epoch.value
        worker_batch_idx = 0
        source_iterator = iter(source)
        while True:
            try:
                sample = next(source_iterator)
            except StopIteration:
                break

            max_seq_len = self._get_max_seq_len(epoch, worker_batch_idx)
            worker_batch_idx += 1
            transform = self.transforms[max_seq_len]
            batch = [self._transform_sample(sample, transform)]
            for _ in range(batch_size - 1):
                try:
                    sample = next(source_iterator)
                except StopIteration:
                    break

                batch.append(self._transform_sample(sample, transform))

            if len(batch) == batch_size or (len(batch) > 0 and drop_last is False):
                yield self.base_collator(batch)
            if len(batch) < batch_size:
                break
