"""
Generated by gpt-5.4 high.
"""

import argparse
import json
import logging
import multiprocessing
import os
import queue
import signal
import time
from io import BytesIO
from pathlib import Path
from typing import Any
from typing import Optional

import torch
import webdataset as wds
from PIL import Image
from tqdm import tqdm

from birder.common import cli
from birder.common import fs_ops
from birder.common.lib import format_duration
from birder.conf import settings
from birder.model_registry import Task

logger = logging.getLogger(__name__)

# Few datasets like Objects365 have some very big files
Image.MAX_IMAGE_PIXELS = int(2048 * 2048 * 1024 // 4 // 3)
MAX_SIZE = 16_000


def _save_classes(pack_path: Path, class_list: list[str]) -> None:
    class_list_path = pack_path.joinpath("classes.txt")
    doc = "\n".join(class_list)

    logger.info(f"Saving class list at {class_list_path}")
    with open(class_list_path, "w", encoding="utf-8") as handle:
        handle.write(doc)


def _build_class_list(categories: list[dict[str, Any]]) -> list[str]:
    return [category["name"] for category in categories]


def _encode_image(
    path: str, file_format: str, size: Optional[int] = None
) -> tuple[bytes, tuple[int, int], tuple[int, int]]:
    image: Image.Image
    with Image.open(path) as image:
        input_size = image.size
        if file_format.lower() in ("jpeg", "jpg") and image.mode in ("RGBA", "P"):
            image = image.convert("RGB")

        if size is not None and size < min(image.size):
            if image.size[0] > image.size[1]:
                ratio = image.size[1] / size
            else:
                ratio = image.size[0] / size

            width = round(image.size[0] / ratio)
            height = round(image.size[1] / ratio)
            if max(width, height) > MAX_SIZE:
                if width > height:
                    ratio = width / MAX_SIZE
                else:
                    ratio = height / MAX_SIZE

                width = round(width / ratio)
                height = round(height / ratio)

            image = image.resize((width, height), Image.Resampling.BICUBIC)

        elif max(image.size) > MAX_SIZE:
            if image.size[0] > image.size[1]:
                ratio = image.size[0] / MAX_SIZE
            else:
                ratio = image.size[1] / MAX_SIZE

            width = round(image.size[0] / ratio)
            height = round(image.size[1] / ratio)
            image = image.resize((width, height), Image.Resampling.BICUBIC)

        sample_buffer = BytesIO()
        image.save(sample_buffer, format=file_format, quality=85)
        return (sample_buffer.getvalue(), input_size, image.size)


def _resize_target(target: dict[str, Any], input_size: tuple[int, int], output_size: tuple[int, int]) -> dict[str, Any]:
    if input_size == output_size:
        return target

    scale_x = output_size[0] / input_size[0]
    scale_y = output_size[1] / input_size[1]

    # Packed images can be resized, so the serialized target needs to match
    # the packed image dimensions and coordinates
    updated_target = dict(target)
    updated_target["width"] = output_size[0]
    updated_target["height"] = output_size[1]
    updated_target["boxes"] = [
        [x0 * scale_x, y0 * scale_y, x1 * scale_x, y1 * scale_y] for x0, y0, x1, y1 in target["boxes"]
    ]
    updated_target["area"] = [area * scale_x * scale_y for area in target["area"]]

    return updated_target


def _load_coco_targets(
    data_path: str | Path,
    coco_json_path: str | Path,
    drop_empty: bool = False,
    preserve_category_ids: bool = False,
    ignore_list: Optional[set[str]] = None,
) -> tuple[list[tuple[str, dict[str, Any]]], list[str], int]:
    with open(coco_json_path, "r", encoding="utf-8") as handle:
        doc = json.load(handle)

    images: list[dict[str, Any]] = doc["images"]
    annotations: list[dict[str, Any]] = doc["annotations"]
    categories: list[dict[str, Any]] = sorted(doc["categories"], key=lambda x: x["id"])
    if len(categories) == 0:
        raise ValueError("COCO json has no categories")

    class_list = _build_class_list(categories)
    max_category_id = max(category["id"] for category in categories)
    category_id_to_label = {category["id"]: idx + 1 for idx, category in enumerate(categories)}
    valid_category_ids = {category["id"] for category in categories}

    annotations_by_image_id: dict[int, list[dict[str, Any]]] = {}
    for annotation in annotations:
        annotations_by_image_id.setdefault(annotation["image_id"], []).append(annotation)

    base_path = Path(data_path)
    samples: list[tuple[str, dict[str, Any]]] = []
    for image in images:
        file_name = image["file_name"]
        if ignore_list is not None and file_name in ignore_list:
            continue

        image_id = image["id"]
        image_annotations = annotations_by_image_id.get(image_id, [])

        boxes = []
        labels = []
        areas = []
        iscrowd = []
        annotation_ids = []

        for annotation in image_annotations:
            category_id = annotation["category_id"]
            if category_id not in valid_category_ids:
                raise ValueError(f"Unknown category_id={category_id} for image_id={image_id}")

            x, y, w, h = annotation["bbox"]
            boxes.append([x, y, x + w, y + h])
            if preserve_category_ids is True:
                labels.append(category_id)
            else:
                labels.append(category_id_to_label[category_id])
            areas.append(annotation.get("area", w * h))
            iscrowd.append(annotation.get("iscrowd", 0))
            annotation_ids.append(annotation["id"])

        if drop_empty is True and len(boxes) == 0:
            continue

        samples.append(
            (
                str(base_path.joinpath(file_name)),
                {
                    "image_id": image_id,
                    "file_name": file_name,
                    "width": image["width"],
                    "height": image["height"],
                    "boxes": boxes,
                    "labels": labels,
                    "area": areas,
                    "iscrowd": iscrowd,
                    "annotation_ids": annotation_ids,
                    "boxes_format": "xyxy",
                },
            )
        )

    return (samples, class_list, max_category_id)


def read_worker(q_in: Any, q_out: Any, error_event: Any, size: Optional[int], file_format: str) -> None:
    while True:
        deq: Optional[tuple[int, str, dict[str, Any]]] = q_in.get()
        if deq is None:
            break

        try:
            idx, path, target = deq
            if size is None:
                suffix = Path(path).suffix[1:]
                if file_format != suffix:
                    sample, input_size, output_size = _encode_image(path, file_format)
                    target = _resize_target(target, input_size, output_size)
                else:
                    with open(path, "rb") as stream:
                        sample = stream.read()

            else:
                sample, input_size, output_size = _encode_image(path, file_format, size)
                target = _resize_target(target, input_size, output_size)

        except Exception:
            error_event.set()
            raise

        if error_event.is_set() is True:
            break

        q_out.put(
            (idx, sample, file_format, json.dumps(target, separators=(",", ":")).encode("utf-8")),
            block=True,
            timeout=None,
        )


def wds_write_worker(q_out: Any, error_event: Any, pack_path: Path, total: int, args: argparse.Namespace) -> None:
    try:
        info_path = pack_path.joinpath("_info.json")
        if args.append is True:
            info = fs_ops.read_wds_info(info_path)
            if args.split in info["splits"]:
                raise ValueError(f"split {args.split} already exist")

        else:
            info = None
    except Exception:
        error_event.set()
        # Re-raise to terminate this process
        raise

    filenames: list[str] = []
    shard_lengths: list[int] = []
    path_pattern = str(pack_path.joinpath(f"{args.suffix}-{args.split}-%06d.tar"))
    sink = wds.ShardWriter(path_pattern, maxsize=args.max_size, verbose=0)

    def wds_info(fname: str) -> None:
        filenames.append(Path(fname).name)
        shard_lengths.append(sink.count)

    sink.post = wds_info

    start_number = args.start_number
    count = 0
    buf = {}
    more = True
    try:
        with tqdm(total=total, initial=0, unit="images", unit_scale=True, leave=False) as progress:
            while more:
                deq: Optional[tuple[int, bytes, str, bytes]] = q_out.get()
                if deq is not None:
                    idx, sample, suffix, target = deq
                    buf[idx] = (sample, suffix, target)

                else:
                    more = False

                # Ensures ordered write
                while count in buf:
                    sample, suffix, target = buf[count]
                    del buf[count]

                    sink.write(
                        {
                            "__key__": f"sample{count + start_number:09d}",
                            suffix: sample,
                            "json": target,
                        }
                    )
                    count += 1

                    # Update progress bar
                    progress.update(n=1)

    except Exception:
        error_event.set()
        raise

    sink.close()

    split_info = {
        "name": args.split,
        "filenames": filenames,
        "shard_lengths": shard_lengths,
        "num_samples": sum(shard_lengths),
    }

    if info is None:
        info = {
            "name": args.suffix,
            "task": Task.OBJECT_DETECTION,
            "splits": {args.split: split_info},
        }
    else:
        info["splits"][args.split] = split_info

    with open(pack_path.joinpath("_info.json"), "w", encoding="utf-8") as handle:
        logger.debug("Saving _info.json")
        json.dump(info, handle, indent=2)


def pack(args: argparse.Namespace, pack_path: Path) -> None:
    ignore_list: Optional[set[str]] = None
    if args.ignore_file is not None:
        with open(args.ignore_file, "r", encoding="utf-8") as handle:
            ignore_list = {line for line in handle.read().splitlines() if line != ""}

    if args.class_file is not None:
        samples, _class_list, max_category_id = _load_coco_targets(
            args.data_path,
            args.coco_json_path,
            drop_empty=args.drop_empty,
            preserve_category_ids=True,
            ignore_list=ignore_list,
        )
        class_file_list = list(fs_ops.read_class_file(args.class_file).keys())
        if len(class_file_list) < max_category_id:
            raise ValueError("--class-file length must be at least the maximum category id in the COCO categories")

        class_list = class_file_list
    else:
        samples, class_list, _ = _load_coco_targets(
            args.data_path, args.coco_json_path, drop_empty=args.drop_empty, ignore_list=ignore_list
        )

    if ignore_list is not None:
        logger.info(f"Ignoring {len(ignore_list):,} file names from {args.ignore_file}")

    if args.append is True:
        existing_class_list = list(fs_ops.read_class_file(pack_path.joinpath("classes.txt")).keys())
        if existing_class_list != class_list:
            raise ValueError("classes.txt in target path does not match the COCO categories being appended")

    else:
        _save_classes(pack_path, class_list)

    if args.shuffle is True:
        indices = torch.randperm(len(samples)).tolist()
    else:
        indices = list(range(len(samples)))

    if args.jobs == -1:
        args.jobs = multiprocessing.cpu_count()

    logger.info(f"Packing {len(samples):,} samples")
    logger.info(f"Running {args.jobs} read processes and 1 write process")

    q_in = []  # type: ignore[var-annotated]
    for _ in range(args.jobs):
        q_in.append(multiprocessing.Queue(1024))

    q_out = multiprocessing.Queue(1024)  # type: ignore[var-annotated]
    error_event = multiprocessing.Event()

    read_processes: list[multiprocessing.Process] = []
    for idx in range(args.jobs):
        read_processes.append(
            multiprocessing.Process(target=read_worker, args=(q_in[idx], q_out, error_event, args.size, args.format))
        )

    for p in read_processes:
        p.start()

    write_process = multiprocessing.Process(
        target=wds_write_worker, args=(q_out, error_event, pack_path, len(samples), args)
    )
    write_process.start()

    # Flag to prevent signal handler re-entry
    cleanup_in_progress = False

    def cleanup_processes() -> None:
        nonlocal cleanup_in_progress
        if cleanup_in_progress is True:
            return

        cleanup_in_progress = True

        # Cancel queue join threads to prevent blocking during cleanup
        for q in q_in:
            q.cancel_join_thread()

        q_out.cancel_join_thread()

        # Terminate child processes
        for p in read_processes:
            if p.is_alive():
                p.terminate()

        if write_process.is_alive():
            write_process.terminate()

        # Wait briefly for termination
        for p in read_processes:
            p.join(timeout=1)

        write_process.join(timeout=1)

    def signal_handler(signum, _frame) -> None:  # type: ignore
        logger.info(f"Received signal: {signum} at {multiprocessing.current_process().name}, aborting...")
        error_event.set()
        cleanup_processes()
        raise SystemExit(1)

    signal.signal(signal.SIGINT, signal_handler)

    try:
        tic = time.time()
        for idx, sample_idx in enumerate(indices):
            if idx % 1000 == 0:
                if error_event.is_set() is True:
                    cleanup_processes()
                    raise RuntimeError()

            path, target = samples[sample_idx]

            while True:
                try:
                    q_in[idx % len(q_in)].put((idx, path, target), block=True, timeout=1)
                    break
                except queue.Full:
                    if error_event.is_set() is True:
                        cleanup_processes()
                        raise RuntimeError()  # pylint: disable=raise-missing-from

        for q in q_in:
            q.put(None, block=True, timeout=None)

        for p in read_processes:
            while True:
                p.join(timeout=2)
                if p.is_alive() is False:
                    break

                if error_event.is_set() is True:
                    cleanup_processes()
                    raise RuntimeError()

        q_out.put(None, block=True, timeout=None)
        while True:
            write_process.join(timeout=2)
            if write_process.is_alive() is False:
                break

            if error_event.is_set() is True:
                cleanup_processes()
                raise RuntimeError()

        if error_event.is_set() is True:
            cleanup_processes()
            raise RuntimeError()

        wds_path, num_shards = fs_ops.wds_braces_from_path(pack_path, prefix=f"{args.suffix}-{args.split}")
        logger.info(f"Packed {len(samples):,} samples into {num_shards} shards at {wds_path}")

        toc = time.time()
        rate = len(samples) / (toc - tic)
        logger.info(f"{format_duration(toc-tic)} to pack {len(samples):,} samples ({rate:.2f} samples/sec)")

    except Exception:
        cleanup_processes()
        raise


def set_parser(subparsers: Any) -> None:
    subparser = subparsers.add_parser(
        "pack-detection",
        allow_abbrev=False,
        help="pack a COCO detection dataset into webdataset",
        description="pack a COCO detection dataset into webdataset",
        epilog=(
            "Usage examples:\n"
            "python -m birder.tools pack-detection -j 4 --drop-empty --size 1024 --split validation "
            "--class-file public_datasets_metadata/coco-classes.txt --data-path ~/Datasets/cocodataset/val2017 "
            "--coco-json-path ~/Datasets/cocodataset/annotations/instances_val2017.json\n"
            "python -m birder.tools pack-detection -j 4 --shuffle --max-size 80 "
            "--target-path data/coco_detection_wds --suffix coco "
            "--data-path ~/Datasets/cocodataset/val2017 "
            "--coco-json-path ~/Datasets/cocodataset/annotations/instances_val2017.json\n"
            "python -m birder.tools pack-detection --target-path /mnt/data/Objects365-2020-wds "
            "--data-path /mnt/data/Objects365-2020/train --coco-json-path "
            "/mnt/data/Objects365-2020/train/zhiyuan_objv2_train.json -j 24 --shuffle --drop-empty "
            "--ignore-file public_datasets_metadata/objects365_ignore.txt --size 896\n"
            "python -m birder.tools pack-detection --target-path /mnt/data/Objects365-2020-wds "
            "--data-path /mnt/data/Objects365-2020/val --coco-json-path "
            "/mnt/data/Objects365-2020/val/zhiyuan_objv2_val.json -j 24 --ignore-file "
            "public_datasets_metadata/objects365_ignore.txt --size 896 --split validation --append\n"
        ),
        formatter_class=cli.ArgumentHelpFormatter,
    )
    subparser.add_argument("--target-path", type=str, help="where to write the packed dataset")
    subparser.add_argument(
        "--data-path", type=str, default=str(settings.DETECTION_DATA_PATH), help="image directory path"
    )
    subparser.add_argument(
        "--coco-json-path",
        type=str,
        default=f"{settings.TRAINING_DETECTION_ANNOTATIONS_PATH}_coco.json",
        help="training COCO json path",
    )
    subparser.add_argument("--max-size", type=int, default=400, help="maximum size of each shard in MB")
    subparser.add_argument(
        "-j",
        "--jobs",
        type=int,
        default=1,
        help="performs calculation on multiple cores, set -1 to run on all cores",
    )
    subparser.add_argument("--shuffle", default=False, action="store_true", help="shuffle the dataset during packing")
    subparser.add_argument("--drop-empty", default=False, action="store_true", help="skip images without annotations")
    subparser.add_argument("--ignore-file", type=str, help="ignore list file, list of image file names to skip")
    subparser.add_argument("--size", type=int, help="resize image short dimension to size if bigger")
    subparser.add_argument("--format", type=str, choices=["webp", "png", "jpeg"], default="webp", help="file format")
    subparser.add_argument("--class-file", type=str, help="class list file")
    subparser.add_argument("--start-number", type=int, default=0, help="starting number for output file naming")
    subparser.add_argument("--suffix", type=str, default=settings.PACK_PATH_SUFFIX, help="directory suffix")
    subparser.add_argument("--split", type=str, default="training", help="dataset split used for _info.json")
    subparser.add_argument("--append", default=False, action="store_true", help="add split to existing wds")
    subparser.set_defaults(func=main)


def main(args: argparse.Namespace) -> None:
    args.data_path = os.path.expanduser(args.data_path)
    args.coco_json_path = os.path.expanduser(args.coco_json_path)
    if args.ignore_file is not None:
        args.ignore_file = os.path.expanduser(args.ignore_file)
    if args.target_path is not None:
        args.target_path = os.path.expanduser(args.target_path)

    args.max_size = args.max_size * 1e6
    if args.target_path is None:
        pack_path = Path(f"{Path(args.data_path)}_{args.suffix}")
    else:
        pack_path = Path(args.target_path)

    if pack_path.exists() is False:
        logger.info(f"Creating {pack_path} directory...")
        pack_path.mkdir(parents=True)

    elif args.append is False:
        logger.warning("Directory already exists... aborting")
        raise SystemExit(1)

    pack(args, pack_path)
