"""
AIM v1

Paper "Scalable Pre-training of Large Autoregressive Image Models",
https://arxiv.org/abs/2401.08541

Generated by gpt-5.5 xhigh.
"""

import math
from typing import Any
from typing import Optional

import torch
from torch import nn

from birder.layers.moe import MoETrainingOutputType
from birder.model_registry import registry
from birder.net.base import PreTrainEncoder
from birder.net.base import pos_embedding_sin_cos_2d
from birder.net.mim.base import MIMBaseNet


class MLPBlock(nn.Module):
    def __init__(self, dim: int) -> None:
        super().__init__()

        self.norm = nn.LayerNorm(dim, eps=1e-6)
        self.mlp = nn.Sequential(
            nn.Linear(dim, dim * 4, bias=False),
            nn.GELU(),
            nn.Linear(dim * 4, dim, bias=False),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x + self.mlp(self.norm(x))


class AIM_v1(MIMBaseNet):
    default_size = (224, 224)
    default_mask_ratio = 0.0  # Not used
    auto_register = False

    def __init__(
        self,
        encoder: PreTrainEncoder,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
        mask_ratio: Optional[float] = None,
        min_mask_size: int = 1,
    ) -> None:
        super().__init__(encoder, config=config, size=size, mask_ratio=mask_ratio, min_mask_size=min_mask_size)
        assert self.config is not None, "must set config"

        self.patch_size = self.encoder.stem_stride
        encoder_dim = self.encoder.feature_dim
        decoder_embed_dim: int = self.config["decoder_embed_dim"]
        decoder_depth: int = self.config["decoder_depth"]

        self.decoder_embed = nn.Linear(encoder_dim, decoder_embed_dim)

        # Fixed sin-cos embedding
        pos_embedding = pos_embedding_sin_cos_2d(
            h=self.size[0] // self.patch_size,
            w=self.size[1] // self.patch_size,
            dim=decoder_embed_dim,
            num_special_tokens=0,
            include_frequency_endpoint=False,
        )
        self.decoder_pos_embed = nn.Buffer(pos_embedding.unsqueeze(0))

        layers = []
        for _ in range(decoder_depth):
            layers.append(MLPBlock(decoder_embed_dim))

        self.decoder_blocks = nn.Sequential(*layers)
        self.decoder_norm = nn.LayerNorm(decoder_embed_dim, eps=1e-6)
        self.decoder_pred = nn.Linear(decoder_embed_dim, self.patch_size**2 * self.input_channels)

        # Weight initialization
        nn.init.xavier_uniform_(self.decoder_embed.weight)
        nn.init.zeros_(self.decoder_embed.bias)

        for m in self.decoder_blocks.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

            elif isinstance(m, nn.LayerNorm):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)

        nn.init.ones_(self.decoder_norm.weight)
        nn.init.zeros_(self.decoder_norm.bias)

        scale = 1.0 / (1 + decoder_depth)
        std = math.sqrt(scale / self.decoder_pred.in_features)
        nn.init.trunc_normal_(self.decoder_pred.weight, std=std)
        nn.init.zeros_(self.decoder_pred.bias)

    def patchify(self, imgs: torch.Tensor) -> torch.Tensor:
        """
        imgs: (N, C, H, W)
        x: (N, L, patch_size**2 * C)
        """

        p = self.patch_size
        c = self.input_channels
        assert imgs.shape[2] % p == 0 and imgs.shape[3] % p == 0

        h = imgs.shape[2] // p
        w = imgs.shape[3] // p
        x = imgs.reshape(shape=(imgs.shape[0], c, h, p, w, p))
        x = torch.einsum("nchpwq->nhwpqc", x)
        x = x.reshape(shape=(imgs.shape[0], h * w, p**2 * c))

        return x

    def unpatchify(self, x: torch.Tensor) -> torch.Tensor:
        """
        x: (N, L, patch_size**2 * C)
        imgs: (N, C, H, W)
        """

        p = self.patch_size
        c = self.input_channels
        h = self.size[0] // p
        w = self.size[1] // p
        assert h * w == x.shape[1]

        x = x.reshape(shape=(x.size(0), h, w, p, p, c))
        x = torch.einsum("nhwpqc->nchpwq", x)
        imgs = x.reshape(shape=(x.size(0), c, h * p, w * p))

        return imgs

    def _sample_prefix_lengths(self, batch_size: int, num_patches: int, device: torch.device) -> torch.Tensor:
        return torch.randint(1, num_patches, (batch_size,), dtype=torch.long, device=device)

    def _make_prefix_mask(self, prefix_lengths: torch.Tensor, num_patches: int) -> torch.Tensor:
        patch_idx = torch.arange(num_patches, device=prefix_lengths.device).unsqueeze(0)
        return patch_idx >= prefix_lengths.unsqueeze(1)

    def _make_attention_mask(self, prefix_mask: torch.Tensor, num_special_tokens: int) -> torch.Tensor:
        # This mask constrains attention only, the encoder's other token-mixing operations must preserve causality too.
        # For sparse MoE, use dropless token-choice or V-MoE with top_k=1, expert-choice routing is not causal.
        B, K = prefix_mask.size()
        device = prefix_mask.device

        prefix_keys = ~prefix_mask
        causal_mask = torch.ones(K, K, dtype=torch.bool, device=device).tril(diagonal=0)
        patch_attn_mask = causal_mask.unsqueeze(0) | prefix_keys.unsqueeze(1)

        if num_special_tokens == 0:
            return patch_attn_mask.unsqueeze(1)

        seq_len = num_special_tokens + K
        attn_mask = torch.zeros(B, seq_len, seq_len, dtype=torch.bool, device=device)
        attn_mask[:, :num_special_tokens, :num_special_tokens] = True
        attn_mask[:, :num_special_tokens, num_special_tokens:] = prefix_keys.unsqueeze(1)
        attn_mask[:, num_special_tokens:, :num_special_tokens] = True
        attn_mask[:, num_special_tokens:, num_special_tokens:] = patch_attn_mask

        return attn_mask.unsqueeze(1)

    def forward_loss(self, x: torch.Tensor, pred: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        target = self.patchify(x)
        mean = target.mean(dim=-1, keepdim=True)
        var = target.var(dim=-1, keepdim=True)
        target = (target - mean) / (var + 1.0e-6) ** 0.5

        loss = (pred[:, :-1] - target[:, 1:]) ** 2
        loss = loss.mean(dim=-1)
        mask = mask[:, 1:].type_as(loss)
        loss = (loss * mask).sum() / mask.sum()

        return loss

    def forward(self, x: torch.Tensor, *, return_moe_training_output: bool = False) -> dict[str, Any]:
        h = self.size[0] // self.patch_size
        w = self.size[1] // self.patch_size
        num_patches = h * w

        prefix_lengths = self._sample_prefix_lengths(x.size(0), num_patches, x.device)
        prefix_mask = self._make_prefix_mask(prefix_lengths, num_patches)
        attn_mask = self._make_attention_mask(prefix_mask, getattr(self.encoder, "num_special_tokens", 0))
        moe_training_output: Optional[MoETrainingOutputType] = None
        if return_moe_training_output is True:
            features, moe_training_output = self.encoder.forward_features(
                x, attn_mask=attn_mask, return_moe_training_output=True  # type: ignore[call-arg]
            )
        else:
            features = self.encoder.forward_features(x, attn_mask=attn_mask)  # type: ignore[call-arg]

        features = self.encoder.flatten_features(features, include_special_tokens=False)
        pred = self.decoder_embed(features)
        pred = pred + self.decoder_pos_embed
        pred = self.decoder_blocks(pred)
        pred = self.decoder_norm(pred)
        pred = self.decoder_pred(pred)
        loss = self.forward_loss(x, pred, prefix_mask)

        result = {"loss": loss, "pred": pred, "mask": prefix_mask, "prefix_lengths": prefix_lengths}
        if moe_training_output is not None:
            result["moe_training_output"] = moe_training_output

        return result


registry.register_model_config("aim_v1", AIM_v1, config={"decoder_embed_dim": 2048, "decoder_depth": 12})
registry.register_model_config("aim_v1_dec512d4", AIM_v1, config={"decoder_embed_dim": 512, "decoder_depth": 4})
registry.register_model_config("aim_v1_dec512d8", AIM_v1, config={"decoder_embed_dim": 512, "decoder_depth": 8})
registry.register_model_config("aim_v1_dec512d12", AIM_v1, config={"decoder_embed_dim": 512, "decoder_depth": 12})
registry.register_model_config("aim_v1_dec1024d8", AIM_v1, config={"decoder_embed_dim": 1024, "decoder_depth": 8})
registry.register_model_config("aim_v1_dec1024d12", AIM_v1, config={"decoder_embed_dim": 1024, "decoder_depth": 12})
