"""
MaskFeat, adapted from
https://github.com/facebookresearch/SlowFast/blob/main/slowfast/models/masked.py

Paper "Masked Feature Prediction for Self-Supervised Visual Pre-Training",
https://arxiv.org/abs/2112.09133

Changes from original:
* Support rectangular feature grids and coarse masking through min_mask_size

Generated by gpt-5.6-sol max.
"""

# Reference license: Apache-2.0

import math
from typing import Any
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn

from birder.common.masking import BlockMasking
from birder.net.base import MaskedTokenRetentionMixin
from birder.net.base import PreTrainEncoder
from birder.net.mim.base import MIMBaseNet


class HOGTarget(nn.Module):
    def __init__(self, input_channels: int, num_bins: int, cell_size: int) -> None:
        super().__init__()
        self.input_channels = input_channels
        self.num_bins = num_bins
        self.cell_size = cell_size

        weight_x = torch.tensor([[1.0, 0.0, -1.0], [2.0, 0.0, -2.0], [1.0, 0.0, -1.0]])
        weight_x = weight_x.reshape(1, 1, 3, 3).repeat(self.input_channels, 1, 1, 1)
        self.weight_x = nn.Buffer(weight_x, persistent=False)
        self.weight_y = nn.Buffer(weight_x.transpose(2, 3), persistent=False)

    @torch.no_grad()  # type: ignore[untyped-decorator]
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        x
            Images of shape (B, C, H, W).

        Returns
        -------
        Per-channel HOG histograms of shape (B, C, num_bins, H // cell_size, W // cell_size).
        """

        # HOG target construction is intentionally kept in float32, including during mixed-precision training
        with torch.amp.autocast(x.device.type, enabled=False):
            x = F.pad(x.float(), pad=(1, 1, 1, 1), mode="reflect")
            grad_x = F.conv2d(  # pylint: disable=not-callable
                x, self.weight_x.float(), bias=None, stride=1, padding=0, groups=self.input_channels
            )
            grad_y = F.conv2d(  # pylint: disable=not-callable
                x, self.weight_y.float(), bias=None, stride=1, padding=0, groups=self.input_channels
            )

            magnitude = torch.stack((grad_x, grad_y), dim=-1).norm(dim=-1)
            phase = torch.atan2(grad_x, grad_y)
            phase = phase / math.pi * self.num_bins

            batch_size, channels, height, width = magnitude.size()
            histogram = torch.zeros(
                (batch_size, channels, self.num_bins, height, width), dtype=torch.float32, device=x.device
            )
            bin_indices = phase.floor().long().remainder(self.num_bins).unsqueeze(2)
            histogram.scatter_add_(2, bin_indices, magnitude.unsqueeze(2))

            histogram = histogram.unfold(3, self.cell_size, self.cell_size)
            histogram = histogram.unfold(4, self.cell_size, self.cell_size)
            histogram = histogram.sum(dim=(-1, -2))
            histogram = F.normalize(histogram, p=2, dim=2)

        return histogram


class MaskFeat(MIMBaseNet):
    default_size = (224, 224)
    default_mask_ratio = 0.4

    def __init__(
        self,
        encoder: PreTrainEncoder,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
        mask_ratio: Optional[float] = None,
        min_mask_size: int = 1,
    ) -> None:
        super().__init__(encoder, config=config, size=size, mask_ratio=mask_ratio, min_mask_size=min_mask_size)
        assert self.config is None, "config not supported"
        assert isinstance(self.encoder, MaskedTokenRetentionMixin)

        self.num_bins = 9
        self.cell_size = 8
        self.patch_size = self.encoder.max_stride
        self.grid_size = (self.size[0] // self.patch_size, self.size[1] // self.patch_size)

        assert (
            self.patch_size % self.cell_size == 0
        ), f"encoder stride {self.patch_size} must be divisible by HOG cell size {self.cell_size}"
        assert (
            self.size[0] % self.patch_size == 0 and self.size[1] % self.patch_size == 0
        ), f"image size {self.size} must be divisible by encoder stride {self.patch_size}"
        assert (
            self.grid_size[0] % self.min_mask_size == 0 and self.grid_size[1] % self.min_mask_size == 0
        ), f"feature grid {self.grid_size} must be divisible by min_mask_size {self.min_mask_size}"

        mask_grid_size = (
            self.grid_size[0] // self.min_mask_size,
            self.grid_size[1] // self.min_mask_size,
        )
        num_masking_patches = round(math.prod(mask_grid_size) * self.mask_ratio)
        self._mask_generator = BlockMasking(
            mask_grid_size,
            min_num_patches=max(1, num_masking_patches // 5),
            max_num_patches=num_masking_patches,
            min_aspect=0.3,
            max_aspect=1 / 0.3,
            min_masking_patches=num_masking_patches,
        )

        cells_per_token = self.patch_size // self.cell_size
        target_dim = self.input_channels * self.num_bins * cells_per_token**2
        self.hog_target = HOGTarget(
            input_channels=self.input_channels, num_bins=self.num_bins, cell_size=self.cell_size
        )
        self.mask_token = nn.Parameter(torch.zeros(1, 1, 1, self.encoder.stem_width))
        self.predictor = nn.Conv2d(
            in_channels=self.encoder.feature_dim,
            out_channels=target_dim,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
        )

        # Weights initialization
        nn.init.trunc_normal_(self.mask_token, mean=0.0, std=0.02)
        nn.init.trunc_normal_(self.predictor.weight, mean=0.0, std=0.02)
        nn.init.zeros_(self.predictor.bias)

    @torch.compiler.disable()  # type: ignore[untyped-decorator]
    def _generate_mask(self, batch_size: int, device: torch.device) -> torch.Tensor:
        mask = self._mask_generator(batch_size)
        if self.min_mask_size > 1:
            mask = mask.reshape(
                batch_size,
                self.grid_size[0] // self.min_mask_size,
                self.grid_size[1] // self.min_mask_size,
            )
            mask = mask.repeat_interleave(self.min_mask_size, dim=1)
            mask = mask.repeat_interleave(self.min_mask_size, dim=2)
            mask = mask.reshape(batch_size, -1)

        return mask.to(device=device)

    def _patchify_hog(self, hog: torch.Tensor) -> torch.Tensor:
        batch_size, channels, num_bins, _, _ = hog.size()
        cells_per_token = self.patch_size // self.cell_size
        hog = hog.reshape(
            batch_size,
            channels,
            num_bins,
            self.grid_size[0],
            cells_per_token,
            self.grid_size[1],
            cells_per_token,
        )

        # Layout: channel/bin features first, followed by the cells within each encoder token
        hog = hog.permute(0, 3, 5, 1, 2, 4, 6)

        return hog.reshape(batch_size, math.prod(self.grid_size), -1)

    def get_hog_targets(self, x: torch.Tensor) -> torch.Tensor:
        return self._patchify_hog(self.hog_target(x))

    def forward_loss(self, pred: torch.Tensor, target: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        loss = (pred.float() - target).square().mean(dim=-1)
        mask = mask.to(dtype=loss.dtype)

        return (loss * mask).sum() / mask.sum().clamp_min(1.0)

    def forward(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        mask = self._generate_mask(x.size(0), x.device)
        target = self.get_hog_targets(x)
        latent = self.encoder.masked_encoding_retention(x, mask, mask_token=self.mask_token, return_keys="features")
        pred = self.predictor(latent["features"])
        pred = pred.flatten(2).transpose(1, 2)
        loss = self.forward_loss(pred, target, mask)

        result = {"loss": loss, "pred": pred, "mask": mask}
        if "auxiliary_losses" in latent:
            result["moe_auxiliary_loss"] = latent["auxiliary_losses"]["auxiliary_loss"]

        return result
