from django.utils.translation import gettext_lazy as _

SYNSET = [
    _("Alpine swift"),
    _("Arabian babbler"),
    _("Asian desert warbler"),
    _("Barn owl"),
    _("Barn swallow"),
    _("Bearded reedling"),
    _("Black francolin"),
    _("Black kite"),
    _("Black stork"),
    _("Black-crowned night heron"),
    _("Black-headed gull"),
    _("Black-shouldered kite"),
    _("Black-winged stilt"),
    _("Blackstart"),
    _("Bluethroat"),
    _("Cattle egret"),
    _("Common blackbird"),
    _("Common chaffinch"),
    _("Common crane"),
    _("Common kestrel"),
    _("Common kingfisher"),
    _("Common moorhen"),
    _("Common myna"),
    _("Common quail"),
    _("Common rock thrush"),
    _("Common starling"),
    _("Common tern"),
    _("Cream-colored courser"),
    _("Crested lark"),
    _("Egyptian goose"),
    _("Egyptian vulture"),
    _("Eurasian blackcap"),
    _("Eurasian collared dove"),
    _("Eurasian coot"),
    _("Eurasian curlew"),
    _("Eurasian golden oriole"),
    _("Eurasian hoopoe"),
    _("Eurasian jay"),
    _("Eurasian oystercatcher"),
    _("Eurasian scops owl"),
    _("Eurasian spoonbill"),
    _("Eurasian stone-curlew"),
    _("Eurasian teal"),
    _("Eurasian wryneck"),
    _("European bee-eater"),
    _("European goldfinch"),
    _("European nightjar"),
    _("European robin"),
    _("European roller"),
    _("European stonechat"),
    _("Fan-tailed raven"),
    _("Fieldfare"),
    _("Glossy ibis"),
    _("Great cormorant"),
    _("Great crested grebe"),
    _("Great egret"),
    _("Great spotted cuckoo"),
    _("Great tit"),
    _("Great white pelican"),
    _("Greater flamingo"),
    _("Green bee-eater"),
    _("Grey heron"),
    _("Griffon vulture"),
    _("Hawfinch"),
    _("Hooded crow"),
    _("House sparrow"),
    _("Kentish plover"),
    _("Lappet-faced vulture"),
    _("Laughing dove"),
    _("Little egret"),
    _("Little owl"),
    _("Long-eared owl"),
    _("Mallard"),
    _("Masked shrike"),
    _("Mute swan"),
    _("Northern gannet"),
    _("Northern shoveler"),
    _("Osprey"),
    _("Palestine sunbird"),
    _("Peregrine falcon"),
    _("Pied avocet"),
    _("Pied kingfisher"),
    _("Pin-tailed sandgrouse"),
    _("Pygmy cormorant"),
    _("Red-footed falcon"),
    _("Rock pigeon"),
    _("Rose-ringed parakeet"),
    _("Rosy starling"),
    _("Short-toed snake eagle"),
    _("Sinai rosefinch"),
    _("Spotted flycatcher"),
    _("Spur-winged lapwing"),
    _("Syrian woodpecker"),
    _("Tristrams starling"),
    _("Trumpeter finch"),
    _("Wallcreeper"),
    _("Whinchat"),
    _("White stork"),
    _("White wagtail"),
    _("White-spectacled bulbul"),
    _("White-tailed eagle"),
    _("White-throated kingfisher"),
    _("Yelkouan shearwater"),
]
