"""
RF-DETR, adapted from
https://github.com/roboflow/rf-detr

Paper "RF-DETR: Neural Architecture Search for Real-Time Detection Transformers",
https://arxiv.org/abs/2511.09554

Changes from original:
* Added support for hierarchical feature map backbones

Generated by gpt-5.4 high.
"""

# Reference license: Apache-2.0

import copy
from collections.abc import Callable
from typing import Any
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn

from birder.layers import LayerNorm2d
from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.detection.deformable_detr import HungarianMatcher
from birder.net.detection.lw_detr import LW_DETR
from birder.net.detection.lw_detr import LW_DETRDecoder
from birder.ops.soft_nms import SoftNMS


class ConvX(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel: tuple[int, int],
        stride: tuple[int, int],
        act_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        padding = (kernel[0] // 2, kernel[1] // 2)
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=kernel, stride=stride, padding=padding, bias=False)
        self.norm = LayerNorm2d(out_channels, eps=1e-6)
        self.act = act_layer(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act(self.norm(self.conv(x.contiguous())))


class Bottleneck(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        shortcut: bool,
        kernels: tuple[tuple[int, int], tuple[int, int]],
        expansion: float,
        act_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        hidden_channels = int(out_channels * expansion)
        self.conv1 = ConvX(in_channels, hidden_channels, kernel=kernels[0], stride=(1, 1), act_layer=act_layer)
        self.conv2 = ConvX(hidden_channels, out_channels, kernel=kernels[1], stride=(1, 1), act_layer=act_layer)
        self.add = shortcut is True and in_channels == out_channels

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = self.conv2(self.conv1(x))
        if self.add is True:
            return x + out

        return out


class C2f(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        num_blocks: int,
        shortcut: bool,
        expansion: float,
        act_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        hidden_channels = int(out_channels * expansion)
        self.hidden_channels = hidden_channels
        self.conv1 = ConvX(in_channels, 2 * hidden_channels, kernel=(1, 1), stride=(1, 1), act_layer=act_layer)
        self.blocks = nn.ModuleList(
            [
                Bottleneck(
                    hidden_channels,
                    hidden_channels,
                    shortcut=shortcut,
                    kernels=((3, 3), (3, 3)),
                    expansion=1.0,
                    act_layer=act_layer,
                )
                for _ in range(num_blocks)
            ]
        )
        self.conv2 = ConvX(
            (2 + num_blocks) * hidden_channels, out_channels, kernel=(1, 1), stride=(1, 1), act_layer=act_layer
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y = list(self.conv1(x).split((self.hidden_channels, self.hidden_channels), dim=1))
        y.extend(block(y[-1]) for block in self.blocks)
        return self.conv2(torch.concat(y, dim=1))


class ProjectorStage(nn.Module):
    def __init__(self, in_channels: list[int], out_channels: int, scale: float, num_blocks: int) -> None:
        super().__init__()
        self.scale = float(scale)
        samplers: list[nn.Module] = []
        fused_channels = 0
        for in_dim in in_channels:
            layers: list[nn.Module] = []
            out_dim = in_dim
            if scale == 4.0:
                layers.extend(
                    [
                        nn.ConvTranspose2d(in_dim, in_dim // 2, kernel_size=(2, 2), stride=(2, 2), padding=(0, 0)),
                        LayerNorm2d(in_dim // 2, eps=1e-6),
                        nn.GELU(),
                        nn.ConvTranspose2d(in_dim // 2, in_dim // 4, kernel_size=(2, 2), stride=(2, 2), padding=(0, 0)),
                    ]
                )
                out_dim = in_dim // 4
            elif scale == 2.0:
                layers.append(
                    nn.ConvTranspose2d(in_dim, in_dim // 2, kernel_size=(2, 2), stride=(2, 2), padding=(0, 0))
                )
                out_dim = in_dim // 2
            elif scale == 1.0:
                layers.append(nn.Identity())
                out_dim = in_dim
            elif scale == 0.5:
                layers.append(ConvX(in_dim, in_dim, kernel=(3, 3), stride=(2, 2), act_layer=nn.ReLU))
                out_dim = in_dim
            else:
                raise ValueError(f"Unsupported scale_factor: {scale}")

            samplers.append(nn.Sequential(*layers))
            fused_channels += out_dim

        self.samplers = nn.ModuleList(samplers)
        self.fuser = nn.Sequential(
            C2f(fused_channels, out_channels, num_blocks=num_blocks, shortcut=False, expansion=0.5, act_layer=nn.SiLU),
            LayerNorm2d(out_channels, eps=1e-6),
        )

    def forward(self, features: list[torch.Tensor], ref_h: int, ref_w: int) -> torch.Tensor:
        target_h = int(ref_h * self.scale)
        target_w = int(ref_w * self.scale)
        fused_feats: list[torch.Tensor] = []
        for level_idx, sampler in enumerate(self.samplers):
            sampled = sampler(features[level_idx])
            if sampled.shape[-2:] != (target_h, target_w):
                sampled = F.interpolate(sampled, size=(target_h, target_w), mode="nearest")

            fused_feats.append(sampled)

        fused = fused_feats[0] if len(fused_feats) == 1 else torch.concat(fused_feats, dim=1)
        return self.fuser(fused)


class MultiScaleProjector(nn.Module):
    def __init__(self, in_channels: list[int], out_channels: int, scale_factors: list[float], num_blocks: int) -> None:
        super().__init__()
        self.use_extra_pool = False
        self.stages = nn.ModuleList()

        for scale in scale_factors:
            if scale == 0.25:
                self.use_extra_pool = True
                continue

            self.stages.append(ProjectorStage(in_channels, out_channels, scale, num_blocks=num_blocks))

    def forward(self, features: list[torch.Tensor]) -> list[torch.Tensor]:
        results: list[torch.Tensor] = []

        if len(features) == 0:
            return results

        ref_idx = len(features) // 2
        ref_h, ref_w = features[ref_idx].shape[-2:]

        for stage in self.stages:
            results.append(stage(features, ref_h, ref_w))

        if self.use_extra_pool is True and len(results) > 0:
            results.append(F.max_pool2d(results[-1], kernel_size=(1, 1), stride=(2, 2), padding=(0, 0)))

        return results


class RF_DETR(LW_DETR):
    default_size = (576, 576)

    def __init__(
        self,
        num_classes: int,
        backbone: DetectorBackbone,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
        export_mode: bool = False,
    ) -> None:
        super().__init__(num_classes, backbone, config=config, size=size, export_mode=export_mode)
        assert self.config is not None, "must set config"

        # Num classes defined at LW_DETR (parent class)

        dropout = 0.0
        num_decoder_layers: int = self.config.get("num_decoder_layers", 4)
        projector_dim: int = self.config.get("projector_dim", 256)
        projector_scale_factors: list[float] = self.config["projector_scale_factors"]
        projector_num_blocks: int = self.config.get("projector_num_blocks", 3)
        decoder_dim: int = self.config.get("decoder_dim", 256)
        dim_feedforward: int = self.config.get("dim_feedforward", 2048)
        decoder_self_heads: int = self.config.get("decoder_self_heads", 8)
        decoder_cross_heads: int = self.config.get("decoder_cross_heads", 16)
        decoder_points: int = self.config.get("decoder_points", 2)
        num_queries: int = self.config.get("num_queries", 300)
        num_select: int = self.config.get("num_select", 300)
        group_detr: int = self.config.get("group_detr", 13)
        soft_nms: bool = self.config.get("soft_nms", False)

        self.soft_nms = None
        if soft_nms is True:
            self.soft_nms = SoftNMS()

        self.ia_alpha = 0.25
        self.loss_class = 1.0
        self.loss_bbox = 5.0
        self.loss_giou = 2.0
        self.match_cost_class = 2.0
        self.aux_loss = True
        self.num_queries = num_queries
        self.num_select = num_select
        self.two_stage = True
        self.group_detr = group_detr

        num_decoder_levels = len(projector_scale_factors)

        self.projector = MultiScaleProjector(
            in_channels=list(self.backbone.return_channels),
            out_channels=projector_dim,
            scale_factors=projector_scale_factors,
            num_blocks=projector_num_blocks,
        )
        self.decoder_input_proj = nn.ModuleList(
            [
                (
                    nn.Conv2d(projector_dim, decoder_dim, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0))
                    if projector_dim != decoder_dim
                    else nn.Identity()
                )
                for _ in range(num_decoder_levels)
            ]
        )
        self.decoder = LW_DETRDecoder(
            hidden_dim=decoder_dim,
            num_classes=self.num_classes,
            num_queries=self.num_queries,
            num_decoder_layers=num_decoder_layers,
            num_levels=num_decoder_levels,
            num_self_heads=decoder_self_heads,
            num_cross_heads=decoder_cross_heads,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            num_decoder_points=decoder_points,
            group_detr=self.group_detr,
            two_stage=self.two_stage,
        )

        self.enc_output = nn.ModuleList([nn.Linear(decoder_dim, decoder_dim) for _ in range(self.group_detr)])
        self.enc_output_norm = nn.ModuleList([nn.LayerNorm(decoder_dim) for _ in range(self.group_detr)])
        self.enc_out_class_embed = nn.ModuleList(
            [copy.deepcopy(self.decoder.class_embed) for _ in range(self.group_detr)]
        )
        self.enc_out_bbox_embed = nn.ModuleList(
            [copy.deepcopy(self.decoder.bbox_embed) for _ in range(self.group_detr)]
        )

        # Weights initialization
        for enc_output in self.enc_output:
            nn.init.xavier_uniform_(enc_output.weight)
            if enc_output.bias is not None:
                nn.init.zeros_(enc_output.bias)

        for enc_output_norm in self.enc_output_norm:
            nn.init.ones_(enc_output_norm.weight)
            nn.init.zeros_(enc_output_norm.bias)

        self.decoder_dim = decoder_dim
        self.matcher = HungarianMatcher(
            cost_class=self.match_cost_class,
            cost_bbox=self.loss_bbox,
            cost_giou=self.loss_giou,
        )

        # Export mode defined at LW_DETR (parent class)


registry.register_model_config(
    "rf_detr_nano",
    RF_DETR,
    config={"num_backbone_levels": 4, "num_decoder_layers": 2, "projector_scale_factors": [1.0]},
)
registry.register_model_config(
    "rf_detr_small",  # Base
    RF_DETR,
    config={"num_backbone_levels": 4, "num_decoder_layers": 3, "projector_scale_factors": [1.0]},
)
registry.register_model_config(
    "rf_detr",  # Medium
    RF_DETR,
    config={"num_backbone_levels": 4, "num_decoder_layers": 4, "projector_scale_factors": [1.0]},
)
registry.register_model_config(
    "rf_detr_large",  # Deprecated
    RF_DETR,
    config={
        "num_backbone_levels": 4,
        "projector_dim": 384,
        "num_decoder_layers": 3,
        "projector_scale_factors": [2.0, 0.5],
        "decoder_dim": 384,
        "decoder_self_heads": 12,
        "decoder_cross_heads": 24,
        "decoder_points": 4,
    },
)
