"""
RTMDet, adapted from
https://github.com/open-mmlab/mmdetection/tree/main/configs/rtmdet

Paper "RTMDet: An Empirical Study of Designing Real-Time Object Detectors", https://arxiv.org/abs/2212.07784

Generated by gpt-5.6-sol max.
"""

# Reference license: Apache-2.0

import math
from collections.abc import Callable
from functools import partial
from typing import Any
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn
from torchvision.ops import Conv2dNormActivation
from torchvision.ops import boxes as box_ops

from birder.common import training_utils
from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.cspnext import CSPNeXtLayer
from birder.net.detection.base import DetectionBaseNet
from birder.net.detection.base import aligned_generalized_box_iou
from birder.net.detection.base import clip_boxes_to_image


def _pairwise_box_iou(boxes1: torch.Tensor, boxes2: torch.Tensor) -> torch.Tensor:
    # T and S regress raw distances, so untrained predictions can have inverted sides.
    top_left = torch.maximum(boxes1[:, None, :2], boxes2[None, :, :2])
    bottom_right = torch.minimum(boxes1[:, None, 2:], boxes2[None, :, 2:])
    intersection_wh = (bottom_right - top_left).clamp(min=0)
    intersection = intersection_wh[..., 0] * intersection_wh[..., 1]

    boxes1_wh = (boxes1[:, 2:] - boxes1[:, :2]).clamp(min=0)
    boxes2_wh = (boxes2[:, 2:] - boxes2[:, :2]).clamp(min=0)
    boxes1_area = boxes1_wh[:, 0] * boxes1_wh[:, 1]
    boxes2_area = boxes2_wh[:, 0] * boxes2_wh[:, 1]
    union = boxes1_area[:, None] + boxes2_area[None, :] - intersection

    return intersection / union.clamp(min=1e-7)


def _distance_to_boxes(points: torch.Tensor, distances: torch.Tensor) -> torch.Tensor:
    return torch.stack(
        [
            points[..., 0] - distances[..., 0],
            points[..., 1] - distances[..., 1],
            points[..., 0] + distances[..., 2],
            points[..., 1] + distances[..., 3],
        ],
        dim=-1,
    )


def _quality_focal_loss(
    logits: torch.Tensor, labels: torch.Tensor, quality: torch.Tensor, beta: float = 2.0
) -> torch.Tensor:
    probabilities = logits.sigmoid()
    loss = F.binary_cross_entropy_with_logits(logits, torch.zeros_like(logits), reduction="none")
    loss = loss * probabilities.pow(beta)

    foreground = labels < logits.size(1)
    foreground_indices = torch.where(foreground)[0]
    foreground_labels = labels[foreground_indices]
    scale = quality[foreground_indices] - probabilities[foreground_indices, foreground_labels]
    loss[foreground_indices, foreground_labels] = F.binary_cross_entropy_with_logits(
        logits[foreground_indices, foreground_labels], quality[foreground_indices], reduction="none"
    ) * scale.abs().pow(beta)

    return loss.sum(dim=1)


class DynamicSoftLabelAssigner(nn.Module):
    def __init__(self, soft_center_radius: float, topk: int, iou_weight: float) -> None:
        super().__init__()
        self.soft_center_radius = soft_center_radius
        self.topk = topk
        self.iou_weight = iou_weight

    def forward(
        self,
        class_logits: torch.Tensor,
        boxes: torch.Tensor,
        priors: torch.Tensor,
        target_labels: torch.Tensor,
        target_boxes: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        prior_centers = priors[:, :2]
        left_top = prior_centers[:, None] - target_boxes[None, :, :2]
        right_bottom = target_boxes[None, :, 2:] - prior_centers[:, None]
        inside_targets = torch.concat([left_top, right_bottom], dim=-1).min(dim=-1).values > 0
        valid_mask = inside_targets.any(dim=1)
        valid_indices = torch.where(valid_mask)[0]
        if valid_indices.numel() == 0:
            return (
                valid_indices,
                target_labels.new_empty((0,)),
                boxes.new_empty((0,)),
            )

        valid_logits = class_logits[valid_mask]
        valid_boxes = boxes[valid_mask]
        valid_priors = priors[valid_mask]
        pairwise_ious = _pairwise_box_iou(valid_boxes, target_boxes)

        target_centers = (target_boxes[:, :2] + target_boxes[:, 2:]) * 0.5
        center_distance = (valid_priors[:, None, :2] - target_centers[None]).pow(2).sum(dim=-1).sqrt()
        center_distance = center_distance / valid_priors[:, None, 2]
        soft_center_prior = torch.pow(10.0, center_distance - self.soft_center_radius)

        iou_cost = -torch.log(pairwise_ious + 1e-7) * self.iou_weight

        probabilities = valid_logits.sigmoid()
        negative_cost = F.binary_cross_entropy_with_logits(
            valid_logits, torch.zeros_like(valid_logits), reduction="none"
        ) * probabilities.pow(2.0)

        # Replace only the target-class term instead of materializing a priors x targets x classes one-hot tensor
        target_logits = valid_logits[:, target_labels]
        target_probabilities = probabilities[:, target_labels]
        target_negative_cost = negative_cost[:, target_labels]
        target_positive_cost = F.binary_cross_entropy_with_logits(target_logits, pairwise_ious, reduction="none") * (
            pairwise_ious - target_probabilities
        ).abs().pow(2.0)
        classification_cost = negative_cost.sum(dim=-1, keepdim=True) - target_negative_cost
        classification_cost = classification_cost + target_positive_cost

        cost = classification_cost + iou_cost + soft_center_prior
        matching_matrix = torch.zeros_like(cost, dtype=torch.bool)
        candidate_topk = min(self.topk, pairwise_ious.size(0))
        topk_ious = torch.topk(pairwise_ious, candidate_topk, dim=0).values
        dynamic_ks = topk_ious.sum(dim=0).to(torch.int64).clamp(min=1)
        for target_idx in range(target_boxes.size(0)):
            dynamic_k = int(dynamic_ks[target_idx].item())
            matched_indices = torch.topk(cost[:, target_idx], dynamic_k, largest=False).indices
            matching_matrix[matched_indices, target_idx] = True

        multiple_matches = matching_matrix.sum(dim=1) > 1
        if multiple_matches.any():
            minimum_cost_targets = cost[multiple_matches].argmin(dim=1)
            matching_matrix[multiple_matches] = False
            matching_matrix[multiple_matches, minimum_cost_targets] = True

        foreground = matching_matrix.any(dim=1)
        matched_target_indices = matching_matrix[foreground].to(pairwise_ious.dtype).argmax(dim=1)
        matched_ious = pairwise_ious[foreground, matched_target_indices]

        return (valid_indices[foreground], matched_target_indices, matched_ious)


class CSPNeXtPAFPN(nn.Module):
    def __init__(self, in_channels: list[int], out_channels: int, num_csp_blocks: int) -> None:
        super().__init__()
        norm_layer = partial(nn.BatchNorm2d, eps=0.001, momentum=0.03)

        self.reduce_layers = nn.ModuleList()
        self.top_down_layers = nn.ModuleList()
        for level_idx in range(len(in_channels) - 1, 0, -1):
            self.reduce_layers.append(
                Conv2dNormActivation(
                    in_channels[level_idx],
                    in_channels[level_idx - 1],
                    kernel_size=(1, 1),
                    stride=(1, 1),
                    padding=(0, 0),
                    norm_layer=norm_layer,
                    activation_layer=nn.SiLU,
                )
            )
            self.top_down_layers.append(
                CSPNeXtLayer(
                    2 * in_channels[level_idx - 1],
                    in_channels[level_idx - 1],
                    depth=num_csp_blocks,
                    shortcut=False,
                    expansion=0.5,
                    channel_attention=False,
                    norm_layer=norm_layer,
                )
            )

        self.downsample_layers = nn.ModuleList()
        self.bottom_up_layers = nn.ModuleList()
        for level_idx in range(len(in_channels) - 1):
            self.downsample_layers.append(
                Conv2dNormActivation(
                    in_channels[level_idx],
                    in_channels[level_idx],
                    kernel_size=(3, 3),
                    stride=(2, 2),
                    padding=(1, 1),
                    norm_layer=norm_layer,
                    activation_layer=nn.SiLU,
                )
            )
            self.bottom_up_layers.append(
                CSPNeXtLayer(
                    2 * in_channels[level_idx],
                    in_channels[level_idx + 1],
                    depth=num_csp_blocks,
                    shortcut=False,
                    expansion=0.5,
                    channel_attention=False,
                    norm_layer=norm_layer,
                )
            )

        self.out_convs = nn.ModuleList(
            [
                Conv2dNormActivation(
                    channels,
                    out_channels,
                    kernel_size=(3, 3),
                    stride=(1, 1),
                    padding=(1, 1),
                    norm_layer=norm_layer,
                    activation_layer=nn.SiLU,
                )
                for channels in in_channels
            ]
        )
        self.out_channels = out_channels

    def forward(self, features: list[torch.Tensor]) -> list[torch.Tensor]:
        inner_outputs = [features[-1]]
        for level_idx, (reduce_layer, top_down_layer) in enumerate(zip(self.reduce_layers, self.top_down_layers)):
            high_feature = reduce_layer(inner_outputs[0])
            inner_outputs[0] = high_feature
            low_feature = features[-level_idx - 2]
            high_feature = F.interpolate(high_feature, size=low_feature.shape[-2:], mode="nearest")
            inner_outputs.insert(0, top_down_layer(torch.concat([high_feature, low_feature], dim=1)))

        outputs = [inner_outputs[0]]
        for level_idx, (downsample_layer, bottom_up_layer) in enumerate(
            zip(self.downsample_layers, self.bottom_up_layers)
        ):
            low_feature = downsample_layer(outputs[-1])
            high_feature = inner_outputs[level_idx + 1]
            outputs.append(bottom_up_layer(torch.concat([low_feature, high_feature], dim=1)))

        final_outputs: list[torch.Tensor] = []
        for level_idx, out_conv in enumerate(self.out_convs):
            final_outputs.append(out_conv(outputs[level_idx]))

        return final_outputs


class RTMDetHeadBranch(nn.Module):
    def __init__(self, channels: int, num_convs: int, num_levels: int, norm_layer: Callable[..., nn.Module]) -> None:
        super().__init__()
        self.convs = nn.ModuleList(
            [
                nn.Conv2d(channels, channels, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                for _ in range(num_convs)
            ]
        )
        self.norms = nn.ModuleList(
            [nn.ModuleList([norm_layer(channels) for _ in range(num_levels)]) for _ in range(num_convs)]
        )
        self.activation = nn.SiLU()

    def forward(self, features: list[torch.Tensor]) -> list[torch.Tensor]:
        outputs = features
        for conv, level_norms in zip(self.convs, self.norms):
            block_outputs: list[torch.Tensor] = []
            for level_idx, norm in enumerate(level_norms):
                feature = outputs[level_idx]
                feature = conv(feature)
                feature = norm(feature)
                block_outputs.append(self.activation(feature))

            outputs = block_outputs

        return outputs


class RTMDetHead(nn.Module):
    def __init__(
        self, channels: int, num_classes: int, num_convs: int, strides: tuple[int, ...], exp_on_reg: bool
    ) -> None:
        super().__init__()
        self.num_classes = num_classes
        self.strides = strides
        self.exp_on_reg = exp_on_reg

        norm_layer = partial(nn.BatchNorm2d, eps=0.001, momentum=0.03)
        self.classification_branch = RTMDetHeadBranch(channels, num_convs, len(strides), norm_layer)
        self.regression_branch = RTMDetHeadBranch(channels, num_convs, len(strides), norm_layer)
        self.classification_heads = nn.ModuleList(
            [nn.Conv2d(channels, num_classes, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0)) for _ in strides]
        )
        self.regression_heads = nn.ModuleList(
            [nn.Conv2d(channels, 4, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0)) for _ in strides]
        )

        # Weights initialization
        for module in self.modules():
            if isinstance(module, nn.Conv2d):
                nn.init.normal_(module.weight, mean=0.0, std=0.01)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)

            elif isinstance(module, nn.BatchNorm2d):
                nn.init.ones_(module.weight)
                nn.init.zeros_(module.bias)

        self._initialize_classification_heads()

    def _initialize_classification_heads(self) -> None:
        bias = -math.log((1.0 - 0.01) / 0.01)
        for classification_head in self.classification_heads:
            nn.init.normal_(classification_head.weight, mean=0.0, std=0.01)
            nn.init.constant_(classification_head.bias, bias)

    def reset_classifier(self, num_classes: int) -> None:
        self.num_classes = num_classes
        channels = self.classification_heads[0].in_channels
        self.classification_heads = nn.ModuleList(
            [nn.Conv2d(channels, num_classes, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0)) for _ in self.strides]
        )
        self._initialize_classification_heads()

    def forward(self, features: list[torch.Tensor]) -> dict[str, list[torch.Tensor]]:
        classification_features = self.classification_branch(features)
        regression_features = self.regression_branch(features)

        class_logits = []
        box_regression = []
        for level_idx, (classification_head, regression_head) in enumerate(
            zip(self.classification_heads, self.regression_heads)
        ):
            classification_feature = classification_features[level_idx]
            regression_feature = regression_features[level_idx]
            class_logits.append(classification_head(classification_feature))
            distances = regression_head(regression_feature)
            if self.exp_on_reg is True:
                distances = distances.exp()

            box_regression.append(distances * self.strides[level_idx])

        return {"cls_logits": class_logits, "bbox_regression": box_regression}


class RTMDet(DetectionBaseNet):
    default_size = (640, 640)

    def __init__(
        self,
        num_classes: int,
        backbone: DetectorBackbone,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
        export_mode: bool = False,
    ) -> None:
        super().__init__(num_classes, backbone, config=config, size=size, export_mode=export_mode)
        assert self.config is not None, "must set config"

        self.num_classes = self.num_classes - 1
        self.strides = (8, 16, 32)
        self.score_thresh = 0.001
        self.nms_thresh = 0.65
        self.detections_per_img = 300
        self.topk_candidates = 30000

        fpn_width: int = self.config["fpn_width"]
        num_csp_blocks: int = self.config["num_csp_blocks"]
        exp_on_reg: bool = self.config["exp_on_reg"]

        self.backbone.return_channels = self.backbone.return_channels[-3:]
        self.backbone.return_stages = self.backbone.return_stages[-3:]
        self.neck = CSPNeXtPAFPN(self.backbone.return_channels, fpn_width, num_csp_blocks)
        self.head = RTMDetHead(fpn_width, self.num_classes, num_convs=2, strides=self.strides, exp_on_reg=exp_on_reg)
        self.assigner = DynamicSoftLabelAssigner(soft_center_radius=3.0, topk=13, iou_weight=3.0)

        if self.export_mode is False:
            self.forward = torch.compiler.disable(recursive=False)(self.forward)  # type: ignore[method-assign]

    def reset_classifier(self, num_classes: int) -> None:
        self.num_classes = num_classes
        self.head.reset_classifier(num_classes)

    def freeze(self, freeze_classifier: bool = True) -> None:
        for param in self.parameters():
            param.requires_grad_(False)

        if freeze_classifier is False:
            for param in self.head.classification_branch.parameters():
                param.requires_grad_(True)

            for param in self.head.classification_heads.parameters():
                param.requires_grad_(True)

    def _generate_priors(self, features: list[torch.Tensor]) -> list[torch.Tensor]:
        priors = []
        for level_idx, feature in enumerate(features):
            stride = self.strides[level_idx]
            height = feature.size(2)
            width = feature.size(3)
            shifts_x = torch.arange(width, dtype=torch.float32, device=feature.device) * stride
            shifts_y = torch.arange(height, dtype=torch.float32, device=feature.device) * stride
            shift_y, shift_x = torch.meshgrid(shifts_y, shifts_x, indexing="ij")
            stride_x = torch.full_like(shift_x, stride)
            stride_y = torch.full_like(shift_y, stride)
            priors.append(torch.stack([shift_x, shift_y, stride_x, stride_y], dim=-1).reshape(-1, 4))

        return priors

    @torch.jit.unused  # type: ignore[untyped-decorator]
    @torch.compiler.disable()  # type: ignore[untyped-decorator]
    def compute_loss(
        self,
        targets: list[dict[str, torch.Tensor]],
        head_outputs: dict[str, list[torch.Tensor]],
        priors: list[torch.Tensor],
    ) -> dict[str, torch.Tensor]:
        class_logits = torch.concat(
            [
                output.permute(0, 2, 3, 1).reshape(output.size(0), -1, self.num_classes)
                for output in head_outputs["cls_logits"]
            ],
            dim=1,
        )
        box_regression = torch.concat(
            [output.permute(0, 2, 3, 1).reshape(output.size(0), -1, 4) for output in head_outputs["bbox_regression"]],
            dim=1,
        )
        flattened_priors = torch.concat(priors, dim=0)
        decoded_boxes = _distance_to_boxes(flattened_priors[None, :, :2], box_regression)

        labels_per_image = []
        target_boxes_per_image = []
        assign_metrics_per_image = []
        for logits, boxes, target in zip(class_logits.detach(), decoded_boxes.detach(), targets):
            labels = torch.full((flattened_priors.size(0),), self.num_classes, dtype=torch.int64, device=logits.device)
            target_boxes = torch.zeros_like(boxes)
            assign_metrics = torch.zeros((flattened_priors.size(0),), dtype=torch.float32, device=logits.device)
            if target["boxes"].numel() > 0:
                target_labels = target["labels"] - 1
                positive_indices, matched_target_indices, matched_ious = self.assigner(
                    logits.float(),
                    boxes.float(),
                    flattened_priors,
                    target_labels,
                    target["boxes"].float(),
                )
                labels[positive_indices] = target_labels[matched_target_indices]
                target_boxes[positive_indices] = target["boxes"][matched_target_indices]
                assign_metrics[positive_indices] = matched_ious

            labels_per_image.append(labels)
            target_boxes_per_image.append(target_boxes)
            assign_metrics_per_image.append(assign_metrics)

        labels = torch.stack(labels_per_image)
        target_boxes = torch.stack(target_boxes_per_image)
        assign_metrics = torch.stack(assign_metrics_per_image)

        classification_avg_factor = assign_metrics.sum()
        if training_utils.is_dist_available_and_initialized() is True:
            torch.distributed.all_reduce(classification_avg_factor)

        classification_avg_factor = classification_avg_factor / training_utils.get_world_size()
        classification_avg_factor = classification_avg_factor.clamp(min=1.0)
        classification_loss = _quality_focal_loss(
            class_logits.float().reshape(-1, self.num_classes),
            labels.reshape(-1),
            assign_metrics.reshape(-1),
        ).sum()
        classification_loss = classification_loss / classification_avg_factor

        foreground = labels < self.num_classes
        if foreground.any():
            regression_loss = 1.0 - aligned_generalized_box_iou(
                decoded_boxes[foreground].float(), target_boxes[foreground].float()
            )
            regression_loss = (regression_loss * assign_metrics[foreground]).sum() / classification_avg_factor
            regression_loss = 2.0 * regression_loss
        else:
            regression_loss = decoded_boxes.sum() * 0.0

        return {"classification": classification_loss, "bbox_regression": regression_loss}

    def postprocess_detections(
        self,
        head_outputs: dict[str, list[torch.Tensor]],
        priors: list[torch.Tensor],
        image_sizes: torch.Tensor,
    ) -> list[dict[str, torch.Tensor]]:
        detections: list[dict[str, torch.Tensor]] = []
        for image_idx in range(image_sizes.size(0)):
            image_boxes_list = []
            image_scores_list = []
            image_labels_list = []
            for logits, regression, priors_per_level in zip(
                head_outputs["cls_logits"], head_outputs["bbox_regression"], priors
            ):
                logits_per_image = logits[image_idx].permute(1, 2, 0).reshape(-1, self.num_classes)
                regression_per_image = regression[image_idx].permute(1, 2, 0).reshape(-1, 4)

                scores_per_level = logits_per_image.sigmoid().flatten()
                keep_indices = torch.where(scores_per_level > self.score_thresh)[0]
                scores_per_level = scores_per_level[keep_indices]
                num_topk = min(self.topk_candidates, keep_indices.size(0))
                scores_per_level, topk_indices = scores_per_level.topk(num_topk)
                keep_indices = keep_indices[topk_indices]

                prior_indices = torch.div(keep_indices, self.num_classes, rounding_mode="floor")
                labels_per_level = keep_indices % self.num_classes
                boxes_per_level = _distance_to_boxes(
                    priors_per_level[prior_indices, :2], regression_per_image[prior_indices]
                )
                boxes_per_level = clip_boxes_to_image(boxes_per_level, image_sizes[image_idx])

                image_boxes_list.append(boxes_per_level)
                image_scores_list.append(scores_per_level)
                image_labels_list.append(labels_per_level + 1)

            image_boxes = torch.concat(image_boxes_list, dim=0)
            image_scores = torch.concat(image_scores_list, dim=0)
            image_labels = torch.concat(image_labels_list, dim=0)

            if self.export_mode is False:
                keep = box_ops.batched_nms(image_boxes, image_scores, image_labels, self.nms_thresh)
                keep = keep[: self.detections_per_img]
                image_boxes = image_boxes[keep]
                image_scores = image_scores[keep]
                image_labels = image_labels[keep]

            detections.append({"boxes": image_boxes, "scores": image_scores, "labels": image_labels})

        return detections

    def forward_net(
        self, x: torch.Tensor
    ) -> tuple[list[torch.Tensor], dict[str, list[torch.Tensor]], list[torch.Tensor]]:
        backbone_features = self.backbone.detection_features(x)
        features = self.neck(list(backbone_features.values()))
        head_outputs = self.head(features)
        priors = self._generate_priors(features)

        return (features, head_outputs, priors)

    def forward(
        self,
        x: torch.Tensor,
        targets: Optional[list[dict[str, torch.Tensor]]] = None,
        masks: Optional[torch.Tensor] = None,
        image_sizes: Optional[list[tuple[int, int]]] = None,
    ) -> tuple[list[dict[str, torch.Tensor]], dict[str, torch.Tensor]]:
        self._input_check(targets)
        images = self._to_img_list(x, image_sizes)
        _, head_outputs, priors = self.forward_net(x)

        losses = {}
        detections: list[dict[str, torch.Tensor]] = []
        if self.training is True:
            assert targets is not None, "targets should not be none when in training mode"
            losses = self.compute_loss(targets, head_outputs, priors)

        else:
            detections = self.postprocess_detections(head_outputs, priors, images.image_sizes)

        return (detections, losses)


registry.register_model_config("rtmdet_t", RTMDet, config={"fpn_width": 96, "num_csp_blocks": 1, "exp_on_reg": False})
registry.register_model_config("rtmdet_s", RTMDet, config={"fpn_width": 128, "num_csp_blocks": 1, "exp_on_reg": False})
registry.register_model_config("rtmdet_m", RTMDet, config={"fpn_width": 192, "num_csp_blocks": 2, "exp_on_reg": True})
registry.register_model_config("rtmdet_l", RTMDet, config={"fpn_width": 256, "num_csp_blocks": 3, "exp_on_reg": True})
registry.register_model_config("rtmdet_xl", RTMDet, config={"fpn_width": 320, "num_csp_blocks": 4, "exp_on_reg": True})
