"""
SimDINO v2, adapted from
https://github.com/RobinWu218/SimDINO/tree/main/simdinov2

Paper "Simplifying DINO via Coding Rate Regularization", https://arxiv.org/abs/2502.10385

Changes from original:
* Normalized non-reduced coding rates by the local batch size
* Computed the losses in float32, including under autocast

Generated by gpt-6-sol max.
"""

# Reference license: Apache-2.0

from typing import Optional

import torch
import torch.distributed as dist
import torch.distributed._functional_collectives as funcol
import torch.nn.functional as F
from torch import nn

from birder.common import training_utils
from birder.net.ssl.dino_v2 import DINOv2Student
from birder.net.ssl.dino_v2 import DINOv2Teacher


class MCRLoss(nn.Module):
    """
    Cross-view alignment and coding-rate expansion for normalized embeddings

    Student views must start with the two global views, in the same order as
    the teacher views. Matching global views are excluded from alignment.
    eps denotes the distortion variance (epsilon squared in the paper).
    """

    def __init__(self, eps: float = 0.05, coeff: float = 1.0, expa_type: int = 1, reduce_cov: bool = False) -> None:
        super().__init__()
        if expa_type not in (0, 1):
            raise ValueError("expa_type must be 0 (student) or 1 (student/teacher average)")

        self.eps = eps
        self.coeff = coeff
        self.expa_type = expa_type
        self.reduce_cov = reduce_cov

    def forward(
        self, student_output_list: list[torch.Tensor], teacher_output_list: list[torch.Tensor]
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        with torch.amp.autocast(student_output_list[0].device.type, enabled=False):
            student = torch.stack(student_output_list).float()
            teacher = torch.stack(teacher_output_list).detach().float()

            # Average cosine similarity across all pairs except matching global views
            similarities = torch.einsum("tbd,sbd->tsb", teacher, student).mean(dim=-1)
            matching_views = torch.eye(2, student.size(0), device=student.device, dtype=torch.bool)
            compression = similarities.masked_fill(matching_views, 0).sum() / (2 * student.size(0) - 2)

            features = student[:2]
            if self.expa_type == 1:
                features = (features + teacher) / 2

            # The reference uses uncentered second moments, separately for each global view
            covariance = features.transpose(-2, -1) @ features
            num_samples = features.new_tensor(features.size(1))
            if self.reduce_cov is True and training_utils.is_dist_available_and_initialized() is True:
                covariance = funcol.all_reduce(covariance, reduceOp="sum", group=dist.group.WORLD)
                num_samples = funcol.all_reduce(num_samples, reduceOp="sum", group=dist.group.WORLD)

            dim = features.size(-1)
            identity = torch.eye(dim, device=features.device, dtype=features.dtype)
            matrix = identity + covariance * (dim / (num_samples * self.eps))
            cholesky = torch.linalg.cholesky_ex(matrix)[0]  # pylint: disable=not-callable
            coding_rate = cholesky.diagonal(dim1=-2, dim2=-1).log().sum(dim=-1).mean()
            coding_rate = coding_rate * (dim + num_samples) / (dim * num_samples)

            loss = -self.coeff * compression - coding_rate

        return (loss, compression.detach(), coding_rate.detach())


class CosinePatchLoss(nn.Module):
    def forward(
        self,
        student_patch_tokens: torch.Tensor,
        teacher_patch_tokens: torch.Tensor,
        student_masks_flat: torch.Tensor,
        masks_weight: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        with torch.amp.autocast(student_patch_tokens.device.type, enabled=False):
            similarities = F.cosine_similarity(  # pylint: disable=not-callable
                student_patch_tokens.float(), teacher_patch_tokens.detach().float(), dim=-1
            )
            if masks_weight is None:
                per_sample_weight = student_masks_flat.sum(dim=-1).clamp_min(1).float().reciprocal()
                masks_weight = per_sample_weight.unsqueeze(-1).expand_as(student_masks_flat)[student_masks_flat]

            # Unmasked images contribute zero; an empty mask yields a differentiable zero
            loss = -(similarities * masks_weight).sum() / student_masks_flat.size(0)

        return loss


class SimDINOv2Student(DINOv2Student):
    pass


class SimDINOv2Teacher(DINOv2Teacher):
    def forward(  # type: ignore[override]
        self,
        x: torch.Tensor,
        n_crops: int,
        upper_bound: int,
        mask_indices_list: torch.Tensor,
        target_feature_size: Optional[tuple[int, int]] = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        # if n_crops != 2:
        #     raise ValueError("SimDINO v2 requires two global crops")

        embedding, patches = super().forward(x, n_crops, upper_bound, mask_indices_list, target_feature_size)
        # DINO v2 swaps global views so A is matched to B in the cross-view loss. The MCR loss needs
        # the original order to exclude matching views and average matching teacher and student features
        second, first = embedding.chunk(2)
        return (torch.concat((first, second)), patches)
