"""
ACNet and Diverse Branch Block, adapted from
https://github.com/DingXiaoH/ACNet/blob/master/acnet/acb.py
and
https://github.com/DingXiaoH/DiverseBranchBlock/blob/main/diversebranchblock.py

Paper "ACNet: Strengthening the Kernel Skeletons for Powerful CNN via Asymmetric Convolution Blocks",
https://arxiv.org/abs/1908.03930
and
Paper "Diverse Branch Block: Building a Convolution as an Inception-like Unit",
https://arxiv.org/abs/2103.13425

Generated by gpt-5.6-sol max.
"""

# Reference license: MIT and Apache-2.0

from collections import OrderedDict
from collections.abc import Callable
from typing import Any
from typing import Literal
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn
from torch.nn.utils.fusion import fuse_conv_bn_weights
from torchvision.ops import Conv2dNormActivation
from torchvision.ops import SqueezeExcitation

from birder.common.masking import mask_tensor
from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.base import MaskedTokenRetentionMixin
from birder.net.base import PreTrainEncoder
from birder.net.base import TokenRetentionResultType


def _fuse_conv_bn(conv: nn.Conv2d, bn: nn.BatchNorm2d) -> tuple[torch.Tensor, torch.Tensor]:
    return fuse_conv_bn_weights(  # type: ignore[no-any-return]
        conv.weight,
        conv.bias,
        bn.running_mean,
        bn.running_var,
        bn.eps,
        bn.weight,
        bn.bias,
    )


class Conv2dBN(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: tuple[int, int],
        padding: int,
        groups: int = 1,
    ) -> None:
        super().__init__()
        self.conv = nn.Conv2d(
            in_channels,
            out_channels,
            kernel_size=(kernel_size, kernel_size),
            stride=stride,
            padding=(padding, padding),
            groups=groups,
            bias=False,
        )
        self.bn = nn.BatchNorm2d(out_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.bn(self.conv(x))


class AsymmetricConvBlock(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: tuple[int, int],
        padding: int,
        groups: int = 1,
        reparameterized: bool = False,
    ) -> None:
        super().__init__()
        assert kernel_size % 2 == 1

        self.reparameterized = reparameterized
        self.kernel_size = kernel_size

        if reparameterized is True:
            self.reparam_conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size, kernel_size),
                stride=stride,
                padding=(padding, padding),
                groups=groups,
            )
        else:
            self.reparam_conv = None

            self.square_conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size, kernel_size),
                stride=stride,
                padding=(padding, padding),
                groups=groups,
                bias=False,
            )
            self.square_bn = nn.BatchNorm2d(out_channels)

            center_offset = kernel_size // 2  # * dilation
            if padding >= center_offset:
                self.crop = 0
                horizontal_padding = (padding - center_offset, padding)
                vertical_padding = (padding, padding - center_offset)
            else:
                self.crop = center_offset - padding
                horizontal_padding = (0, padding)
                vertical_padding = (padding, 0)

            self.vertical_conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size, 1),
                stride=stride,
                padding=vertical_padding,
                groups=groups,
                bias=False,
            )
            self.vertical_bn = nn.BatchNorm2d(out_channels)
            self.horizontal_conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(1, kernel_size),
                stride=stride,
                padding=horizontal_padding,
                groups=groups,
                bias=False,
            )
            self.horizontal_bn = nn.BatchNorm2d(out_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.reparam_conv is not None:
            return self.reparam_conv(x)

        square = self.square_bn(self.square_conv(x))
        if self.crop > 0:
            vertical_input = x[:, :, :, self.crop : -self.crop]
            horizontal_input = x[:, :, self.crop : -self.crop, :]
        else:
            vertical_input = x
            horizontal_input = x

        vertical = self.vertical_bn(self.vertical_conv(vertical_input))
        horizontal = self.horizontal_bn(self.horizontal_conv(horizontal_input))

        return square + vertical + horizontal

    @torch.no_grad()  # type: ignore[untyped-decorator]
    def reparameterize(self) -> None:
        if self.reparameterized is True:
            return

        kernel, bias = self._get_kernel_bias()
        self.reparam_conv = nn.Conv2d(
            in_channels=self.square_conv.in_channels,
            out_channels=self.square_conv.out_channels,
            kernel_size=self.square_conv.kernel_size,
            stride=self.square_conv.stride,
            padding=self.square_conv.padding,
            dilation=self.square_conv.dilation,
            groups=self.square_conv.groups,
            device=kernel.device,
            dtype=kernel.dtype,
        )
        self.reparam_conv.weight.copy_(kernel)
        self.reparam_conv.bias.copy_(bias)

        # Delete unused branches
        for param in self.parameters():
            param.detach_()

        del self.square_conv
        del self.square_bn
        del self.vertical_conv
        del self.vertical_bn
        del self.horizontal_conv
        del self.horizontal_bn

        self.reparameterized = True

    def _get_kernel_bias(self) -> tuple[torch.Tensor, torch.Tensor]:
        square_kernel, square_bias = _fuse_conv_bn(self.square_conv, self.square_bn)
        vertical_kernel, vertical_bias = _fuse_conv_bn(self.vertical_conv, self.vertical_bn)
        horizontal_kernel, horizontal_bias = _fuse_conv_bn(self.horizontal_conv, self.horizontal_bn)

        center = self.kernel_size // 2
        vertical_kernel = F.pad(vertical_kernel, [center, center, 0, 0])
        horizontal_kernel = F.pad(horizontal_kernel, [0, 0, center, center])

        return (
            square_kernel + vertical_kernel + horizontal_kernel,
            square_bias + vertical_bias + horizontal_bias,
        )


class IdentityBasedConv1x1(nn.Conv2d):
    def __init__(self, channels: int, groups: int) -> None:
        super().__init__(channels, channels, kernel_size=1, groups=groups, bias=False)

        input_dim = channels // groups
        identity = torch.zeros_like(self.weight)
        for i in range(channels):
            identity[i, i % input_dim, 0, 0] = 1

        self.identity = nn.Buffer(identity, persistent=False)
        nn.init.zeros_(self.weight)

    def forward(self, x: torch.Tensor) -> torch.Tensor:  # pylint: disable=arguments-renamed
        return F.conv2d(x, self._get_actual_kernel(), groups=self.groups)  # pylint: disable=not-callable

    def _get_actual_kernel(self) -> torch.Tensor:
        return self.weight + self.identity


class BatchNormAndPad(nn.Module):
    def __init__(self, num_features: int, pad_pixels: int) -> None:
        super().__init__()
        self.bn = nn.BatchNorm2d(num_features)
        self.pad_pixels = pad_pixels

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.bn(x)
        if self.pad_pixels == 0:
            return x

        pad_values = self.bn.bias.detach() - (  # pylint: disable=not-callable
            self.bn.running_mean
            * self.bn.weight.detach()  # pylint: disable=not-callable
            / torch.sqrt(self.bn.running_var + self.bn.eps)
        )
        x = F.pad(x, [self.pad_pixels] * 4)
        pad_values = pad_values.view(1, -1, 1, 1)
        x[:, :, : self.pad_pixels, :] = pad_values
        x[:, :, -self.pad_pixels :, :] = pad_values
        x[:, :, :, : self.pad_pixels] = pad_values
        x[:, :, :, -self.pad_pixels :] = pad_values

        return x


class Conv2dBNAndPad(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, pad_pixels: int, groups: int = 1) -> None:
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1, groups=groups, bias=False)
        self.bn_pad = BatchNormAndPad(out_channels, pad_pixels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.bn_pad(self.conv(x))


class DiverseBranchBlock(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: tuple[int, int],
        padding: int,
        groups: int = 1,
        reparameterized: bool = False,
    ) -> None:
        super().__init__()
        assert kernel_size % 2 == 1
        assert padding == kernel_size // 2

        self.reparameterized = reparameterized
        self.kernel_size = kernel_size
        self.out_channels = out_channels
        self.groups = groups

        if reparameterized is True:
            self.reparam_conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size, kernel_size),
                stride=stride,
                padding=(padding, padding),
                dilation=(1, 1),
                groups=groups,
            )
        else:
            self.reparam_conv = None
            self.origin = Conv2dBN(
                in_channels,
                out_channels,
                kernel_size,
                stride=stride,
                padding=padding,
                groups=groups,
            )

            self.branch_1x1: Optional[Conv2dBN] = None
            self.avg_projection: Optional[Conv2dBNAndPad] = None
            if groups < out_channels:
                self.avg_projection = Conv2dBNAndPad(in_channels, out_channels, padding, groups=groups)
                self.avg_pool = nn.AvgPool2d(kernel_size=kernel_size, stride=stride)
                self.branch_1x1 = Conv2dBN(
                    in_channels, out_channels, kernel_size=1, stride=stride, padding=0, groups=groups
                )
            else:
                self.avg_pool = nn.AvgPool2d(kernel_size=kernel_size, stride=stride, padding=padding)

            self.avg_bn = nn.BatchNorm2d(out_channels)

            internal_channels = in_channels if groups < out_channels else 2 * in_channels
            self.kxk_first: nn.Conv2d
            if internal_channels == in_channels:
                self.kxk_first = IdentityBasedConv1x1(in_channels, groups)
            else:
                self.kxk_first = nn.Conv2d(
                    in_channels,
                    internal_channels,
                    kernel_size=1,
                    groups=groups,
                    bias=False,
                )

            self.kxk_bn_pad = BatchNormAndPad(internal_channels, padding)
            self.kxk_second = nn.Conv2d(
                internal_channels,
                out_channels,
                kernel_size=(kernel_size, kernel_size),
                stride=stride,
                dilation=(1, 1),
                groups=groups,
                bias=False,
            )
            self.kxk_bn = nn.BatchNorm2d(out_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.reparam_conv is not None:
            return self.reparam_conv(x)

        out = self.origin(x)
        if self.branch_1x1 is not None:
            out += self.branch_1x1(x)

        avg = x
        if self.avg_projection is not None:
            avg = self.avg_projection(avg)
        avg = self.avg_bn(self.avg_pool(avg))

        kxk = self.kxk_bn_pad(self.kxk_first(x))
        kxk = self.kxk_bn(self.kxk_second(kxk))

        return out + avg + kxk

    @torch.no_grad()  # type: ignore[untyped-decorator]
    def reparameterize(self) -> None:
        if self.reparameterized is True:
            return

        kernel, bias = self._get_kernel_bias()
        self.reparam_conv = nn.Conv2d(
            in_channels=self.origin.conv.in_channels,
            out_channels=self.origin.conv.out_channels,
            kernel_size=self.origin.conv.kernel_size,
            stride=self.origin.conv.stride,
            padding=self.origin.conv.padding,
            dilation=self.origin.conv.dilation,
            groups=self.origin.conv.groups,
            device=kernel.device,
            dtype=kernel.dtype,
        )
        self.reparam_conv.weight.copy_(kernel)
        self.reparam_conv.bias.copy_(bias)

        # Delete unused branches
        for param in self.parameters():
            param.detach_()

        del self.origin
        del self.branch_1x1
        del self.avg_projection
        del self.avg_pool
        del self.avg_bn
        del self.kxk_first
        del self.kxk_bn_pad
        del self.kxk_second
        del self.kxk_bn

        self.reparameterized = True

    def _get_kernel_bias(self) -> tuple[torch.Tensor, torch.Tensor]:
        origin_kernel, origin_bias = _fuse_conv_bn(self.origin.conv, self.origin.bn)

        if self.branch_1x1 is None:
            branch_1x1_kernel = torch.zeros_like(origin_kernel)
            branch_1x1_bias = torch.zeros_like(origin_bias)
        else:
            branch_1x1_kernel, branch_1x1_bias = _fuse_conv_bn(self.branch_1x1.conv, self.branch_1x1.bn)
            center = self.kernel_size // 2
            branch_1x1_kernel = F.pad(branch_1x1_kernel, [center, center, center, center])

        if isinstance(self.kxk_first, IdentityBasedConv1x1):
            kxk_first_kernel = self.kxk_first._get_actual_kernel()
        else:
            kxk_first_kernel = self.kxk_first.weight

        kxk_first_kernel, kxk_first_bias = fuse_conv_bn_weights(
            kxk_first_kernel,
            None,
            self.kxk_bn_pad.bn.running_mean,
            self.kxk_bn_pad.bn.running_var,
            self.kxk_bn_pad.bn.eps,
            self.kxk_bn_pad.bn.weight,
            self.kxk_bn_pad.bn.bias,
        )
        kxk_second_kernel, kxk_second_bias = _fuse_conv_bn(self.kxk_second, self.kxk_bn)
        kxk_kernel, kxk_bias = self._compose_1x1_kxk(
            kxk_first_kernel,
            kxk_first_bias,
            kxk_second_kernel,
            kxk_second_bias,
        )

        avg_kernel = self._average_kernel(origin_kernel.device, origin_kernel.dtype)
        avg_kernel, avg_bias = fuse_conv_bn_weights(
            avg_kernel,
            None,
            self.avg_bn.running_mean,
            self.avg_bn.running_var,
            self.avg_bn.eps,
            self.avg_bn.weight,
            self.avg_bn.bias,
        )
        if self.avg_projection is not None:
            avg_first_kernel, avg_first_bias = _fuse_conv_bn(self.avg_projection.conv, self.avg_projection.bn_pad.bn)
            avg_kernel, avg_bias = self._compose_1x1_kxk(
                avg_first_kernel,
                avg_first_bias,
                avg_kernel,
                avg_bias,
            )

        return (
            origin_kernel + branch_1x1_kernel + avg_kernel + kxk_kernel,
            origin_bias + branch_1x1_bias + avg_bias + kxk_bias,
        )

    def _compose_1x1_kxk(
        self,
        first_kernel: torch.Tensor,
        first_bias: torch.Tensor,
        second_kernel: torch.Tensor,
        second_bias: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        if self.groups == 1:
            kernel = F.conv2d(second_kernel, first_kernel.permute(1, 0, 2, 3))  # pylint: disable=not-callable
            bias = (second_kernel * first_bias.reshape(1, -1, 1, 1)).sum((1, 2, 3))
        else:
            kernels = []
            biases = []
            first_kernel_t = first_kernel.permute(1, 0, 2, 3)
            first_group_width = first_kernel.size(0) // self.groups
            second_group_width = second_kernel.size(0) // self.groups
            for group_idx in range(self.groups):
                first_slice = first_kernel_t[
                    :, group_idx * first_group_width : (group_idx + 1) * first_group_width, :, :
                ]
                second_slice = second_kernel[
                    group_idx * second_group_width : (group_idx + 1) * second_group_width, :, :, :
                ]
                bias_slice = first_bias[group_idx * first_group_width : (group_idx + 1) * first_group_width]
                kernels.append(F.conv2d(second_slice, first_slice))  # pylint: disable=not-callable
                biases.append((second_slice * bias_slice.reshape(1, -1, 1, 1)).sum((1, 2, 3)))

            kernel = torch.concat(kernels, dim=0)
            bias = torch.concat(biases)

        return (kernel, bias + second_bias)

    def _average_kernel(self, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
        input_dim = self.out_channels // self.groups
        kernel = torch.zeros(
            (self.out_channels, input_dim, self.kernel_size, self.kernel_size),
            device=device,
            dtype=dtype,
        )
        output_indices = torch.arange(self.out_channels, device=device)
        input_indices = torch.arange(input_dim, device=device).repeat(self.groups)
        kernel[output_indices, input_indices, :, :] = 1.0 / self.kernel_size**2

        return kernel


class ResidualBlock(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        stride: tuple[int, int],
        bottle_neck: bool,
        squeeze_excitation: bool,
        avg_down: bool,
        conv_block: Callable[..., nn.Module],
        reparameterized: bool,
    ) -> None:
        super().__init__()
        if bottle_neck is True:
            self.block1 = nn.Sequential(
                Conv2dNormActivation(
                    in_channels, out_channels // 4, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), bias=False
                ),
                conv_block(
                    out_channels // 4,
                    out_channels // 4,
                    kernel_size=3,
                    stride=stride,
                    padding=1,
                    reparameterized=reparameterized,
                ),
                nn.ReLU(inplace=True),
                nn.Conv2d(
                    out_channels // 4, out_channels, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), bias=False
                ),
                nn.BatchNorm2d(out_channels),
            )
        else:
            self.block1 = nn.Sequential(
                conv_block(
                    in_channels,
                    out_channels,
                    kernel_size=3,
                    stride=stride,
                    padding=1,
                    reparameterized=reparameterized,
                ),
                nn.ReLU(inplace=True),
                conv_block(
                    out_channels,
                    out_channels,
                    kernel_size=3,
                    stride=(1, 1),
                    padding=1,
                    reparameterized=reparameterized,
                ),
            )

        if in_channels == out_channels and stride == (1, 1):
            self.block2 = nn.Identity()
        else:
            if avg_down is True and stride != (1, 1):
                self.block2 = nn.Sequential(
                    nn.AvgPool2d(kernel_size=2, stride=stride, ceil_mode=True, count_include_pad=False),
                    nn.Conv2d(in_channels, out_channels, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), bias=False),
                    nn.BatchNorm2d(out_channels),
                )
            else:
                self.block2 = nn.Sequential(
                    nn.Conv2d(in_channels, out_channels, kernel_size=(1, 1), stride=stride, padding=(0, 0), bias=False),
                    nn.BatchNorm2d(out_channels),
                )

        self.relu = nn.ReLU()
        if squeeze_excitation is True:
            self.se = SqueezeExcitation(out_channels, out_channels // 16)
        else:
            self.se = nn.Identity()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x
        x = self.block1(x)
        x = self.se(x)
        identity = self.block2(identity)
        x += identity
        x = self.relu(x)

        return x


class ACNet(DetectorBackbone, PreTrainEncoder, MaskedTokenRetentionMixin):
    block_group_regex = r"body\.stage(\d+)\.(\d+)"

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"

        self.reparameterized = False
        block_type: Literal["acb", "dbb"] = self.config["block_type"]
        bottle_neck: bool = self.config["bottle_neck"]
        filter_list: list[int] = self.config["filter_list"]
        units: list[int] = self.config["units"]
        squeeze_excitation: bool = self.config.get("squeeze_excitation", False)
        deep_stem: bool = self.config.get("deep_stem", False)
        avg_down: bool = self.config.get("avg_down", False)

        assert len(units) + 1 == len(filter_list)
        num_unit = len(units)

        if block_type == "acb":
            conv_block = AsymmetricConvBlock
        elif block_type == "dbb":
            conv_block = DiverseBranchBlock
        else:
            raise ValueError(f"Unknown block type '{block_type}'")

        if deep_stem is True:
            self.stem = nn.Sequential(
                Conv2dNormActivation(
                    self.input_channels, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False
                ),
                Conv2dNormActivation(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
                Conv2dNormActivation(32, filter_list[0], kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
                nn.MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1)),
            )
        else:
            self.stem = nn.Sequential(
                Conv2dNormActivation(
                    self.input_channels, filter_list[0], kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
                ),
                nn.MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1)),
            )

        stages: OrderedDict[str, nn.Module] = OrderedDict()
        return_channels: list[int] = []
        for i in range(num_unit):
            layers = []
            if i == 0:
                stride = (1, 1)
            else:
                stride = (2, 2)

            layers.append(
                ResidualBlock(
                    filter_list[i],
                    filter_list[i + 1],
                    stride=stride,
                    bottle_neck=bottle_neck,
                    squeeze_excitation=squeeze_excitation,
                    avg_down=avg_down,
                    conv_block=conv_block,
                    reparameterized=self.reparameterized,
                )
            )
            for _ in range(1, units[i]):
                layers.append(
                    ResidualBlock(
                        filter_list[i + 1],
                        filter_list[i + 1],
                        stride=(1, 1),
                        bottle_neck=bottle_neck,
                        squeeze_excitation=squeeze_excitation,
                        avg_down=avg_down,
                        conv_block=conv_block,
                        reparameterized=self.reparameterized,
                    )
                )

            stages[f"stage{i+1}"] = nn.Sequential(*layers)
            return_channels.append(filter_list[i + 1])

        self.body = nn.Sequential(stages)
        self.features = nn.Sequential(
            nn.AdaptiveAvgPool2d(output_size=(1, 1)),
            nn.Flatten(1),
        )
        self.return_channels = return_channels
        self.embedding_size = filter_list[-1]
        self.classifier = self.create_classifier()

        self.max_stride = 32
        self.stem_stride = 4
        self.stem_width = filter_list[0]
        self.feature_dim = filter_list[-1]

    def detection_features(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        x = self.stem(x)

        out = {}
        for name, module in self.body.named_children():
            x = module(x)
            if name in self.return_stages:
                out[name] = x

        return out

    def freeze_stages(self, up_to_stage: int) -> None:
        for param in self.stem.parameters():
            param.requires_grad_(False)

        for idx, module in enumerate(self.body.children()):
            if idx >= up_to_stage:
                break

            for param in module.parameters():
                param.requires_grad_(False)

    def masked_encoding_retention(
        self,
        x: torch.Tensor,
        mask: torch.Tensor,
        mask_token: Optional[torch.Tensor] = None,
        return_keys: Literal["all", "features", "embedding"] = "features",
    ) -> TokenRetentionResultType:
        x = self.stem(x)
        x = mask_tensor(x, mask, patch_factor=self.max_stride // self.stem_stride, mask_token=mask_token)
        x = self.body(x)

        result: TokenRetentionResultType = {}
        if return_keys in ("all", "features"):
            result["features"] = x
        if return_keys in ("all", "embedding"):
            result["embedding"] = self.features(x)

        return result

    def forward_features(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        return self.body(x)

    def embedding_from_features(self, features: torch.Tensor) -> torch.Tensor:
        return self.features(features)

    @torch.no_grad()  # type: ignore[untyped-decorator]
    def reparameterize_model(self) -> None:
        if self.reparameterized is True:
            return

        for module in self.modules():
            if hasattr(module, "reparameterize") is True:
                module.reparameterize()

        self.reparameterized = True


registry.register_model_config(
    "acb_resnet_v1_18",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": False,
        "filter_list": [64, 64, 128, 256, 512],
        "units": [2, 2, 2, 2],
    },
)
registry.register_model_config(
    "acb_resnet_v1_50",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
    },
)
registry.register_model_config(
    "acb_resnet_v1_101",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
    },
)

# ResNet-D variants
registry.register_model_config(
    "acb_resnet_d_50",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
        "deep_stem": True,
        "avg_down": True,
    },
)
registry.register_model_config(
    "acb_resnet_d_101",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
        "deep_stem": True,
        "avg_down": True,
    },
)

# Squeeze-and-Excitation variants
registry.register_model_config(
    "acb_se_resnet_v1_18",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": False,
        "filter_list": [64, 64, 128, 256, 512],
        "units": [2, 2, 2, 2],
        "squeeze_excitation": True,
    },
)
registry.register_model_config(
    "acb_se_resnet_v1_50",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
        "squeeze_excitation": True,
    },
)
registry.register_model_config(
    "acb_se_resnet_v1_101",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
        "squeeze_excitation": True,
    },
)

# SE-ResNet-D variants
registry.register_model_config(
    "acb_se_resnet_d_50",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
        "squeeze_excitation": True,
        "deep_stem": True,
        "avg_down": True,
    },
)
registry.register_model_config(
    "acb_se_resnet_d_101",
    ACNet,
    config={
        "block_type": "acb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
        "squeeze_excitation": True,
        "deep_stem": True,
        "avg_down": True,
    },
)

registry.register_model_config(
    "dbb_resnet_v1_18",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": False,
        "filter_list": [64, 64, 128, 256, 512],
        "units": [2, 2, 2, 2],
    },
)
registry.register_model_config(
    "dbb_resnet_v1_50",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
    },
)
registry.register_model_config(
    "dbb_resnet_v1_101",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
    },
)

# ResNet-D variants
registry.register_model_config(
    "dbb_resnet_d_50",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
        "deep_stem": True,
        "avg_down": True,
    },
)
registry.register_model_config(
    "dbb_resnet_d_101",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
        "deep_stem": True,
        "avg_down": True,
    },
)

# Squeeze-and-Excitation variants
registry.register_model_config(
    "dbb_se_resnet_v1_18",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": False,
        "filter_list": [64, 64, 128, 256, 512],
        "units": [2, 2, 2, 2],
        "squeeze_excitation": True,
    },
)
registry.register_model_config(
    "dbb_se_resnet_v1_50",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
        "squeeze_excitation": True,
    },
)
registry.register_model_config(
    "dbb_se_resnet_v1_101",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
        "squeeze_excitation": True,
    },
)

# SE-ResNet-D variants
registry.register_model_config(
    "dbb_se_resnet_d_50",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 6, 3],
        "squeeze_excitation": True,
        "deep_stem": True,
        "avg_down": True,
    },
)
registry.register_model_config(
    "dbb_se_resnet_d_101",
    ACNet,
    config={
        "block_type": "dbb",
        "bottle_neck": True,
        "filter_list": [64, 256, 512, 1024, 2048],
        "units": [3, 4, 23, 3],
        "squeeze_excitation": True,
        "deep_stem": True,
        "avg_down": True,
    },
)
