"""
CSPNeXt, adapted from
https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/backbones/cspnext.py

Paper "RTMDet: An Empirical Study of Designing Real-Time Object Detectors", https://arxiv.org/abs/2212.07784

Generated by gpt-5.6-sol max.
"""

# Reference license: Apache-2.0

from collections import OrderedDict
from collections.abc import Callable
from functools import partial
from typing import Any
from typing import Optional

import torch
from torch import nn
from torchvision.ops import Conv2dNormActivation

from birder.model_registry import registry
from birder.net.base import DetectorBackbone


class DepthwiseSeparableConv2d(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: tuple[int, int],
        padding: tuple[int, int],
        norm_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        self.depthwise = Conv2dNormActivation(
            in_channels,
            in_channels,
            kernel_size=kernel_size,
            stride=(1, 1),
            padding=padding,
            groups=in_channels,
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )
        self.pointwise = Conv2dNormActivation(
            in_channels,
            out_channels,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.depthwise(x)
        return self.pointwise(x)


class ChannelAttention(nn.Module):
    def __init__(self, channels: int) -> None:
        super().__init__()
        self.pool = nn.AdaptiveAvgPool2d(output_size=(1, 1))
        self.fc = nn.Conv2d(channels, channels, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0))
        self.activation = nn.Hardsigmoid(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        scale = self.pool(x)
        scale = self.fc(scale)
        scale = self.activation(scale)

        return x * scale


class SPPBottleneck(nn.Module):
    def __init__(
        self, in_channels: int, out_channels: int, kernel_sizes: tuple[int, ...], norm_layer: Callable[..., nn.Module]
    ) -> None:
        super().__init__()
        hidden_channels = in_channels // 2
        self.conv1 = Conv2dNormActivation(
            in_channels,
            hidden_channels,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )
        self.pools = nn.ModuleList(
            [nn.MaxPool2d(kernel_size=(k, k), stride=(1, 1), padding=(k // 2, k // 2)) for k in kernel_sizes]
        )
        self.conv2 = Conv2dNormActivation(
            hidden_channels * (len(kernel_sizes) + 1),
            out_channels,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.conv1(x)
        features = [x] + [pool(x) for pool in self.pools]
        x = torch.concat(features, dim=1)

        return self.conv2(x)


class CSPNeXtBlock(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        expansion: float,
        shortcut: bool,
        norm_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        hidden_channels = int(out_channels * expansion)
        self.shortcut = shortcut is True and in_channels == out_channels

        self.conv1 = Conv2dNormActivation(
            in_channels,
            hidden_channels,
            kernel_size=(3, 3),
            stride=(1, 1),
            padding=(1, 1),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )
        self.conv2 = DepthwiseSeparableConv2d(
            hidden_channels, out_channels, kernel_size=(5, 5), padding=(2, 2), norm_layer=norm_layer
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x
        x = self.conv1(x)
        x = self.conv2(x)
        if self.shortcut is True:
            x = x + identity

        return x


class CSPNeXtLayer(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        depth: int,
        shortcut: bool,
        expansion: float,
        channel_attention: bool,
        norm_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        hidden_channels = int(out_channels * expansion)
        self.main_conv = Conv2dNormActivation(
            in_channels,
            hidden_channels,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )
        self.shortcut_conv = Conv2dNormActivation(
            in_channels,
            hidden_channels,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )
        self.blocks = nn.Sequential(
            *[
                CSPNeXtBlock(
                    hidden_channels,
                    hidden_channels,
                    expansion=1.0,
                    shortcut=shortcut,
                    norm_layer=norm_layer,
                )
                for _ in range(depth)
            ]
        )
        if channel_attention is True:
            self.attention = ChannelAttention(2 * hidden_channels)
        else:
            self.attention = nn.Identity()

        self.final_conv = Conv2dNormActivation(
            2 * hidden_channels,
            out_channels,
            kernel_size=(1, 1),
            stride=(1, 1),
            padding=(0, 0),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        main = self.main_conv(x)
        main = self.blocks(main)
        shortcut = self.shortcut_conv(x)
        x = torch.concat([main, shortcut], dim=1)
        x = self.attention(x)

        return self.final_conv(x)


class CSPNeXtStage(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        depth: int,
        shortcut: bool,
        use_spp: bool,
        norm_layer: Callable[..., nn.Module],
    ) -> None:
        super().__init__()
        self.downsample = Conv2dNormActivation(
            in_channels,
            out_channels,
            kernel_size=(3, 3),
            stride=(2, 2),
            padding=(1, 1),
            norm_layer=norm_layer,
            activation_layer=nn.SiLU,
        )
        if use_spp is True:
            self.spp: nn.Module = SPPBottleneck(
                out_channels, out_channels, kernel_sizes=(5, 9, 13), norm_layer=norm_layer
            )
        else:
            self.spp = nn.Identity()

        self.csp_layer = CSPNeXtLayer(
            out_channels,
            out_channels,
            depth=depth,
            shortcut=shortcut,
            expansion=0.5,
            channel_attention=True,
            norm_layer=norm_layer,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.downsample(x)
        x = self.spp(x)
        return self.csp_layer(x)


class CSPNeXt(DetectorBackbone):
    block_group_regex = r"body\.stage(\d+)\.csp_layer\.blocks\.(\d+)"

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"

        channels: list[int] = self.config["channels"]
        depths: list[int] = self.config["depths"]
        norm_layer = partial(nn.BatchNorm2d, eps=0.001, momentum=0.03)

        self.stem = nn.Sequential(
            Conv2dNormActivation(
                self.input_channels,
                channels[0] // 2,
                kernel_size=(3, 3),
                stride=(2, 2),
                padding=(1, 1),
                norm_layer=norm_layer,
                activation_layer=nn.SiLU,
            ),
            Conv2dNormActivation(
                channels[0] // 2,
                channels[0] // 2,
                kernel_size=(3, 3),
                stride=(1, 1),
                padding=(1, 1),
                norm_layer=norm_layer,
                activation_layer=nn.SiLU,
            ),
            Conv2dNormActivation(
                channels[0] // 2,
                channels[0],
                kernel_size=(3, 3),
                stride=(1, 1),
                padding=(1, 1),
                norm_layer=norm_layer,
                activation_layer=nn.SiLU,
            ),
        )

        stages: OrderedDict[str, nn.Module] = OrderedDict()
        return_channels: list[int] = []
        num_stages = len(depths)
        for idx, depth in enumerate(depths):
            stages[f"stage{idx+1}"] = CSPNeXtStage(
                channels[idx],
                channels[idx + 1],
                depth=depth,
                shortcut=idx < num_stages - 1,
                use_spp=idx == num_stages - 1,
                norm_layer=norm_layer,
            )
            return_channels.append(channels[idx + 1])

        self.body = nn.Sequential(stages)
        self.features = nn.Sequential(
            nn.AdaptiveAvgPool2d(output_size=(1, 1)),
            nn.Flatten(1),
        )
        self.return_channels = return_channels
        self.embedding_size = channels[-1]
        self.classifier = self.create_classifier()

        self.max_stride = 2 ** (num_stages + 1)
        self.stem_stride = 2
        self.stem_width = channels[0]
        self.feature_dim = channels[-1]

    def detection_features(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        x = self.stem(x)

        out = {}
        for name, module in self.body.named_children():
            x = module(x)
            if name in self.return_stages:
                out[name] = x

        return out

    def freeze_stages(self, up_to_stage: int) -> None:
        for param in self.stem.parameters():
            param.requires_grad_(False)

        for idx, module in enumerate(self.body.children()):
            if idx >= up_to_stage:
                break

            for param in module.parameters():
                param.requires_grad_(False)

    def forward_features(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        return self.body(x)

    def embedding_from_features(self, features: torch.Tensor) -> torch.Tensor:
        return self.features(features)


registry.register_model_config(
    "cspnext_t",
    CSPNeXt,
    config={"channels": [24, 48, 96, 192, 384], "depths": [1, 1, 1, 1]},
)
registry.register_model_config(
    "cspnext_s",
    CSPNeXt,
    config={"channels": [32, 64, 128, 256, 512], "depths": [1, 2, 2, 1]},
)
registry.register_model_config(
    "cspnext_m",
    CSPNeXt,
    config={"channels": [48, 96, 192, 384, 768], "depths": [2, 4, 4, 2]},
)
registry.register_model_config(
    "cspnext_l",
    CSPNeXt,
    config={"channels": [64, 128, 256, 512, 1024], "depths": [3, 6, 6, 3]},
)
registry.register_model_config(
    "cspnext_xl",
    CSPNeXt,
    config={"channels": [80, 160, 320, 640, 1280], "depths": [4, 8, 8, 4]},
)
