"""
MambaOut, adapted from
https://github.com/yuweihao/MambaOut/blob/main/models/mambaout.py
and
https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/mambaout.py

Paper "MambaOut: Do We Really Need Mamba for Vision?", https://arxiv.org/abs/2405.07992

Generated by gpt-5.6-sol max.
"""

# Reference license: Apache-2.0 (both)

from collections import OrderedDict
from typing import Any
from typing import Literal
from typing import Optional

import torch
from torch import nn
from torchvision.ops import StochasticDepth

from birder.common.masking import mask_tensor
from birder.layers import LayerNorm2d
from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.base import MaskedTokenRetentionMixin
from birder.net.base import PreTrainEncoder
from birder.net.base import TokenRetentionResultType
from birder.net.base import staged_stochastic_depth_rates


class Stem(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels // 2, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.norm1 = LayerNorm2d(out_channels // 2, eps=1e-6)
        self.act = nn.GELU()
        self.conv2 = nn.Conv2d(out_channels // 2, out_channels, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.norm2 = nn.LayerNorm(out_channels, eps=1e-6)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.conv1(x)
        x = self.norm1(x)
        x = self.act(x)
        x = self.conv2(x)
        x = x.permute(0, 2, 3, 1)
        x = self.norm2(x)

        return x


class Downsample(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.norm = nn.LayerNorm(out_channels, eps=1e-6)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.permute(0, 3, 1, 2)
        x = self.conv(x)
        x = x.permute(0, 2, 3, 1)
        x = self.norm(x)

        return x


class GatedCNNBlock(nn.Module):
    def __init__(self, dim: int, expansion_ratio: float, kernel_size: int, conv_ratio: float, drop_path: float) -> None:
        super().__init__()
        hidden_dim = int(expansion_ratio * dim)
        conv_channels = int(conv_ratio * dim)

        self.split_indices = (hidden_dim, hidden_dim - conv_channels, conv_channels)
        self.norm = nn.LayerNorm(dim, eps=1e-6)
        self.fc1 = nn.Linear(dim, hidden_dim * 2)
        self.act = nn.GELU()
        self.conv = nn.Conv2d(
            conv_channels,
            conv_channels,
            kernel_size=(kernel_size, kernel_size),
            stride=(1, 1),
            padding=(kernel_size // 2, kernel_size // 2),
            groups=conv_channels,
        )
        self.fc2 = nn.Linear(hidden_dim, dim)
        self.drop_path = StochasticDepth(drop_path, mode="row")

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x
        x = self.norm(x)
        gate, identity_branch, conv_branch = torch.split(self.fc1(x), self.split_indices, dim=-1)
        conv_branch = conv_branch.permute(0, 3, 1, 2)
        conv_branch = self.conv(conv_branch)
        conv_branch = conv_branch.permute(0, 2, 3, 1)
        x = self.fc2(self.act(gate) * torch.concat((identity_branch, conv_branch), dim=-1))
        x = self.drop_path(x)

        return x + identity


class MambaOutStage(nn.Module):
    def __init__(
        self,
        in_dim: int,
        out_dim: int,
        depth: int,
        expansion_ratio: float,
        kernel_size: int,
        conv_ratio: float,
        drop_path_rates: list[float],
        downsample: bool,
    ) -> None:
        super().__init__()
        if downsample is True:
            self.downsample = Downsample(in_dim, out_dim)
        else:
            assert in_dim == out_dim
            self.downsample = nn.Identity()

        self.blocks = nn.Sequential(
            *[
                GatedCNNBlock(
                    dim=out_dim,
                    expansion_ratio=expansion_ratio,
                    kernel_size=kernel_size,
                    conv_ratio=conv_ratio,
                    drop_path=drop_path_rates[i],
                )
                for i in range(depth)
            ]
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.downsample(x)
        x = self.blocks(x)

        return x


class MambaOut(DetectorBackbone, PreTrainEncoder, MaskedTokenRetentionMixin):
    block_group_regex = r"body\.stage(\d+)\.blocks\.(\d+)"

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"
        assert "mlp_head" not in self.config, "mlp_head customization is not supported"

        expansion_ratio = 8 / 3
        kernel_size = 7
        conv_ratio = 1.0
        self.head_dropout: float = self.config.get("head_dropout", 0.0)
        dims: list[int] = self.config["dims"]
        depths: list[int] = self.config["depths"]
        drop_path_rate: float = self.config["drop_path_rate"]

        self.stem = Stem(self.input_channels, dims[0])

        num_stages = len(depths)
        dpr = staged_stochastic_depth_rates(drop_path_rate, depths)
        prev_dim = dims[0]
        stages: OrderedDict[str, nn.Module] = OrderedDict()
        return_channels: list[int] = []
        for i in range(num_stages):
            stages[f"stage{i+1}"] = MambaOutStage(
                prev_dim,
                dims[i],
                depth=depths[i],
                expansion_ratio=expansion_ratio,
                kernel_size=kernel_size,
                conv_ratio=conv_ratio,
                drop_path_rates=dpr[i],
                downsample=i > 0,
            )
            return_channels.append(dims[i])
            prev_dim = dims[i]

        self.body = nn.Sequential(stages)
        self.features = nn.Sequential(
            nn.AdaptiveAvgPool2d(output_size=(1, 1)),
            nn.Flatten(1),
            nn.LayerNorm(dims[-1], eps=1e-6),
        )
        self.return_channels = return_channels
        self.embedding_size = dims[-1]
        self.classifier = self.create_classifier()

        self.max_stride = 4 * 2 ** (num_stages - 1)
        self.stem_stride = 4
        self.stem_width = dims[0]
        self.feature_dim = dims[-1]

        # Weight initialization
        for module in self.modules():
            if isinstance(module, (nn.Conv2d, nn.Linear)):
                nn.init.trunc_normal_(module.weight, std=0.02)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)

    def detection_features(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        x = self.stem(x)

        out = {}
        for name, module in self.body.named_children():
            x = module(x)
            if name in self.return_stages:
                out[name] = x.permute(0, 3, 1, 2).contiguous()

        return out

    def freeze_stages(self, up_to_stage: int) -> None:
        for param in self.stem.parameters():
            param.requires_grad_(False)

        for idx, module in enumerate(self.body.children()):
            if idx >= up_to_stage:
                break

            for param in module.parameters():
                param.requires_grad_(False)

    def masked_encoding_retention(
        self,
        x: torch.Tensor,
        mask: torch.Tensor,
        mask_token: Optional[torch.Tensor] = None,
        return_keys: Literal["all", "features", "embedding"] = "features",
    ) -> TokenRetentionResultType:
        x = self.stem(x)
        x = mask_tensor(
            x,
            mask,
            channels_last=True,
            patch_factor=self.max_stride // self.stem_stride,
            mask_token=mask_token,
        )
        x = self.body(x)
        x = x.permute(0, 3, 1, 2).contiguous()
        result: TokenRetentionResultType = {}
        if return_keys in ("all", "features"):
            result["features"] = x
        if return_keys in ("all", "embedding"):
            result["embedding"] = self.features(x)

        return result

    def forward_features(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        x = self.body(x)
        return x.permute(0, 3, 1, 2).contiguous()

    def embedding_from_features(self, features: torch.Tensor) -> torch.Tensor:
        return self.features(features)

    def create_classifier(
        self, embed_dim: Optional[int] = None, head_bias: Optional[bool] = None, mlp_head: Optional[bool] = None
    ) -> nn.Module:
        assert mlp_head is None, "mlp_head customization is not supported"

        if self.num_classes == 0:
            return nn.Identity()

        if embed_dim is None:
            embed_dim = self.embedding_size
        if head_bias is None:
            head_bias = self.head_bias

        hidden_dim = 4 * embed_dim
        return nn.Sequential(
            nn.Linear(embed_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim, eps=1e-6),
            nn.Dropout(self.head_dropout),
            nn.Linear(hidden_dim, self.num_classes, bias=head_bias),
        )


registry.register_model_config(
    "mambaout_femto",
    MambaOut,
    config={"depths": [3, 3, 9, 3], "dims": [48, 96, 192, 288], "drop_path_rate": 0.025},
)
registry.register_model_config(
    "mambaout_kobe",
    MambaOut,
    config={"depths": [3, 3, 15, 3], "dims": [48, 96, 192, 288], "drop_path_rate": 0.025},
)
registry.register_model_config(
    "mambaout_tiny",
    MambaOut,
    config={"depths": [3, 3, 9, 3], "dims": [96, 192, 384, 576], "drop_path_rate": 0.2},
)
registry.register_model_config(
    "mambaout_small",
    MambaOut,
    config={"depths": [3, 4, 27, 3], "dims": [96, 192, 384, 576], "drop_path_rate": 0.4},
)
registry.register_model_config(
    "mambaout_base",
    MambaOut,
    config={"depths": [3, 4, 27, 3], "dims": [128, 256, 512, 768], "drop_path_rate": 0.6},
)
