"""
MicroViT v1, adapted from
https://github.com/novendrastywn/MicroViT/blob/main/model/microvit.py

Paper "MicroViT: A Vision Transformer with Low Complexity Self Attention for Edge Device",
https://arxiv.org/abs/2502.05800

Changes from original:
* Fixed residual reparameterization condition to fuse Conv2dBN residuals
* Added padding at the stem convolutions for regular power-of-two spatial reductions

Generated by gpt-5.5 high.
"""

# Reference license: MIT

from collections import OrderedDict
from collections.abc import Callable
from typing import Any
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn

from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.shvit import Conv2dBN
from birder.net.shvit import NormLinear


class Residual(nn.Module):
    def __init__(self, module: nn.Module, reparameterized: bool = False) -> None:
        super().__init__()
        self.m = module
        self.reparameterized = reparameterized and isinstance(module, Conv2dBN)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.reparameterized is True:
            return self.m(x)

        return x + self.m(x)

    def reparameterize(self) -> None:
        if self.reparameterized is True:
            return

        if hasattr(self.m, "reparameterize") is True:
            reparameterized_module = self.m.reparameterize()
            if isinstance(reparameterized_module, nn.Module):
                self.m = reparameterized_module

        if isinstance(self.m, Conv2dBN):
            conv = self.m.c
            assert isinstance(conv, nn.Conv2d)
        elif isinstance(self.m, nn.Conv2d):
            conv = self.m
        else:
            return

        if isinstance(conv, nn.Conv2d):
            assert conv.groups == conv.in_channels
            assert conv.in_channels == conv.out_channels

            identity = torch.ones(
                conv.weight.shape[0], conv.weight.shape[1], 1, 1, device=conv.weight.device, dtype=conv.weight.dtype
            )
            identity = F.pad(
                identity,
                [
                    conv.kernel_size[1] // 2,
                    conv.kernel_size[1] // 2,
                    conv.kernel_size[0] // 2,
                    conv.kernel_size[0] // 2,
                ],
            )
            conv.weight.data.add_(identity)

            # Delete un-used branches
            for param in self.parameters():
                param.detach_()

            self.m = conv
            self.reparameterized = True


class FFN(nn.Module):
    def __init__(
        self, dim: int, hidden_dim: int, reparameterized: bool, act_layer: Callable[..., nn.Module] = nn.GELU
    ) -> None:
        super().__init__()
        self.pw1 = Conv2dBN(
            dim, hidden_dim, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), reparameterized=reparameterized
        )
        self.act = act_layer()
        self.pw2 = Conv2dBN(
            hidden_dim, dim, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), reparameterized=reparameterized
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.pw1(x)
        x = self.act(x)
        x = self.pw2(x)

        return x


class Stem(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, reparameterized: bool) -> None:
        super().__init__()
        blocks = 4
        dims = [in_channels] + [out_channels // 2**idx for idx in range(blocks - 1, -1, -1)]
        layers = []
        for idx in range(blocks):
            layers.append(
                nn.Sequential(
                    Conv2dBN(
                        dims[idx],
                        dims[idx + 1],
                        kernel_size=(3, 3),
                        stride=(2, 2),
                        padding=(1, 1),
                        reparameterized=reparameterized,
                    ),
                    nn.GELU(),
                )
            )

        self.block = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class ESHA(nn.Module):
    """
    Efficient Single Head Attention
    """

    def __init__(self, dim: int, reparameterized: bool) -> None:
        super().__init__()
        qk_dim = 16
        partial_dim = int(dim * 0.215)
        self.scale = qk_dim**-0.5
        self.partial_dim = partial_dim
        self.split_index = (qk_dim, qk_dim, partial_dim, dim - partial_dim)
        self.pre_norm = nn.GroupNorm(1, dim)
        self.in_proj = Conv2dBN(
            dim,
            qk_dim * 2 + dim,
            kernel_size=(3, 3),
            stride=(1, 1),
            padding=(1, 1),
            groups=32,
            reparameterized=reparameterized,
        )

        self.out_proj = nn.Sequential(
            nn.ReLU(),
            Conv2dBN(dim, dim, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), reparameterized=reparameterized),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.pre_norm(x)
        q, k, v, untouched = self.in_proj(x).split(self.split_index, dim=1)
        q = q.flatten(2)
        k = k.flatten(2)
        v = v.flatten(2)

        attn = (q.transpose(-2, -1) @ k) * self.scale
        attn = attn.softmax(dim=-1)
        b, _, h, w = untouched.shape
        attn = (v @ attn.transpose(-2, -1)).reshape(b, self.partial_dim, h, w)
        x = self.out_proj(torch.concat((attn, untouched), dim=1))

        return x


class PatchMerging(nn.Module):
    def __init__(self, in_dim: int, out_dim: int, reparameterized: bool) -> None:
        super().__init__()
        self.token_mix = nn.Sequential(
            Conv2dBN(
                in_dim,
                in_dim,
                kernel_size=(3, 3),
                stride=(2, 2),
                padding=(1, 1),
                groups=in_dim,
                reparameterized=reparameterized,
            ),
            nn.GELU(),
            Conv2dBN(
                in_dim, out_dim, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), reparameterized=reparameterized
            ),
        )
        self.channel_mix = Residual(
            nn.Sequential(
                Conv2dBN(
                    out_dim,
                    out_dim * 2,
                    kernel_size=(1, 1),
                    stride=(1, 1),
                    padding=(0, 0),
                    reparameterized=reparameterized,
                ),
                nn.GELU(),
                Conv2dBN(
                    out_dim * 2,
                    out_dim,
                    kernel_size=(1, 1),
                    stride=(1, 1),
                    padding=(0, 0),
                    reparameterized=reparameterized,
                ),
            ),
            reparameterized=reparameterized,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.token_mix(x)
        x = self.channel_mix(x)

        return x


class MicroViTBlock(nn.Module):
    def __init__(self, dim: int, use_attention: bool, reparameterized: bool) -> None:
        super().__init__()
        hidden_dim = int(dim * 2)

        if use_attention is True:
            spatial_mix: nn.Module = ESHA(dim, reparameterized=reparameterized)
        else:
            spatial_mix = Conv2dBN(
                dim,
                dim,
                kernel_size=(3, 3),
                stride=(1, 1),
                padding=(1, 1),
                groups=dim,
                reparameterized=reparameterized,
            )

        self.block = nn.Sequential(
            Residual(spatial_mix, reparameterized=reparameterized),
            Residual(FFN(dim, hidden_dim, reparameterized), reparameterized=reparameterized),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class MicroViTStage(nn.Module):
    def __init__(
        self,
        prev_dim: int,
        dim: int,
        depth: int,
        use_attention: bool,
        reparameterized: bool,
    ) -> None:
        super().__init__()
        if prev_dim != dim:
            self.downsample = nn.Sequential(
                PatchMerging(prev_dim, dim, reparameterized),
                Residual(
                    Conv2dBN(
                        dim,
                        dim,
                        kernel_size=(3, 3),
                        stride=(1, 1),
                        padding=(1, 1),
                        groups=dim,
                        reparameterized=reparameterized,
                    ),
                    reparameterized=reparameterized,
                ),
                Residual(FFN(dim, dim * 2, reparameterized), reparameterized=reparameterized),
            )
        else:
            self.downsample = nn.Identity()

        self.blocks = nn.Sequential(
            *[
                MicroViTBlock(
                    dim,
                    use_attention=use_attention,
                    reparameterized=reparameterized,
                )
                for _ in range(depth)
            ]
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.downsample(x)
        x = self.blocks(x)

        return x


class MicroViT_v1(DetectorBackbone):
    block_group_regex = r"body\.stage(\d+)\.blocks\.(\d+)"

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"
        assert "head_bias" not in self.config, "head_bias customization is not supported"
        assert "mlp_head" not in self.config, "mlp_head customization is not supported"

        self.reparameterized = False
        embed_dims: list[int] = self.config["embed_dims"]
        depths: list[int] = self.config["depths"]

        self.stem = Stem(self.input_channels, embed_dims[0], reparameterized=self.reparameterized)

        stages: OrderedDict[str, nn.Module] = OrderedDict()
        return_channels: list[int] = []
        prev_dim = embed_dims[0]
        for idx, dim in enumerate(embed_dims):
            stages[f"stage{idx + 1}"] = MicroViTStage(
                prev_dim=prev_dim,
                dim=dim,
                depth=depths[idx],
                use_attention=idx == len(embed_dims) - 1,
                reparameterized=self.reparameterized,
            )
            return_channels.append(dim)
            prev_dim = dim

        self.body = nn.Sequential(stages)
        self.features = nn.Sequential(
            nn.AdaptiveAvgPool2d(output_size=(1, 1)),
            nn.Flatten(1),
        )
        self.return_stages = self.return_stages[: len(depths)]
        self.return_channels = return_channels
        self.embedding_size = embed_dims[-1]
        self.dist_classifier = self.create_classifier()
        self.classifier = self.create_classifier()
        self.distillation_output = False

        # Weights initialization
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, (nn.Conv1d, nn.Conv2d)):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, (nn.LayerNorm, nn.GroupNorm)):
                nn.init.zeros_(m.bias)
                nn.init.ones_(m.weight)

    def reset_classifier(self, num_classes: int) -> None:
        self.num_classes = num_classes
        self.dist_classifier = self.create_classifier()
        self.classifier = self.create_classifier()

    def freeze(self, freeze_classifier: bool = True, unfreeze_features: bool = False) -> None:
        for param in self.parameters():
            param.requires_grad_(False)

        if freeze_classifier is False:
            for param in self.classifier.parameters():
                param.requires_grad_(True)

            for param in self.dist_classifier.parameters():
                param.requires_grad_(True)

        if unfreeze_features is True:
            for param in self.features.parameters():
                param.requires_grad_(True)

    def transform_to_backbone(self) -> None:
        self.features = nn.Identity()
        self.classifier = nn.Identity()
        self.dist_classifier = nn.Identity()

    def detection_features(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        x = self.stem(x)

        out = {}
        for name, module in self.body.named_children():
            x = module(x)
            if name in self.return_stages:
                out[name] = x

        return out

    def freeze_stages(self, up_to_stage: int) -> None:
        for param in self.stem.parameters():
            param.requires_grad_(False)

        for idx, module in enumerate(self.body.children()):
            if idx >= up_to_stage:
                break

            for param in module.parameters():
                param.requires_grad_(False)

    def forward_features(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        return self.body(x)

    def embedding(self, x: torch.Tensor) -> torch.Tensor:
        x = self.forward_features(x)
        return self.features(x)

    def create_classifier(
        self, embed_dim: Optional[int] = None, head_bias: Optional[bool] = None, mlp_head: Optional[bool] = None
    ) -> nn.Module:
        assert head_bias is None, "head_bias customization is not supported"
        assert mlp_head is None, "mlp_head customization is not supported"

        if self.num_classes == 0:
            return nn.Identity()

        if embed_dim is None:
            embed_dim = self.embedding_size

        return NormLinear(embed_dim, self.num_classes, self.reparameterized)

    def set_distillation_output(self, enable: bool = True) -> None:
        self.distillation_output = enable

    def classify(self, x: torch.Tensor) -> torch.Tensor:
        x_cls = self.classifier(x)
        x_dist = self.dist_classifier(x)

        if self.training is True and self.distillation_output is True:
            x = torch.stack([x_cls, x_dist], dim=1)
        else:
            x = (x_cls + x_dist) / 2

        return x

    @torch.no_grad()  # type: ignore[untyped-decorator]
    def reparameterize_model(self) -> None:
        for module in self.modules():
            if hasattr(module, "reparameterize") is True:
                module.reparameterize()

        self.reparameterized = True


registry.register_model_config(
    "microvit_v1_s1", MicroViT_v1, config={"embed_dims": [128, 256, 320], "depths": [2, 5, 5]}
)
registry.register_model_config(
    "microvit_v1_s2", MicroViT_v1, config={"embed_dims": [128, 320, 448], "depths": [2, 7, 5]}
)
registry.register_model_config(
    "microvit_v1_s3", MicroViT_v1, config={"embed_dims": [192, 384, 512], "depths": [3, 7, 6]}
)

registry.register_weights(
    "microvit_v1_s1_il-common",
    {
        "description": "MicroViT v1 S1 model trained on the il-common dataset",
        "resolution": (256, 256),
        "formats": {
            "pt": {
                "file_size": 23.3,
                "sha256": "84386b2d09f8c8b68ddd0df4beb23f1c3486efc3399e22f7d4034b0dbe688ae6",
            }
        },
        "net": {"network": "microvit_v1_s1", "tag": "il-common"},
    },
)
