"""
MicroViT v2, adapted from
https://github.com/novendrastywn/MicroViT/blob/main/model/microvitv2.py

Paper "MicroViTv2: Beyond the FLOPS for Edge Energy-Friendly Vision Transformers",
https://arxiv.org/abs/2605.10148

Generated by gpt-5.5 high.
"""

# Reference license: MIT

from collections import OrderedDict
from typing import Any
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn

from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.microvit_v1 import FFN
from birder.net.microvit_v1 import Residual
from birder.net.shvit import Conv2dBN
from birder.net.shvit import NormLinear


class RepConv(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int,
        padding: int,
        groups: int = 1,
        reparameterized: bool = False,
    ) -> None:
        super().__init__()
        self.reparameterized = reparameterized
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.groups = groups

        if reparameterized is True:
            self.reparam_conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size, kernel_size),
                stride=(stride, stride),
                padding=(padding, padding),
                groups=groups,
            )
        else:
            self.reparam_conv = None
            self.conv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size, kernel_size),
                stride=(stride, stride),
                padding=(padding, padding),
                groups=groups,
            )
            self.repconv = nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(kernel_size // 2, kernel_size // 2),
                stride=(stride, stride),
                padding=(padding // 2, padding // 2),
                groups=groups,
            )
            self.bn = nn.BatchNorm2d(out_channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.reparam_conv is not None:
            return self.reparam_conv(x)

        x = self.conv(x) + self.repconv(x)
        x = self.bn(x)

        return x

    def reparameterize(self) -> nn.Conv2d:
        if self.reparameterized is True:
            assert self.reparam_conv is not None
            return self.reparam_conv

        repconv_w = F.pad(
            self.repconv.weight,
            [
                (self.conv.weight.shape[3] - self.repconv.weight.shape[3]) // 2,
                (self.conv.weight.shape[3] - self.repconv.weight.shape[3]) // 2,
                (self.conv.weight.shape[2] - self.repconv.weight.shape[2]) // 2,
                (self.conv.weight.shape[2] - self.repconv.weight.shape[2]) // 2,
            ],
        )
        conv_w = self.conv.weight + repconv_w
        conv_b = self.conv.bias + self.repconv.bias

        w = self.bn.weight / (self.bn.running_var + self.bn.eps).sqrt()
        w = conv_w * w[:, None, None, None]
        b = self.bn.bias + (conv_b - self.bn.running_mean) * self.bn.weight / (self.bn.running_var + self.bn.eps).sqrt()

        self.reparam_conv = nn.Conv2d(
            self.in_channels,
            self.out_channels,
            kernel_size=(self.kernel_size, self.kernel_size),
            stride=(self.stride, self.stride),
            padding=(self.padding, self.padding),
            groups=self.groups,
            device=self.conv.weight.device,
            dtype=self.conv.weight.dtype,
        )
        self.reparam_conv.weight.data.copy_(w)
        self.reparam_conv.bias.data.copy_(b)

        # Delete un-used branches
        for param in self.parameters():
            param.detach_()

        del self.conv
        del self.repconv
        del self.bn
        self.reparameterized = True

        return self.reparam_conv


class Stem(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, reparameterized: bool) -> None:
        super().__init__()
        dims = [in_channels, out_channels // 8, out_channels // 4, out_channels // 2, out_channels]
        layers = []
        for idx in range(4):
            layers.append(
                RepConv(dims[idx], dims[idx + 1], kernel_size=3, stride=2, padding=1, reparameterized=reparameterized)
            )
            if idx < 3:
                layers.append(nn.SiLU())

        self.block = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class SDTA(nn.Module):
    """
    Single Depth-Wise Transposed Attention
    """

    def __init__(self, dim: int, reparameterized: bool) -> None:
        super().__init__()
        qk_dim = 16
        partial_dim = dim // 4
        self.scale = qk_dim**-0.5
        self.partial_dim = partial_dim
        self.split_index = (qk_dim, qk_dim, partial_dim, dim - partial_dim)
        self.pre_norm = nn.GroupNorm(1, dim)
        self.in_proj = nn.Sequential(
            RepConv(dim, dim, kernel_size=3, stride=1, padding=1, groups=dim, reparameterized=reparameterized),
            Conv2dBN(
                dim,
                qk_dim * 2 + dim,
                kernel_size=(1, 1),
                stride=(1, 1),
                padding=(0, 0),
                reparameterized=reparameterized,
            ),
        )
        self.out_proj = nn.Sequential(
            nn.GELU(),
            Conv2dBN(dim, dim, kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), reparameterized=reparameterized),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.pre_norm(x)
        q, k, v, untouched = self.in_proj(x).split(self.split_index, dim=1)
        q = q.flatten(2)
        k = k.flatten(2)
        v = v.flatten(2)

        attn = (q.transpose(-2, -1) @ k) * self.scale
        attn = attn.softmax(dim=-1)
        b, _, h, w = untouched.shape
        attn = (v @ attn.transpose(-2, -1)).reshape(b, self.partial_dim, h, w)
        x = self.out_proj(torch.concat((attn, untouched), dim=1))

        return x


class MicroViTBlock(nn.Module):
    def __init__(self, dim: int, use_attention: bool, reparameterized: bool) -> None:
        super().__init__()
        hidden_dim = int(dim * 2)

        if use_attention is True:
            spatial_mix: nn.Module = SDTA(dim, reparameterized=reparameterized)
        else:
            spatial_mix = RepConv(
                dim, dim, kernel_size=3, stride=1, padding=1, groups=dim, reparameterized=reparameterized
            )

        self.block = nn.Sequential(
            Residual(spatial_mix, reparameterized=reparameterized),
            Residual(FFN(dim, hidden_dim, reparameterized, act_layer=nn.SiLU), reparameterized=reparameterized),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class MicroViTStage(nn.Module):
    def __init__(self, prev_dim: int, dim: int, depth: int, use_attention: bool, reparameterized: bool) -> None:
        super().__init__()
        if prev_dim != dim:
            self.downsample = nn.Sequential(
                Residual(
                    RepConv(
                        prev_dim,
                        prev_dim,
                        kernel_size=3,
                        stride=1,
                        padding=1,
                        groups=prev_dim,
                        reparameterized=reparameterized,
                    ),
                    reparameterized=reparameterized,
                ),
                Residual(FFN(prev_dim, prev_dim * 2, reparameterized, act_layer=nn.SiLU), reparameterized),
                RepConv(prev_dim, dim, kernel_size=3, stride=2, padding=1, reparameterized=reparameterized),
                Residual(
                    RepConv(dim, dim, kernel_size=3, stride=1, padding=1, groups=dim, reparameterized=reparameterized),
                    reparameterized=reparameterized,
                ),
                Residual(FFN(dim, dim * 2, reparameterized, act_layer=nn.SiLU), reparameterized),
            )
        else:
            self.downsample = nn.Identity()

        self.blocks = nn.Sequential(
            *[MicroViTBlock(dim, use_attention=use_attention, reparameterized=reparameterized) for _ in range(depth)]
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.downsample(x)
        x = self.blocks(x)

        return x


class MicroViT_v2(DetectorBackbone):
    block_group_regex = r"body\.stage(\d+)\.blocks\.(\d+)"

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"
        assert "head_bias" not in self.config, "head_bias customization is not supported"
        assert "mlp_head" not in self.config, "mlp_head customization is not supported"

        self.reparameterized = False
        embed_dims: list[int] = self.config["embed_dims"]
        depths: list[int] = self.config["depths"]

        self.stem = Stem(self.input_channels, embed_dims[0], reparameterized=self.reparameterized)

        stages: OrderedDict[str, nn.Module] = OrderedDict()
        return_channels: list[int] = []
        prev_dim = embed_dims[0]
        for idx, dim in enumerate(embed_dims):
            stages[f"stage{idx + 1}"] = MicroViTStage(
                prev_dim=prev_dim,
                dim=dim,
                depth=depths[idx],
                use_attention=idx == len(embed_dims) - 1,
                reparameterized=self.reparameterized,
            )
            return_channels.append(dim)
            prev_dim = dim

        self.body = nn.Sequential(stages)
        self.features = nn.Sequential(
            nn.AdaptiveAvgPool2d(output_size=(1, 1)),
            nn.Flatten(1),
        )
        self.return_stages = self.return_stages[: len(depths)]
        self.return_channels = return_channels
        self.embedding_size = embed_dims[-1]
        self.dist_classifier = self.create_classifier()
        self.classifier = self.create_classifier()
        self.distillation_output = False

        # Weights initialization
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, (nn.Conv1d, nn.Conv2d)):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, (nn.LayerNorm, nn.GroupNorm)):
                nn.init.zeros_(m.bias)
                nn.init.ones_(m.weight)

    def reset_classifier(self, num_classes: int) -> None:
        self.num_classes = num_classes
        self.dist_classifier = self.create_classifier()
        self.classifier = self.create_classifier()

    def freeze(self, freeze_classifier: bool = True, unfreeze_features: bool = False) -> None:
        for param in self.parameters():
            param.requires_grad_(False)

        if freeze_classifier is False:
            for param in self.classifier.parameters():
                param.requires_grad_(True)

            for param in self.dist_classifier.parameters():
                param.requires_grad_(True)

        if unfreeze_features is True:
            for param in self.features.parameters():
                param.requires_grad_(True)

    def transform_to_backbone(self) -> None:
        self.features = nn.Identity()
        self.classifier = nn.Identity()
        self.dist_classifier = nn.Identity()

    def detection_features(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        x = self.stem(x)

        out = {}
        for name, module in self.body.named_children():
            x = module(x)
            if name in self.return_stages:
                out[name] = x

        return out

    def freeze_stages(self, up_to_stage: int) -> None:
        for param in self.stem.parameters():
            param.requires_grad_(False)

        for idx, module in enumerate(self.body.children()):
            if idx >= up_to_stage:
                break

            for param in module.parameters():
                param.requires_grad_(False)

    def forward_features(self, x: torch.Tensor) -> torch.Tensor:
        x = self.stem(x)
        return self.body(x)

    def embedding(self, x: torch.Tensor) -> torch.Tensor:
        x = self.forward_features(x)
        return self.features(x)

    def create_classifier(
        self, embed_dim: Optional[int] = None, head_bias: Optional[bool] = None, mlp_head: Optional[bool] = None
    ) -> nn.Module:
        assert head_bias is None, "head_bias customization is not supported"
        assert mlp_head is None, "mlp_head customization is not supported"

        if self.num_classes == 0:
            return nn.Identity()

        if embed_dim is None:
            embed_dim = self.embedding_size

        return NormLinear(embed_dim, self.num_classes, self.reparameterized)

    def set_distillation_output(self, enable: bool = True) -> None:
        self.distillation_output = enable

    def classify(self, x: torch.Tensor) -> torch.Tensor:
        x_cls = self.classifier(x)
        x_dist = self.dist_classifier(x)

        if self.training is True and self.distillation_output is True:
            x = torch.stack([x_cls, x_dist], dim=1)
        else:
            x = (x_cls + x_dist) / 2

        return x

    @torch.no_grad()  # type: ignore[untyped-decorator]
    def reparameterize_model(self) -> None:
        for module in self.modules():
            if hasattr(module, "reparameterize") is True:
                module.reparameterize()

        self.reparameterized = True


registry.register_model_config(
    "microvit_v2_s1", MicroViT_v2, config={"embed_dims": [128, 224, 320], "depths": [2, 6, 5]}
)
registry.register_model_config(
    "microvit_v2_s2", MicroViT_v2, config={"embed_dims": [128, 308, 448], "depths": [2, 7, 5]}
)
registry.register_model_config(
    "microvit_v2_s3", MicroViT_v2, config={"embed_dims": [192, 384, 448], "depths": [3, 7, 6]}
)

registry.register_weights(
    "microvit_v2_s1_il-common",
    {
        "description": "MicroViT v2 S1 model trained on the il-common dataset",
        "resolution": (256, 256),
        "formats": {
            "pt": {
                "file_size": 26.2,
                "sha256": "d386c1161e93ddc84ff4fcc8c974341f1d62ac6984fc0b8f8107ca89a0fb1f08",
            }
        },
        "net": {"network": "microvit_v2_s1", "tag": "il-common"},
    },
)
registry.register_weights(
    "microvit_v2_s1_il-common_reparameterized",
    {
        "description": "MicroViT v2 S1 (reparameterized) model trained on the il-common dataset",
        "resolution": (256, 256),
        "formats": {
            "pt": {
                "file_size": 25.4,
                "sha256": "b6c3b57a227fb37c5ed4cdd79efa4b52627c3f5ff0ad514d4f71b78c51c69b9b",
            }
        },
        "net": {"network": "microvit_v2_s1", "tag": "il-common_reparameterized", "reparameterized": True},
    },
)
