"""
MViT v1, adapted from
https://github.com/facebookresearch/SlowFast/blob/main/slowfast/models/attention.py

"Multiscale Vision Transformers", https://arxiv.org/abs/2104.11227

Generated by gpt-5.6-sol max.
"""

# Reference license: Apache-2.0

import math
from collections import OrderedDict
from typing import Any
from typing import Optional

import torch
from torch import nn
from torchvision.ops import MLP
from torchvision.ops import StochasticDepth

from birder.model_registry import registry
from birder.net.base import DetectorBackbone
from birder.net.base import staged_stochastic_depth_rates
from birder.net.vit import adjust_position_embedding


def pre_pool(x: torch.Tensor, hw_shape: tuple[int, int]) -> tuple[torch.Tensor, torch.Tensor]:
    H, W = hw_shape
    cls_token = x[:, :, :1, :]
    x = x[:, :, 1:, :]
    x = x.reshape(-1, H, W, x.size(-1)).permute(0, 3, 1, 2).contiguous()

    return (x, cls_token)


def post_pool(x: torch.Tensor, num_heads: int, cls_token: torch.Tensor) -> tuple[torch.Tensor, tuple[int, int]]:
    hw_shape = (x.size(2), x.size(3))
    num_tokens = x.size(2) * x.size(3)
    x = x.reshape(-1, num_heads, x.size(1), num_tokens).transpose(2, 3)
    x = torch.concat((cls_token, x), dim=2)

    return (x, hw_shape)


class SequentialWithShape(nn.Sequential):
    def forward(  # pylint: disable=arguments-differ
        self, x: torch.Tensor, hw_shape: tuple[int, int]
    ) -> tuple[torch.Tensor, tuple[int, int]]:
        for module in self:
            x, hw_shape = module(x, hw_shape)

        return (x, hw_shape)


class PatchEmbed(nn.Module):
    def __init__(self, in_channels: int, embed_dim: int, kernel_size: int, stride: int, padding: int) -> None:
        super().__init__()
        self.proj = nn.Conv2d(
            in_channels,
            embed_dim,
            kernel_size=(kernel_size, kernel_size),
            stride=(stride, stride),
            padding=(padding, padding),
        )

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, tuple[int, int]]:
        x = self.proj(x)
        hw_shape = (x.size(2), x.size(3))
        x = x.flatten(2).transpose(1, 2)

        return (x, hw_shape)


class MultiScaleAttention(nn.Module):
    def __init__(
        self,
        dim: int,
        num_heads: int,
        kernel_q: tuple[int, int],
        kernel_kv: tuple[int, int],
        stride_q: tuple[int, int],
        stride_kv: tuple[int, int],
    ) -> None:
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim**-0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=True)
        self.proj = nn.Linear(dim, dim)

        if math.prod(kernel_q) != 1 or math.prod(stride_q) != 1:
            padding_q = tuple(kernel // 2 for kernel in kernel_q)
            self.pool_q = nn.Conv2d(
                head_dim,
                head_dim,
                kernel_size=kernel_q,
                stride=stride_q,
                padding=padding_q,
                groups=head_dim,
                bias=False,
            )
            self.norm_q = nn.LayerNorm(head_dim, eps=1e-6)
        else:
            self.pool_q = None
            self.norm_q = None

        padding_kv = tuple(kernel // 2 for kernel in kernel_kv)
        self.pool_k = nn.Conv2d(
            head_dim, head_dim, kernel_size=kernel_kv, stride=stride_kv, padding=padding_kv, groups=head_dim, bias=False
        )
        self.norm_k = nn.LayerNorm(head_dim, eps=1e-6)
        self.pool_v = nn.Conv2d(
            head_dim, head_dim, kernel_size=kernel_kv, stride=stride_kv, padding=padding_kv, groups=head_dim, bias=False
        )
        self.norm_v = nn.LayerNorm(head_dim, eps=1e-6)

    def forward(self, x: torch.Tensor, hw_shape: tuple[int, int]) -> tuple[torch.Tensor, tuple[int, int]]:
        B, N, C = x.size()
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv.unbind(dim=0)

        if self.pool_q is not None:
            q, cls_token = pre_pool(q, hw_shape)
            q = self.pool_q(q)
            q, q_shape = post_pool(q, self.num_heads, cls_token)
            q = self.norm_q(q)
        else:
            q_shape = hw_shape

        k, cls_token = pre_pool(k, hw_shape)
        k = self.pool_k(k)
        k, _ = post_pool(k, self.num_heads, cls_token)
        k = self.norm_k(k)

        v, cls_token = pre_pool(v, hw_shape)
        v = self.pool_v(v)
        v, _ = post_pool(v, self.num_heads, cls_token)
        v = self.norm_v(v)

        attn = (q * self.scale) @ k.transpose(-2, -1)
        attn = attn.softmax(dim=-1)
        x = attn @ v
        x = x.transpose(1, 2).reshape(B, -1, C)
        x = self.proj(x)

        return (x, q_shape)


class MultiScaleBlock(nn.Module):
    def __init__(
        self,
        dim: int,
        dim_out: int,
        num_heads: int,
        kernel_q: tuple[int, int],
        kernel_kv: tuple[int, int],
        stride_q: tuple[int, int],
        stride_kv: tuple[int, int],
        drop_path: float,
    ) -> None:
        super().__init__()
        self.norm1 = nn.LayerNorm(dim, eps=1e-6)
        self.attn = MultiScaleAttention(
            dim, num_heads=num_heads, kernel_q=kernel_q, kernel_kv=kernel_kv, stride_q=stride_q, stride_kv=stride_kv
        )
        self.drop_path = StochasticDepth(drop_path, mode="row")
        self.norm2 = nn.LayerNorm(dim, eps=1e-6)
        self.mlp = MLP(dim, [dim * 4, dim_out], activation_layer=nn.GELU, inplace=None)

        if dim != dim_out:
            self.proj_mlp = nn.Linear(dim, dim_out)
        else:
            self.proj_mlp = None

        if math.prod(stride_q) > 1:
            kernel_skip = tuple(stride + 1 if stride > 1 else stride for stride in stride_q)
            padding_skip = tuple(kernel // 2 for kernel in kernel_skip)
            self.pool_skip = nn.MaxPool2d(kernel_skip, stride_q, padding_skip, ceil_mode=False)
        else:
            self.pool_skip = None

    def _shortcut_pool(self, x: torch.Tensor, hw_shape: tuple[int, int]) -> torch.Tensor:
        cls_token = x[:, :1, :]
        x = x[:, 1:, :]

        B, _, C = x.size()
        H, W = hw_shape
        x = x.reshape(B, H, W, C).permute(0, 3, 1, 2).contiguous()
        x = self.pool_skip(x)
        x = x.reshape(B, C, -1).transpose(1, 2)
        x = torch.concat((cls_token, x), dim=1)

        return x

    def forward(self, x: torch.Tensor, hw_shape: tuple[int, int]) -> tuple[torch.Tensor, tuple[int, int]]:
        x_norm = self.norm1(x)
        x_block, hw_shape_new = self.attn(x_norm, hw_shape)

        if self.pool_skip is not None:
            x = self._shortcut_pool(x, hw_shape)

        x = x + self.drop_path(x_block)
        x_norm = self.norm2(x)
        x_mlp = self.mlp(x_norm)

        if self.proj_mlp is not None:
            x = self.proj_mlp(x_norm)

        x = x + self.drop_path(x_mlp)

        return (x, hw_shape_new)


class MultiScaleVitStage(nn.Module):
    def __init__(
        self,
        dim: int,
        dim_out: int,
        depth: int,
        num_heads: int,
        stride_q: tuple[int, int],
        stride_kv: tuple[int, int],
        drop_path: list[float],
    ) -> None:
        super().__init__()
        self.blocks = nn.ModuleList()
        out_dims = (dim,) * (depth - 1) + (dim_out,)

        for i in range(depth):
            block_stride_q = stride_q if i == 0 else (1, 1)
            kernel_q = (3, 3) if math.prod(block_stride_q) > 1 else (1, 1)
            self.blocks.append(
                MultiScaleBlock(
                    dim=dim,
                    dim_out=out_dims[i],
                    num_heads=num_heads,
                    kernel_q=kernel_q,
                    kernel_kv=(3, 3),
                    stride_q=block_stride_q,
                    stride_kv=stride_kv,
                    drop_path=drop_path[i],
                )
            )
            dim = out_dims[i]

    def forward(self, x: torch.Tensor, hw_shape: tuple[int, int]) -> tuple[torch.Tensor, tuple[int, int]]:
        for block in self.blocks:
            x, hw_shape = block(x, hw_shape)

        return (x, hw_shape)


class MViT_v1(DetectorBackbone):
    block_group_regex = r"body\.stage(\d+)\.blocks\.(\d+)"

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"

        depths: list[int] = self.config["depths"]
        embed_dims: list[int] = self.config["embed_dims"]
        num_heads: list[int] = self.config["num_heads"]
        stem_kernel: int = self.config["stem_kernel"]
        stem_stride: int = self.config["stem_stride"]
        stem_padding: int = self.config["stem_padding"]
        stride_q: list[tuple[int, int]] = self.config["stride_q"]
        drop_path_rate: float = self.config["drop_path_rate"]

        num_stages = len(depths)
        assert len(embed_dims) == num_stages
        assert len(num_heads) == num_stages
        assert len(stride_q) == num_stages
        assert all(embed_dim % heads == 0 for embed_dim, heads in zip(embed_dims, num_heads, strict=True))
        assert all(stride[0] == stride[1] for stride in stride_q)

        torch._assert(self.size[0] % stem_stride == 0, "Input shape indivisible by stem stride!")
        torch._assert(self.size[1] % stem_stride == 0, "Input shape indivisible by stem stride!")

        stride_kv = []
        current_stride_kv = (4, 4)
        for stage_stride_q in stride_q:
            if math.prod(stage_stride_q) > 1:
                current_stride_kv = (
                    max(current_stride_kv[0] // stage_stride_q[0], 1),
                    max(current_stride_kv[1] // stage_stride_q[1], 1),
                )

            stride_kv.append(current_stride_kv)

        self.patch_embed = PatchEmbed(
            self.input_channels, embed_dims[0], kernel_size=stem_kernel, stride=stem_stride, padding=stem_padding
        )
        self.num_special_tokens = 1
        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dims[0]))
        patch_grid = (self.size[0] // stem_stride, self.size[1] // stem_stride)
        self.pos_embedding = nn.Parameter(
            torch.zeros(1, math.prod(patch_grid) + self.num_special_tokens, embed_dims[0])
        )

        dpr = staged_stochastic_depth_rates(drop_path_rate, depths)
        stages: OrderedDict[str, nn.Module] = OrderedDict()
        return_channels: list[int] = []
        for i in range(num_stages):
            dim_out = embed_dims[min(i + 1, num_stages - 1)]
            stages[f"stage{i+1}"] = MultiScaleVitStage(
                dim=embed_dims[i],
                dim_out=dim_out,
                depth=depths[i],
                num_heads=num_heads[i],
                stride_q=stride_q[i],
                stride_kv=stride_kv[i],
                drop_path=dpr[i],
            )
            return_channels.append(dim_out)

        self.body = SequentialWithShape(stages)
        self.norm = nn.LayerNorm(embed_dims[-1], eps=1e-6)
        self.return_stages = self.return_stages[:num_stages]
        self.return_channels = return_channels
        self.embedding_size = embed_dims[-1]
        self.classifier = self.create_classifier()

        self.max_stride = stem_stride * math.prod(stride[0] for stride in stride_q)
        self.stem_stride = stem_stride
        self.stem_width = embed_dims[0]
        self.feature_dim = embed_dims[-1]

        # Weights initialization
        nn.init.trunc_normal_(self.cls_token, std=0.02)
        nn.init.trunc_normal_(self.pos_embedding, std=0.02)
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def _get_pos_embed(self, H: int, W: int) -> torch.Tensor:
        if self.dynamic_size is False:
            return self.pos_embedding

        if H == self.size[0] and W == self.size[1]:
            return self.pos_embedding

        return adjust_position_embedding(
            self.pos_embedding,
            (self.size[0] // self.stem_stride, self.size[1] // self.stem_stride),
            (H // self.stem_stride, W // self.stem_stride),
            self.num_special_tokens,
            antialias=False,
        )

    def freeze(self, freeze_classifier: bool = True, unfreeze_features: bool = False) -> None:
        for param in self.parameters():
            param.requires_grad_(False)

        if freeze_classifier is False:
            for param in self.classifier.parameters():
                param.requires_grad_(True)

        if unfreeze_features is True:
            for param in self.norm.parameters():
                param.requires_grad_(True)

    def transform_to_backbone(self) -> None:
        super().transform_to_backbone()
        self.norm = nn.Identity()

    def detection_features(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        H, W = x.shape[-2:]
        x, hw_shape = self.patch_embed(x)
        cls_token = self.cls_token.expand(x.size(0), -1, -1)
        x = torch.concat((cls_token, x), dim=1)
        x = x + self._get_pos_embed(H, W)

        out = {}
        for name, module in self.body.named_children():
            x, hw_shape = module(x, hw_shape)
            if name in self.return_stages:
                x_inter = x[:, self.num_special_tokens :]
                x_inter = x_inter.reshape(x.size(0), hw_shape[0], hw_shape[1], -1).permute(0, 3, 1, 2)
                out[name] = x_inter

        return out

    def freeze_stages(self, up_to_stage: int) -> None:
        for param in self.patch_embed.parameters():
            param.requires_grad_(False)

        self.pos_embedding.requires_grad_(False)

        for idx, module in enumerate(self.body.children()):
            if idx >= up_to_stage:
                break

            for param in module.parameters():
                param.requires_grad_(False)

    def forward_features(self, x: torch.Tensor) -> torch.Tensor:
        H, W = x.shape[-2:]
        x, hw_shape = self.patch_embed(x)
        cls_token = self.cls_token.expand(x.size(0), -1, -1)
        x = torch.concat((cls_token, x), dim=1)
        x = x + self._get_pos_embed(H, W)
        x, _ = self.body(x, hw_shape)
        x = self.norm(x)

        return x

    def flatten_features(self, features: torch.Tensor, include_special_tokens: bool = True) -> torch.Tensor:
        if include_special_tokens is False:
            return features[:, self.num_special_tokens :]

        return features

    def embedding_from_features(self, features: torch.Tensor) -> torch.Tensor:
        return features[:, 0]

    def adjust_size(self, new_size: tuple[int, int]) -> None:
        if new_size == self.size:
            return

        assert new_size[0] % self.stem_stride == 0, "Input shape indivisible by stem stride!"
        assert new_size[1] % self.stem_stride == 0, "Input shape indivisible by stem stride!"

        old_size = self.size
        super().adjust_size(new_size)

        with torch.no_grad():
            pos_embedding = adjust_position_embedding(
                self.pos_embedding,
                (old_size[0] // self.stem_stride, old_size[1] // self.stem_stride),
                (new_size[0] // self.stem_stride, new_size[1] // self.stem_stride),
                self.num_special_tokens,
            )

        self.pos_embedding = nn.Parameter(pos_embedding)


registry.register_model_config(
    "mvit_v1_s_d16",
    MViT_v1,
    config={
        "depths": [3, 7, 6],
        "embed_dims": [128, 256, 512],
        "num_heads": [1, 2, 4],
        "stem_kernel": 8,
        "stem_stride": 8,
        "stem_padding": 0,
        "stride_q": [(1, 1), (2, 2), (2, 2)],
        "drop_path_rate": 0.1,
    },
)
registry.register_model_config(
    "mvit_v1_b_d16",
    MViT_v1,
    config={
        "depths": [1, 2, 11, 2],
        "embed_dims": [96, 192, 384, 768],
        "num_heads": [1, 2, 4, 8],
        "stem_kernel": 7,
        "stem_stride": 4,
        "stem_padding": 3,
        "stride_q": [(1, 1), (2, 2), (2, 2), (2, 2)],
        "drop_path_rate": 0.1,
    },
)
registry.register_model_config(
    "mvit_v1_b_d24",
    MViT_v1,
    config={
        "depths": [2, 3, 16, 3],
        "embed_dims": [112, 224, 448, 896],
        "num_heads": [1, 2, 4, 8],
        "stem_kernel": 7,
        "stem_stride": 4,
        "stem_padding": 3,
        "stride_q": [(1, 1), (2, 2), (2, 2), (2, 2)],
        "drop_path_rate": 0.3,
    },
)
