"""
NaFlex RoPE ViT

Paper "Patch n' Pack: NaViT, a Vision Transformer for any Aspect Ratio and Resolution",
https://arxiv.org/abs/2307.06304
and
Paper "SigLIP 2: Multilingual Vision-Language Encoders with Improved Semantic Understanding, Localization,
and Dense Features", https://arxiv.org/abs/2502.14786

Generated by gpt-5.6-sol max.
"""

import logging
from functools import partial
from typing import Any
from typing import Literal
from typing import Optional

import torch
from torch import nn

from birder.common.masking import mask_tokens
from birder.model_registry import registry
from birder.net._vit_configs import BASE
from birder.net._vit_configs import LARGE
from birder.net._vit_configs import MEDIUM
from birder.net._vit_configs import SMALL
from birder.net._vit_configs import SO150
from birder.net._vit_configs import SO400
from birder.net._vit_configs import TINY
from birder.net.base import TokenRetentionResultType
from birder.net.flexivit import interpolate_proj
from birder.net.naflex_vit import GridSamplePosEmbed
from birder.net.naflex_vit import InterpolatePosEmbed
from birder.net.naflex_vit import naflex_proj
from birder.net.rope_vit import MAEDecoderBlock
from birder.net.rope_vit import RoPE_ViT
from birder.net.vit import adjust_position_embedding

logger = logging.getLogger(__name__)


class NaFlex_RoPE_ViT(RoPE_ViT):
    scriptable = False

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        if config is not None and config.get("mlp_layer_type", "FFN") == "SoftMoE_FFN":
            raise ValueError("NaFlex RoPE ViT does not support SoftMoE_FFN")

        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"

        if isinstance(self.conv_proj, nn.Conv2d) is False:
            raise ValueError("NaFlex RoPE ViT only supports the standard patchify stem")

        self.naflex_patch_resampling: bool = self.config.get("naflex_patch_resampling", False)

        pos_embed_resize_mode: str = self.config.get("naflex_pos_embed_resize_mode", "grid_sample")
        if pos_embed_resize_mode == "grid_sample":
            pos_embed_resize = GridSamplePosEmbed(interpolation_mode=self.pos_embed_interpolation_mode)
        elif pos_embed_resize_mode == "interpolate":
            pos_embed_resize = InterpolatePosEmbed(
                interpolation_mode=self.pos_embed_interpolation_mode,
                antialias=self.config.get("naflex_pos_embed_antialias", False),
            )
        else:
            raise ValueError(f"Unknown naflex_pos_embed_resize_mode '{pos_embed_resize_mode}'")

        self.pos_embed_resize = pos_embed_resize

        self.set_dynamic_size()

    def _get_batched_pos_embed(self, grid_sizes: torch.Tensor, max_seq_len: int) -> Optional[torch.Tensor]:
        if self.pos_embedding is None:
            return None

        return self.pos_embed_resize(
            self.pos_embedding,
            grid_sizes,
            max_seq_len,
            (self.size[0] // self.patch_size, self.size[1] // self.patch_size),
            self.num_special_tokens if self.pos_embed_special_tokens is True else 0,
        )

    def _pool(self, x: torch.Tensor, valid_mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        if valid_mask is None:
            return super()._pool(x)

        if self.attn_pool is not None:
            if self.attn_pool_special_tokens is False:
                x = x[:, self.num_special_tokens :]
            elif self.num_special_tokens > 0:
                special_valid_mask = valid_mask.new_ones((valid_mask.size(0), self.num_special_tokens))
                valid_mask = torch.concat([special_valid_mask, valid_mask], dim=1)

            x = self.attn_pool(x, attn_mask=valid_mask[:, None, None, :])
            return x[:, 0]

        if self.class_token is not None:
            return x[:, self.num_reg_tokens]

        x = x[:, self.num_special_tokens :]
        valid_mask = valid_mask.unsqueeze(-1)
        return (x * valid_mask).sum(dim=1) / valid_mask.sum(dim=1)

    def _forward_naflex_features(
        self,
        patches: torch.Tensor,
        grid_sizes: torch.Tensor,
        valid_mask: torch.Tensor,
        return_input_embedding: bool = False,
        attn_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        x = naflex_proj(patches, self.conv_proj.weight, self.conv_proj.bias, self.naflex_patch_resampling)
        x = x.masked_fill(~valid_mask.unsqueeze(-1), 0)
        patch_embedding = x

        pos_embedding = self._get_batched_pos_embed(grid_sizes, patches.size(1))
        if pos_embedding is not None and self.pos_embed_special_tokens is False:
            x = x + pos_embedding

        special_tokens: list[torch.Tensor] = []
        if self.reg_tokens is not None:
            special_tokens.append(self.reg_tokens.expand(x.size(0), -1, -1))
        if self.class_token is not None:
            special_tokens.append(self.class_token.expand(x.size(0), -1, -1))
        if len(special_tokens) > 0:
            x = torch.concat(special_tokens + [x], dim=1)

        if return_input_embedding is True:
            if len(special_tokens) > 0:
                input_embedding = torch.concat(special_tokens + [patch_embedding], dim=1)
            else:
                input_embedding = patch_embedding
        else:
            input_embedding = None

        if pos_embedding is not None and self.pos_embed_special_tokens is True:
            special_pos_embedding = self.pos_embedding[:, : self.num_special_tokens].expand(x.size(0), -1, -1)
            x = x + torch.concat([special_pos_embedding, pos_embedding], dim=1)

        rope = self.rope.get_batched_pos_embed(grid_sizes, patches.size(1))

        if self.num_special_tokens > 0:
            special_valid_mask = valid_mask.new_ones((valid_mask.size(0), self.num_special_tokens))
            valid_mask = torch.concat([special_valid_mask, valid_mask], dim=1)

        valid_attn_mask = valid_mask[:, None, None, :]
        if attn_mask is None:
            attn_mask = valid_attn_mask
        elif attn_mask.dtype == torch.bool:
            attn_mask = attn_mask & valid_attn_mask
        else:
            padding_bias = torch.zeros_like(valid_attn_mask, dtype=attn_mask.dtype)
            padding_bias = padding_bias.masked_fill(~valid_attn_mask, float("-inf"))
            attn_mask = attn_mask + padding_bias

        x = self.encoder(x, rope, attn_mask=attn_mask)
        x = self.norm(x)

        if return_input_embedding is True and input_embedding is not None:
            return torch.stack([input_embedding, x], dim=-1)

        return x

    def masked_encoding_retention(
        self,
        x: torch.Tensor,
        mask: torch.Tensor,
        mask_token: Optional[torch.Tensor] = None,
        return_keys: Literal["all", "features", "embedding"] = "features",
        *,
        grid_sizes: Optional[torch.Tensor] = None,
        valid_mask: Optional[torch.Tensor] = None,
    ) -> TokenRetentionResultType:
        """
        Encode images or padded NaFlex token sequences while retaining masked tokens

        Padded token features are returned as a channel-first sequence of shape (B, C, L).
        The supplied 'valid_mask' identifies the valid positions in that sequence, and padded
        feature positions are returned as zeros.
        """

        if grid_sizes is None:
            return super().masked_encoding_retention(x, mask, mask_token=mask_token, return_keys=return_keys)

        x = naflex_proj(x, self.conv_proj.weight, self.conv_proj.bias, self.naflex_patch_resampling)
        x = mask_tokens(x, mask, mask_token=mask_token)
        x = x.masked_fill(~valid_mask.unsqueeze(-1), 0)  # type: ignore[union-attr]

        max_seq_len = x.size(1)
        pos_embedding = self._get_batched_pos_embed(grid_sizes, max_seq_len)
        if pos_embedding is not None and self.pos_embed_special_tokens is False:
            x = x + pos_embedding

        special_tokens: list[torch.Tensor] = []
        if self.reg_tokens is not None:
            special_tokens.append(self.reg_tokens.expand(x.size(0), -1, -1))
        if self.class_token is not None:
            special_tokens.append(self.class_token.expand(x.size(0), -1, -1))
        if len(special_tokens) > 0:
            x = torch.concat(special_tokens + [x], dim=1)

        if pos_embedding is not None and self.pos_embed_special_tokens is True:
            special_pos_embedding = self.pos_embedding[:, : self.num_special_tokens].expand(x.size(0), -1, -1)
            x = x + torch.concat([special_pos_embedding, pos_embedding], dim=1)

        rope = self.rope.get_batched_pos_embed(grid_sizes, max_seq_len)

        if self.num_special_tokens > 0:
            special_valid_mask = valid_mask.new_ones((x.size(0), self.num_special_tokens))  # type: ignore[union-attr]
            encoder_valid_mask = torch.concat([special_valid_mask, valid_mask], dim=1)
        else:
            encoder_valid_mask = valid_mask

        x = self.encoder(x, rope, attn_mask=encoder_valid_mask[:, None, None, :])
        x = self.norm(x)

        result: TokenRetentionResultType = {}
        if return_keys in ("all", "features"):
            features = x[:, self.num_special_tokens :].transpose(1, 2)
            result["features"] = features.masked_fill(~valid_mask.unsqueeze(1), 0)  # type: ignore[union-attr]

        if return_keys in ("all", "embedding"):
            result["embedding"] = self.embedding_from_features(x, valid_mask)

        return result

    def forward_features(
        self,
        x: torch.Tensor,
        return_input_embedding: bool = False,
        attn_mask: Optional[torch.Tensor] = None,
        *,
        grid_sizes: Optional[torch.Tensor] = None,
        valid_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        if grid_sizes is None:
            return super().forward_features(
                x,
                return_input_embedding=return_input_embedding,
                attn_mask=attn_mask,
            )

        return self._forward_naflex_features(
            x,
            grid_sizes,
            valid_mask,
            return_input_embedding=return_input_embedding,
            attn_mask=attn_mask,
        )

    def embedding_from_features(
        self, features: torch.Tensor, valid_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        return self.embedding_norm(self._pool(features, valid_mask))

    def embedding(
        self, x: torch.Tensor, grid_sizes: Optional[torch.Tensor] = None, valid_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        if grid_sizes is None:
            x = super().forward_features(x)
            return self.embedding_from_features(x)

        x = self._forward_naflex_features(x, grid_sizes, valid_mask)
        return self.embedding_from_features(x, valid_mask)

    def forward(
        self, x: torch.Tensor, grid_sizes: Optional[torch.Tensor] = None, valid_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        x = self.embedding(x, grid_sizes, valid_mask)
        return self.classify(x)

    def set_dynamic_size(self, dynamic_size: bool = True) -> None:
        if dynamic_size is False:
            raise ValueError("NaFlex RoPE ViT only supports dynamic mode")

        super().set_dynamic_size(dynamic_size)

    def set_naflex_patch_resampling(self, enabled: bool = True) -> None:
        logger.debug(f"Setting NaFlex patch resampling to: {enabled}")
        self.naflex_patch_resampling = enabled

    def adjust_patch_size(self, patch_size: int) -> None:
        if self.patch_size == patch_size:
            return

        assert self.size[0] % patch_size == 0, "Input shape indivisible by patch size!"
        assert self.size[1] % patch_size == 0, "Input shape indivisible by patch size!"

        logger.debug(f"Setting patch size to: {patch_size}")
        with torch.no_grad():
            conv_proj_weight = interpolate_proj(self.conv_proj.weight, patch_size)

        self.conv_proj.weight = nn.Parameter(conv_proj_weight)
        self.conv_proj.kernel_size = (patch_size, patch_size)
        self.conv_proj.stride = (patch_size, patch_size)
        if self.pos_embedding is not None:
            if self.pos_embed_special_tokens is True:
                num_prefix_tokens = self.num_special_tokens
            else:
                num_prefix_tokens = 0

            with torch.no_grad():
                pos_embedding = adjust_position_embedding(
                    self.pos_embedding,
                    (self.size[0] // self.patch_size, self.size[1] // self.patch_size),
                    (self.size[0] // patch_size, self.size[1] // patch_size),
                    num_prefix_tokens,
                    interpolation_mode=self.pos_embed_interpolation_mode,
                )

            self.pos_embedding = nn.Parameter(pos_embedding)

        grid_size = (self.size[0] // patch_size, self.size[1] // patch_size)
        self.rope.set_grid_size(grid_size)

        self.decoder_block = partial(
            MAEDecoderBlock,
            16,
            num_special_tokens=self.num_special_tokens,
            activation_layer=self.act_layer,
            grid_size=grid_size,
            rope_grid_indexing=self.rope_grid_indexing,
            rope_grid_offset=self.rope_grid_offset,
            rope_temperature=self.rope_temperature,
            layer_scale_init_value=self.layer_scale_init_value,
            norm_layer=self.norm_layer,
            norm_layer_eps=self.norm_layer_eps,
            mlp_layer=self.decoder_mlp_layer,
            rope_style=self.rope_style,
            rope_rot_type=self.rope_rot_type,
        )

        self.patch_size = patch_size
        self.max_stride = patch_size
        self.stem_stride = patch_size


registry.register_model_config(
    "naflex_rope_vit_t16",
    NaFlex_RoPE_ViT,
    config={"patch_size": 16, **TINY},
)
registry.register_model_config(
    "naflex_rope_vit_s16",
    NaFlex_RoPE_ViT,
    config={"patch_size": 16, **SMALL},
)
registry.register_model_config(
    "naflex_rope_vit_s14_swiglu_avg",
    NaFlex_RoPE_ViT,
    config={"patch_size": 14, **SMALL, "class_token": False, "mlp_layer_type": "SwiGLU_FFN"},
)
registry.register_model_config(
    "naflex_rope_vit_m16",
    NaFlex_RoPE_ViT,
    config={"patch_size": 16, **MEDIUM},
)
registry.register_model_config(
    "naflex_rope_vit_m14_swiglu_avg",
    NaFlex_RoPE_ViT,
    config={"patch_size": 14, **MEDIUM, "class_token": False, "mlp_layer_type": "SwiGLU_FFN"},
)
registry.register_model_config(
    "naflex_rope_vit_b16",
    NaFlex_RoPE_ViT,
    config={"patch_size": 16, **BASE},
)
registry.register_model_config(
    "naflex_rope_vit_l16",
    NaFlex_RoPE_ViT,
    config={"patch_size": 16, **LARGE},
)
registry.register_model_config(
    "naflex_rope_vit_so400m_p14_ap",
    NaFlex_RoPE_ViT,
    config={"patch_size": 14, **SO400, "class_token": False, "attn_pool_head": True},
)

# With registers
####################

registry.register_model_config(
    "naflex_rope_vit_reg1_t16",
    NaFlex_RoPE_ViT,
    config={"patch_size": 16, **TINY, "num_reg_tokens": 1},
)
registry.register_model_config(
    "naflex_rope_vit_reg4_b14",
    NaFlex_RoPE_ViT,
    config={"patch_size": 14, **BASE, "num_reg_tokens": 4},
)
registry.register_model_config(
    "naflex_rope_vit_reg8_so150m_p14_swiglu_rms_avg",
    NaFlex_RoPE_ViT,
    config={
        "patch_size": 14,
        **SO150,
        "num_reg_tokens": 8,
        "class_token": False,
        "norm_layer_type": "RMSNorm",
        "mlp_layer_type": "SwiGLU_FFN",
    },
)

# DeiT III
####################

registry.register_model_config(
    "naflex_rope_deit3_t16",
    NaFlex_RoPE_ViT,
    config={"pos_embed_special_tokens": False, "patch_size": 16, **TINY, "layer_scale_init_value": 1e-5},
)
registry.register_model_config(
    "naflex_rope_deit3_m14",
    NaFlex_RoPE_ViT,
    config={
        "pos_embed_special_tokens": False,
        "patch_size": 14,
        **MEDIUM,
        "layer_scale_init_value": 1e-5,
        "drop_path_rate": 0.1,
    },
)

# With registers
####################

registry.register_model_config(
    "naflex_rope_deit3_reg1_t16",
    NaFlex_RoPE_ViT,
    config={
        "pos_embed_special_tokens": False,
        "patch_size": 16,
        **TINY,
        "layer_scale_init_value": 1e-5,
        "num_reg_tokens": 1,
    },
)
