"""
NaFlex ViT, adapted from
https://github.com/google-research/big_vision/blob/main/big_vision/models/proj/image_text/naflex_vit.py
and
https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/naflexvit.py

Paper "Patch n' Pack: NaViT, a Vision Transformer for any Aspect Ratio and Resolution",
https://arxiv.org/abs/2307.06304
and
Paper "SigLIP 2: Multilingual Vision-Language Encoders with Improved Semantic Understanding, Localization,
and Dense Features", https://arxiv.org/abs/2502.14786

Generated by gpt-5.6-sol xhigh.
"""

# Reference license: Apache-2.0 (both)

import logging
import math
from typing import Any
from typing import Literal
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn

from birder.common.masking import mask_tokens
from birder.model_registry import registry
from birder.net._vit_configs import BASE
from birder.net._vit_configs import LARGE
from birder.net._vit_configs import MEDIUM
from birder.net._vit_configs import SMALL
from birder.net._vit_configs import SO150
from birder.net._vit_configs import SO400
from birder.net._vit_configs import TINY
from birder.net.base import TokenRetentionResultType
from birder.net.flexivit import interpolate_proj
from birder.net.vit import ViT
from birder.net.vit import adjust_position_embedding

logger = logging.getLogger(__name__)


def naflex_proj(
    x: torch.Tensor, proj_weight: torch.Tensor, proj_bias: Optional[torch.Tensor], patch_resampling: bool
) -> torch.Tensor:
    if patch_resampling is True:
        canonical_patch_dim = proj_weight.size(1) * proj_weight.size(2) * proj_weight.size(3)
        if x.size(-1) != canonical_patch_dim:
            patch_size = math.isqrt(x.size(-1) // proj_weight.size(1))
            proj_weight = interpolate_proj(proj_weight, patch_size)

    return F.linear(x, proj_weight.flatten(1), proj_bias)  # pylint: disable=not-callable


class GridSamplePosEmbed(nn.Module):
    def __init__(self, interpolation_mode: str) -> None:
        super().__init__()
        self.interpolation_mode = interpolation_mode

    def forward(
        self,
        pos_embedding: torch.Tensor,
        grid_sizes: torch.Tensor,
        max_seq_len: int,
        base_grid_size: tuple[int, int],
        num_prefix_tokens: int,
    ) -> torch.Tensor:
        batch_size = grid_sizes.size(0)
        orig_dtype = pos_embedding.dtype
        pos_embedding = pos_embedding[:, num_prefix_tokens:]
        pos_embedding = pos_embedding.float().reshape(1, base_grid_size[0], base_grid_size[1], -1)
        pos_embedding = pos_embedding.permute(0, 3, 1, 2).expand(batch_size, -1, -1, -1)

        patch_indices = torch.arange(max_seq_len, device=grid_sizes.device).unsqueeze(0)
        grid_h = grid_sizes[:, 0].unsqueeze(1)
        grid_w = grid_sizes[:, 1].unsqueeze(1)
        patch_y = torch.div(patch_indices, grid_w, rounding_mode="floor")
        patch_x = torch.remainder(patch_indices, grid_w)

        sample_y = 2 * (patch_y.to(torch.float32) + 0.5) / grid_h - 1
        sample_x = 2 * (patch_x.to(torch.float32) + 0.5) / grid_w - 1
        sampling_grid = torch.stack((sample_x, sample_y), dim=-1).unsqueeze(2)
        pos_embedding = F.grid_sample(
            pos_embedding,
            sampling_grid,
            mode=self.interpolation_mode,
            padding_mode="border",
            align_corners=False,
        )
        pos_embedding = pos_embedding.squeeze(-1).transpose(1, 2).to(orig_dtype)

        valid_mask = patch_indices < (grid_h * grid_w)
        return pos_embedding.masked_fill(~valid_mask.unsqueeze(-1), 0)


class InterpolatePosEmbed(nn.Module):
    def __init__(self, interpolation_mode: str, antialias: bool) -> None:
        super().__init__()
        self.interpolation_mode = interpolation_mode
        self.antialias = antialias

    @torch.compiler.disable()  # type: ignore[untyped-decorator]
    def forward(
        self,
        pos_embedding: torch.Tensor,
        grid_sizes: torch.Tensor,
        max_seq_len: int,
        base_grid_size: tuple[int, int],
        num_prefix_tokens: int,
    ) -> torch.Tensor:
        batched_pos_embedding = pos_embedding.new_zeros((grid_sizes.size(0), max_seq_len, pos_embedding.size(-1)))

        size_to_indices: dict[tuple[int, int], list[int]] = {}
        for batch_idx, grid_size in enumerate(grid_sizes.tolist()):
            size_to_indices.setdefault((grid_size[0], grid_size[1]), []).append(batch_idx)

        for grid_size, batch_indices in size_to_indices.items():
            if grid_size == base_grid_size:
                resized_pos_embedding = pos_embedding[:, num_prefix_tokens:]
            else:
                resized_pos_embedding = adjust_position_embedding(
                    pos_embedding,
                    base_grid_size,
                    grid_size,
                    num_prefix_tokens,
                    interpolation_mode=self.interpolation_mode,
                    antialias=self.antialias,
                )[:, num_prefix_tokens:]

            seq_len = min(max_seq_len, resized_pos_embedding.size(1))
            batched_pos_embedding[:, :seq_len].index_add_(
                0,
                torch.tensor(batch_indices, device=batched_pos_embedding.device),
                resized_pos_embedding[:, :seq_len].expand(len(batch_indices), -1, -1),
            )

        return batched_pos_embedding


class NaFlex_ViT(ViT):
    scriptable = False

    def __init__(
        self,
        input_channels: int,
        num_classes: int,
        *,
        config: Optional[dict[str, Any]] = None,
        size: Optional[tuple[int, int]] = None,
    ) -> None:
        if config is not None and config.get("mlp_layer_type", "FFN") == "SoftMoE_FFN":
            raise ValueError("NaFlex ViT does not support SoftMoE_FFN")

        super().__init__(input_channels, num_classes, config=config, size=size)
        assert self.config is not None, "must set config"

        if isinstance(self.conv_proj, nn.Conv2d) is False:
            raise ValueError("NaFlex ViT only supports the standard patchify stem")

        self.naflex_patch_resampling: bool = self.config.get("naflex_patch_resampling", False)

        pos_embed_resize_mode: str = self.config.get("naflex_pos_embed_resize_mode", "grid_sample")
        if pos_embed_resize_mode == "grid_sample":
            if self.pos_embed_antialias is True:
                raise ValueError("pos_embed_antialias=True requires naflex_pos_embed_resize_mode='interpolate'")

            pos_embed_resize = GridSamplePosEmbed(interpolation_mode=self.pos_embed_interpolation_mode)
        elif pos_embed_resize_mode == "interpolate":
            pos_embed_resize = InterpolatePosEmbed(
                interpolation_mode=self.pos_embed_interpolation_mode,
                antialias=self.pos_embed_antialias,
            )
        else:
            raise ValueError(f"Unknown naflex_pos_embed_resize_mode '{pos_embed_resize_mode}'")

        self.pos_embed_resize = pos_embed_resize

        self.set_dynamic_size()

    def _get_batched_pos_embed(self, grid_sizes: torch.Tensor, max_seq_len: int) -> Optional[torch.Tensor]:
        if self.pos_embedding is None:
            return None

        return self.pos_embed_resize(
            self.pos_embedding,
            grid_sizes,
            max_seq_len,
            (self.size[0] // self.patch_size, self.size[1] // self.patch_size),
            self.num_special_tokens if self.pos_embed_special_tokens is True else 0,
        )

    def _pool(self, x: torch.Tensor, valid_mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        if valid_mask is None:
            return super()._pool(x)

        if self.attn_pool is not None:
            if self.attn_pool_special_tokens is False:
                x = x[:, self.num_special_tokens :]
            elif self.num_special_tokens > 0:
                special_valid_mask = valid_mask.new_ones((valid_mask.size(0), self.num_special_tokens))
                valid_mask = torch.concat([special_valid_mask, valid_mask], dim=1)

            x = self.attn_pool(x, attn_mask=valid_mask[:, None, None, :])
            return x[:, 0]

        if self.class_token is not None:
            return x[:, self.num_reg_tokens]

        x = x[:, self.num_special_tokens :]
        valid_mask = valid_mask.unsqueeze(-1)
        return (x * valid_mask).sum(dim=1) / valid_mask.sum(dim=1)

    def _forward_naflex_features(
        self,
        patches: torch.Tensor,
        grid_sizes: torch.Tensor,
        valid_mask: torch.Tensor,
        return_input_embedding: bool = False,
        attn_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        x = naflex_proj(patches, self.conv_proj.weight, self.conv_proj.bias, self.naflex_patch_resampling)
        x = x.masked_fill(~valid_mask.unsqueeze(-1), 0)
        patch_embedding = x

        pos_embedding = self._get_batched_pos_embed(grid_sizes, patches.size(1))
        if pos_embedding is not None and self.pos_embed_special_tokens is False:
            x = x + pos_embedding

        special_tokens: list[torch.Tensor] = []
        if self.reg_tokens is not None:
            special_tokens.append(self.reg_tokens.expand(x.size(0), -1, -1))
        if self.class_token is not None:
            special_tokens.append(self.class_token.expand(x.size(0), -1, -1))
        if len(special_tokens) > 0:
            x = torch.concat(special_tokens + [x], dim=1)

        if return_input_embedding is True:
            if len(special_tokens) > 0:
                input_embedding = torch.concat(special_tokens + [patch_embedding], dim=1)
            else:
                input_embedding = patch_embedding
        else:
            input_embedding = None

        if pos_embedding is not None and self.pos_embed_special_tokens is True:
            special_pos_embedding = self.pos_embedding[:, : self.num_special_tokens].expand(x.size(0), -1, -1)
            x = x + torch.concat([special_pos_embedding, pos_embedding], dim=1)

        if self.num_special_tokens > 0:
            special_valid_mask = valid_mask.new_ones((valid_mask.size(0), self.num_special_tokens))
            valid_mask = torch.concat([special_valid_mask, valid_mask], dim=1)

        valid_attn_mask = valid_mask[:, None, None, :]
        if attn_mask is None:
            attn_mask = valid_attn_mask
        elif attn_mask.dtype == torch.bool:
            attn_mask = attn_mask & valid_attn_mask
        else:
            padding_bias = torch.zeros_like(valid_attn_mask, dtype=attn_mask.dtype)
            padding_bias = padding_bias.masked_fill(~valid_attn_mask, float("-inf"))
            attn_mask = attn_mask + padding_bias

        x = self.encoder(x, attn_mask=attn_mask)
        x = self.norm(x)

        if return_input_embedding is True and input_embedding is not None:
            return torch.stack([input_embedding, x], dim=-1)

        return x

    def masked_encoding_retention(
        self,
        x: torch.Tensor,
        mask: torch.Tensor,
        mask_token: Optional[torch.Tensor] = None,
        return_keys: Literal["all", "features", "embedding"] = "features",
        *,
        grid_sizes: Optional[torch.Tensor] = None,
        valid_mask: Optional[torch.Tensor] = None,
    ) -> TokenRetentionResultType:
        """
        Encode images or padded NaFlex token sequences while retaining masked tokens

        Padded token features are returned as a channel-first sequence of shape (B, C, L).
        The supplied 'valid_mask' identifies the valid positions in that sequence, and padded
        feature positions are returned as zeros.
        """

        if grid_sizes is None:
            return super().masked_encoding_retention(x, mask, mask_token=mask_token, return_keys=return_keys)

        x = naflex_proj(x, self.conv_proj.weight, self.conv_proj.bias, self.naflex_patch_resampling)
        x = mask_tokens(x, mask, mask_token=mask_token)
        x = x.masked_fill(~valid_mask.unsqueeze(-1), 0)  # type: ignore[union-attr]

        pos_embedding = self._get_batched_pos_embed(grid_sizes, x.size(1))
        if pos_embedding is not None and self.pos_embed_special_tokens is False:
            x = x + pos_embedding

        special_tokens: list[torch.Tensor] = []
        if self.reg_tokens is not None:
            special_tokens.append(self.reg_tokens.expand(x.size(0), -1, -1))
        if self.class_token is not None:
            special_tokens.append(self.class_token.expand(x.size(0), -1, -1))
        if len(special_tokens) > 0:
            x = torch.concat(special_tokens + [x], dim=1)

        if pos_embedding is not None and self.pos_embed_special_tokens is True:
            special_pos_embedding = self.pos_embedding[:, : self.num_special_tokens].expand(x.size(0), -1, -1)
            x = x + torch.concat([special_pos_embedding, pos_embedding], dim=1)

        if self.num_special_tokens > 0:
            special_valid_mask = valid_mask.new_ones((x.size(0), self.num_special_tokens))  # type: ignore[union-attr]
            encoder_valid_mask = torch.concat([special_valid_mask, valid_mask], dim=1)
        else:
            encoder_valid_mask = valid_mask

        x = self.encoder(x, attn_mask=encoder_valid_mask[:, None, None, :])
        x = self.norm(x)

        result: TokenRetentionResultType = {}
        if return_keys in ("all", "features"):
            features = x[:, self.num_special_tokens :].transpose(1, 2)
            result["features"] = features.masked_fill(~valid_mask.unsqueeze(1), 0)  # type: ignore[union-attr]

        if return_keys in ("all", "embedding"):
            result["embedding"] = self.embedding_from_features(x, valid_mask)

        return result

    def forward_features(
        self,
        x: torch.Tensor,
        return_input_embedding: bool = False,
        attn_mask: Optional[torch.Tensor] = None,
        *,
        grid_sizes: Optional[torch.Tensor] = None,
        valid_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        if grid_sizes is None:
            return super().forward_features(
                x,
                return_input_embedding=return_input_embedding,
                attn_mask=attn_mask,
            )

        return self._forward_naflex_features(
            x,
            grid_sizes,
            valid_mask,
            return_input_embedding=return_input_embedding,
            attn_mask=attn_mask,
        )

    def embedding_from_features(
        self, features: torch.Tensor, valid_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        return self.embedding_norm(self._pool(features, valid_mask))

    def embedding(
        self, x: torch.Tensor, grid_sizes: Optional[torch.Tensor] = None, valid_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        if grid_sizes is None:
            x = super().forward_features(x)
            return self.embedding_from_features(x)

        x = self._forward_naflex_features(x, grid_sizes, valid_mask)
        return self.embedding_from_features(x, valid_mask)

    def forward(
        self, x: torch.Tensor, grid_sizes: Optional[torch.Tensor] = None, valid_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        x = self.embedding(x, grid_sizes, valid_mask)
        return self.classify(x)

    def set_dynamic_size(self, dynamic_size: bool = True) -> None:
        if dynamic_size is False:
            raise ValueError("NaFlex ViT only supports dynamic mode")

        super().set_dynamic_size(dynamic_size)

    def set_naflex_patch_resampling(self, enabled: bool = True) -> None:
        logger.debug(f"Setting NaFlex patch resampling to: {enabled}")
        self.naflex_patch_resampling = enabled

    def adjust_patch_size(self, patch_size: int) -> None:
        if self.patch_size == patch_size:
            return

        assert self.size[0] % patch_size == 0, "Input shape indivisible by patch size!"
        assert self.size[1] % patch_size == 0, "Input shape indivisible by patch size!"

        logger.debug(f"Setting patch size to: {patch_size}")
        with torch.no_grad():
            conv_proj_weight = interpolate_proj(self.conv_proj.weight, patch_size)

        self.conv_proj.weight = nn.Parameter(conv_proj_weight)
        self.conv_proj.kernel_size = (patch_size, patch_size)
        self.conv_proj.stride = (patch_size, patch_size)
        if self.pos_embedding is not None:
            if self.pos_embed_special_tokens is True:
                num_prefix_tokens = self.num_special_tokens
            else:
                num_prefix_tokens = 0

            with torch.no_grad():
                pos_embedding = adjust_position_embedding(
                    self.pos_embedding,
                    (self.size[0] // self.patch_size, self.size[1] // self.patch_size),
                    (self.size[0] // patch_size, self.size[1] // patch_size),
                    num_prefix_tokens,
                    interpolation_mode=self.pos_embed_interpolation_mode,
                )

            self.pos_embedding = nn.Parameter(pos_embedding)

        self.patch_size = patch_size
        self.max_stride = patch_size
        self.stem_stride = patch_size


# NaFlex Model Naming Convention
# ==============================
#
# All components after the NaFlex prefix follow the ViT / RoPE ViT naming convention documented in _rope_vit_configs.py.
#
# - naflex_     : NaFlex with batched grid_sample position embedding resizing
# - naflex_i_   : NaFlex with per-unique-grid position embedding interpolation

registry.register_model_config(
    "naflex_vit_t16",
    NaFlex_ViT,
    config={"patch_size": 16, **TINY},
)
registry.register_model_config(
    "naflex_vit_s16",
    NaFlex_ViT,
    config={"patch_size": 16, **SMALL},
)
registry.register_model_config(
    "naflex_vit_m16",
    NaFlex_ViT,
    config={"patch_size": 16, **MEDIUM},
)
registry.register_model_config(
    "naflex_vit_b16",
    NaFlex_ViT,
    config={"patch_size": 16, **BASE},
)
registry.register_model_config(
    "naflex_vit_b16_ls",
    NaFlex_ViT,
    config={"patch_size": 16, **BASE, "layer_scale_init_value": 1e-5},
)
registry.register_model_config(  # For SigLIP 2 - https://arxiv.org/abs/2502.14786
    "naflex_i_vit_b16_ap_c1",
    NaFlex_ViT,
    config={
        "patch_size": 16,
        **BASE,
        "class_token": False,
        "attn_pool_head": True,
        "attn_pool_norm_eps": 1e-6,
        "attn_pool_act_layer_type": "gelu_tanh",
        "act_layer_type": "gelu_tanh",
        "pos_embed_interpolation_mode": "bilinear",
        "pos_embed_antialias": True,
        "naflex_pos_embed_resize_mode": "interpolate",
    },
)
registry.register_model_config(
    "naflex_vit_so150m_p14_ap",
    NaFlex_ViT,
    config={"patch_size": 14, **SO150, "class_token": False, "attn_pool_head": True},
)
registry.register_model_config(
    "naflex_vit_l16",
    NaFlex_ViT,
    config={"patch_size": 16, **LARGE},
)
registry.register_model_config(
    "naflex_vit_l14_pn",
    NaFlex_ViT,
    config={"patch_size": 14, **LARGE, "pre_norm": True, "norm_layer_eps": 1e-5},
)
registry.register_model_config(  # For SigLIP 2 - https://arxiv.org/abs/2502.14786
    "naflex_i_vit_so400m_p16_ap_c1",
    NaFlex_ViT,
    config={
        "patch_size": 16,
        **SO400,
        "class_token": False,
        "attn_pool_head": True,
        "attn_pool_norm_eps": 1e-6,
        "attn_pool_act_layer_type": "gelu_tanh",
        "act_layer_type": "gelu_tanh",
        "pos_embed_interpolation_mode": "bilinear",
        "pos_embed_antialias": True,
        "naflex_pos_embed_resize_mode": "interpolate",
    },
)
registry.register_model_config(
    "naflex_vit_so400m_p14_ap",
    NaFlex_ViT,
    config={"patch_size": 14, **SO400, "class_token": False, "attn_pool_head": True},
)

# With registers
####################

registry.register_model_config(
    "naflex_vit_reg1_t16",
    NaFlex_ViT,
    config={"patch_size": 16, **TINY, "num_reg_tokens": 1},
)
registry.register_model_config(
    "naflex_vit_reg1_s16",
    NaFlex_ViT,
    config={"patch_size": 16, **SMALL, "num_reg_tokens": 1},
)
registry.register_model_config(
    "naflex_vit_reg1_s16_ls",
    NaFlex_ViT,
    config={"patch_size": 16, **SMALL, "layer_scale_init_value": 1e-5, "num_reg_tokens": 1},
)
registry.register_model_config(
    "naflex_vit_reg1_s14_ls",
    NaFlex_ViT,
    config={"patch_size": 14, **SMALL, "layer_scale_init_value": 1e-5, "num_reg_tokens": 1},
)
registry.register_model_config(
    "naflex_vit_reg4_s14_nps_ls",
    NaFlex_ViT,
    config={
        "pos_embed_special_tokens": False,
        "patch_size": 14,
        **SMALL,
        "layer_scale_init_value": 1e-5,
        "num_reg_tokens": 4,
    },
)
registry.register_model_config(
    "naflex_vit_reg4_b16",
    NaFlex_ViT,
    config={"patch_size": 16, **BASE, "num_reg_tokens": 4},
)
registry.register_model_config(
    "naflex_vit_reg4_b16_avg",
    NaFlex_ViT,
    config={"patch_size": 16, **BASE, "num_reg_tokens": 4, "class_token": False},
)
registry.register_model_config(
    "naflex_vit_reg4_so150m_p14_avg",
    NaFlex_ViT,
    config={"patch_size": 14, **SO150, "num_reg_tokens": 4, "class_token": False},
)
registry.register_model_config(
    "naflex_vit_reg4_so150m_p14_ls",
    NaFlex_ViT,
    config={"patch_size": 14, **SO150, "layer_scale_init_value": 1e-5, "num_reg_tokens": 4},
)
registry.register_model_config(
    "naflex_vit_reg4_so150m_p14_ap",
    NaFlex_ViT,
    config={"patch_size": 14, **SO150, "num_reg_tokens": 4, "class_token": False, "attn_pool_head": True},
)

# DeiT III
####################

registry.register_model_config(
    "naflex_deit3_t16",
    NaFlex_ViT,
    config={"pos_embed_special_tokens": False, "patch_size": 16, **TINY, "layer_scale_init_value": 1e-5},
)

# With registers
####################

registry.register_model_config(
    "naflex_deit3_reg1_t16",
    NaFlex_ViT,
    config={
        "pos_embed_special_tokens": False,
        "patch_size": 16,
        **TINY,
        "layer_scale_init_value": 1e-5,
        "num_reg_tokens": 1,
    },
)

registry.register_weights(
    "naflex_vit_b16_nepa-generic",
    {
        "url": "https://huggingface.co/birder-project/naflex_vit_b16_nepa-generic/resolve/main",
        "description": (
            "NaFlex ViT B/16 image encoder, pretrained using NEPA on mix of generic datasets. "
            "It has not been fine-tuned for a specific classification task"
        ),
        "resolution": (256, 256),
        "formats": {
            "pt": {
                "file_size": 327.5,
                "sha256": "b0f317c0593b91cbe4c45ca93061dd194b233d70dcbae85065854a74381d215d",
            },
        },
        "net": {"network": "naflex_vit_b16", "tag": "nepa-generic"},
    },
)
registry.register_weights(  # SigLIP 2: https://arxiv.org/abs/2502.14786
    "naflex_i_vit_b16_ap_c1_siglip-v2-webli",
    {
        "url": "https://huggingface.co/birder-project/naflex_i_vit_b16_ap_c1_siglip-v2-webli/resolve/main",
        "description": (
            "NaFlex ViT B/16 image encoder with attention pooling, pretrained by Google using SigLIP v2. "
            "It has not been fine-tuned for a specific classification task"
        ),
        "resolution": (256, 256),
        "formats": {
            "pt": {
                "file_size": 354.6,
                "sha256": "6eda853590c163a612ce9ae66d665559e5687d0454528e8f122934a735ca6bf9",
            },
        },
        "net": {"network": "naflex_i_vit_b16_ap_c1", "tag": "siglip-v2-webli"},
    },
)
registry.register_weights(  # SigLIP 2: https://arxiv.org/abs/2502.14786
    "naflex_i_vit_so400m_p16_ap_c1_siglip-v2-webli",
    {
        "url": "https://huggingface.co/birder-project/naflex_i_vit_so400m_p16_ap_c1_siglip-v2-webli/resolve/main",
        "description": (
            "NaFlex SoViT 400M/16 image encoder with attention pooling, pretrained by Google using SigLIP v2. "
            "It has not been fine-tuned for a specific classification task"
        ),
        "resolution": (256, 256),
        "formats": {
            "pt": {
                "file_size": 1632.4,
                "sha256": "c3c95419bd4ade8449abb2cb8c669317784d23aed5cbd2ba4affca984ce37b64",
            },
        },
        "net": {"network": "naflex_i_vit_so400m_p16_ap_c1", "tag": "siglip-v2-webli"},
    },
)
